// Harbor Health Network's HIPAA audit desk: access controls tested for the annual HIPAA Security
// Rule evaluation (45 CFR 164.308(a)(8)). Regulation citations checked against the eCFR.
import { PROV_OPTS, TERM_OPTS, G4, rowKit } from "../../engine/grcKit.js";
import { ROLES, buildUsers } from "./company";

const { J, X, RR } = rowKit(ROLES);
// The directory as the review population: workforce, agency staff and service accounts.
const people = Object.values(buildUsers());
const agency = people.filter(u => u.type === "Contractor" || u.title === "Agency Nurse").length;
const service = people.filter(u => u.type === "Service").length;
const staff = people.length - agency - service;

export const G = [
 {id:"G1",ctrl:"APD-01",title:"Test new user provisioning",kind:"table",opts:PROV_OPTS,
  intro:"<p><b>APD-01:</b> Access for new workforce members is approved by the manager <i>before</i> provisioning and limited to the role's birthright groups (HIPAA 164.308(a)(4)(ii)(B), access authorization).</p><p>Test the 15 sampled Q3 joiners. Compare approval date to provisioned date, and groups granted to the access matrix (Policy &amp; matrix tab). Pre-hire accounts are created disabled before the start date; that's normal.</p>",
  rows:[J("Aisha Mbeki","Clinical|Registered Nurse","Mon, Jul 6","Keisha Holloway, Jul 1","Jul 2",null,0),
   J("Daniel Osei","Patient Access|Patient Access Representative","Mon, Jul 13","Carmen Velasquez, Jul 8","Jul 9",null,0),
   J("Mei Tanaka","Clinical|Medical Assistant","Mon, Jul 20","Keisha Holloway, Jul 14","Jul 15",null,0),
   J("Rohan Iyer","Revenue Cycle|Billing Specialist","Mon, Jul 20","None on file","Jul 16",null,1),
   J("Sofia Castro","Clinical|Registered Nurse","Mon, Jul 27","Keisha Holloway, Jul 21","Jul 22",null,0),
   J("Emeka Obi","Pharmacy|Pharmacy Technician","Mon, Aug 3","Farid Rahimi, Jul 28","Jul 29",null,0),
   J("Hana Suzuki","Imaging|Radiologic Technologist","Mon, Aug 3","Samuel Achterberg, Jul 29","Jul 30",null,0),
   J("Lars Eriksson","Clinical|Medical Assistant","Mon, Aug 10","Keisha Holloway, Aug 4","Aug 5",null,0),
   J("Nadia Rahman","Clinical|Registered Nurse","Mon, Aug 17","Keisha Holloway, Aug 13","Aug 11",null,2,"Provisioned Aug 11, approved Aug 13."),
   J("Tomas Weber","Patient Access|Patient Access Representative","Mon, Aug 24","Carmen Velasquez, Aug 18","Aug 19",null,0),
   J("Yara Haddad","Pharmacy|Pharmacist","Mon, Aug 31","Farid Rahimi, Aug 25","Aug 26",null,0),
   J("Kofi Amankwah","Clinical|Medical Assistant","Tue, Sep 8","Keisha Holloway, Sep 1","Sep 2",["APP-Lab-Results"],3,"APP-Lab-Results isn't a Medical Assistant birthright group."),
   J("Priya Nair","Revenue Cycle|Billing Specialist","Mon, Sep 14","Luis Arroyo, Sep 9","Sep 10",null,0),
   J("Diego Torres","Clinical|Registered Nurse","Mon, Sep 21","Keisha Holloway, Sep 15","Sep 16",null,0),
   J("Leilani Kealoha","Patient Access|Patient Access Representative","Mon, Sep 28","Carmen Velasquez, Sep 24","Sep 23",null,2,"Provisioned Sep 23, approved Sep 24.")],
  lesson:"Test both halves of the control: approval before access, and access limited to the role. 4 of 15 failed (27%), so APD-01 is not operating effectively. Extra clinical access also breaks HIPAA's minimum necessary standard."},
 {id:"G2",ctrl:"APD-02",title:"Test timely terminations",kind:"table",opts:TERM_OPTS,
  intro:"<p><b>APD-02:</b> Accounts are disabled within <b>one business day</b> of the HR separation date (HIPAA 164.308(a)(3)(ii)(C), termination procedures).</p><p>Test the 12 sampled Q3 separations from the Oct 2 directory extract. Weekends don't count as business days.</p>",
  rows:[X("Joanna Pierce","Registered Nurse","Wed, Jul 8","Wed, Jul 8","Jul 7",0),
   X("Marco Ferri","Billing Specialist","Fri, Jul 10","Mon, Jul 13","Jul 10",0,"Friday to Monday is one business day."),
   X("Ruth Abernathy","Medical Assistant","Thu, Jul 16","Thu, Jul 16","Jul 16",0),
   X("Owen Pryor","Pharmacy Technician","Tue, Jul 21","Tue, Jul 28","Jul 20",1,"Five business days late; no sign-in after separation."),
   X("Celia Moran","Patient Access Representative","Fri, Jul 31","Fri, Jul 31","Jul 30",0),
   X("Grant Whitley","Registered Nurse","Mon, Aug 3","Fri, Aug 14","Aug 7",2,"Opened the EHR on Aug 7, four days after separation."),
   X("Gregory Hale","Facilities Manager","Fri, Aug 14","Not disabled","Sep 5",3,"Still enabled at extract, and used three weeks after he left."),
   X("Ivy Sandoval","Medical Assistant","Fri, Aug 21","Mon, Aug 24","Aug 20",0,"Friday to Monday is one business day."),
   X("Paul Dunmore","Radiologic Technologist","Tue, Sep 1","Tue, Sep 1","Aug 31",0),
   X("Nell Hargrove","Registered Nurse","Thu, Sep 10","Thu, Sep 10","Sep 10",0),
   X("Maya Estrada","Registered Nurse","Fri, Sep 25","Not disabled","Oct 1",3,"Still enabled at extract and signing in. This is the same account from IAM Ops ticket INC0052333."),
   X("Wade Linton","Billing Specialist","Mon, Sep 28","Tue, Sep 29","Sep 28",0,"Next business day is within policy.")],
  lesson:"Measure against the policy exactly: Friday to Monday passes. Keep \"late\" separate from \"late and used\". At a hospital, use after separation can mean a former employee read patient charts."},
 {id:"G3",ctrl:"APD-02",title:"Evaluate the termination exceptions",kind:"quiz",
  intro:"<p>Your APD-02 test found 4 exceptions in 12 samples. Additional facts from follow-up:</p><ul><li>Owen Pryor (Pharmacy Technician) kept pharmacy inventory access for 5 extra business days. Logs show no activity after separation.</li><li>Grant Whitley opened 3 patient charts in the EHR on Aug 7, four days after separation.</li><li>Gregory Hale's account signed in to email on Sep 5. His role has no EHR access.</li><li>Maya Estrada's account is still active and signed in on Oct 1.</li></ul><p>Definitions are on the Controls tab.</p>",
  qs:[{q:"Is APD-02 operating effectively for Q3?",short:"Effectiveness conclusion",opts:["Yes: 8 of 12 passed","No: 4 of 12 (33%) failed, which is well above a tolerable rate for a per-event control"],correct:1,pts:2},
   {q:"Grant Whitley opened patient charts after he left. What happens with that?",short:"Access to PHI after separation",opts:["Document it in the finding only","Refer it to the Privacy Officer now. It's presumed a breach unless a documented risk assessment shows a low probability that the PHI was compromised, and the notification clock runs from discovery.","Ask Grant whether he looked at anything sensitive, and close it if he says no"],correct:1,pts:3},
   {q:"Gregory Hale's account was used after he left, but it has no EHR access. How do you treat it?",short:"Use without PHI access",opts:["No issue, because no patient data was involved","Refer it to Security as a security incident, have the account disabled now, and include it in the finding","Wait for the next quarterly access review"],correct:1,pts:3}],
  lesson:"Under HIPAA, a failed termination control isn't only an audit exception. Access to patient records after someone leaves is a potential breach the Privacy Officer must assess, and any use after separation is a security incident."},
 G4,
 {id:"G5",ctrl:"UAR-01",title:"Review the Q3 access review for completeness",kind:"quiz",
  intro:"<p><b>UAR-01:</b> Each quarter, managers certify <i>all</i> directory accounts (workforce, agency staff, service accounts). Revocations are completed within 5 business days. HIPAA 164.308(a)(4)(ii)(C) calls for procedures to \"review\" a user's right of access.</p>",
  evidence:[["Directory extract, Sep 30",`${people.length} accounts: ${staff} workforce members, ${agency} agency staff, ${service} service accounts`],["Access review file",`${staff} accounts, all certified by managers`],["Reviewer sign-off","Rashid Karimi, Oct 1"],["Population source","Excel export provided by IT; no query or run parameters attached"]],
  qs:[{q:"What is the main issue?",short:"Issue identified",opts:[`Completeness: the ${agency} agency staff and ${service} service accounts were left out of the review`,"Timeliness: sign-off came after quarter end","Accuracy: managers certified too quickly","No issue"],correct:0,pts:3},
   {q:"What evidence do you request? Select all that apply.",multi:true,opts:["A system-generated population with the query, parameters and run date",`Review evidence for the ${agency + service} excluded accounts`,"An email from IT confirming the review was complete","Re-perform the whole review yourself"],correct:[0,1]},
   {q:"Until those accounts are reviewed, can UAR-01 be relied on to catch the access APD-02 missed?",short:"Reliance on UAR-01",opts:["Yes","No"],correct:1,pts:2}],
  lesson:"Before testing a review, test the population. Agency nurses and service accounts are the usual gaps, and agency staff open patient charts every shift."},
 {id:"G6",ctrl:"RISK",title:"Rate the HIPAA risk register",kind:"table",opts:["High","Medium","Low"],
  intro:"<p>HIPAA requires an accurate and thorough risk analysis (164.308(a)(1)(ii)(A)). Rate each risk's inherent level. Score = likelihood × impact. <b>High</b> 15–25, <b>Medium</b> 8–14, <b>Low</b> 1–7.</p><p class=\"mono\" style=\"font-size:12px\">Likelihood: Rare 1 · Unlikely 2 · Possible 3 · Likely 4 · Almost certain 5<br>Impact: Minimal 1 · Minor 2 · Moderate 3 · Major 4 · Severe 5</p>",
  rows:[RR("R-01 Former workforce keep EHR access","APD-02 failures; 2 accounts used after separation","Likely","Severe",0),
   RR("R-02 Shared nursing-station login","Requested by 3 West","Possible","Moderate",1),
   RR("R-03 Standing EHR admin and break-glass grants","6 standing break-glass users found","Possible","Severe",0),
   RR("R-04 Clearinghouse SOC 2 coverage gap","MedBridge report ends Jun 30","Unlikely","Moderate",2),
   RR("R-05 MFA fatigue attacks","One successful push approval this week","Likely","Moderate",1)],
  lesson:"Apply the matrix the same way every time. The risk analysis drives what gets fixed first, so R-01 (20) and R-03 (15) lead the risk management plan."},
 {id:"G7",ctrl:"VEN-01",title:"Review a business associate's SOC 2 report",kind:"quiz",
  intro:"<p>MedBridge Clearinghouse submits Harbor Health's insurance claims, so it handles PHI as a business associate. The audit period ends Dec 31.</p>",
  evidence:[["Report","SOC 2 Type II, Security and Confidentiality"],["Period","Oct 1, 2025 to Jun 30, 2026"],["Opinion","Unqualified"],["Exception","CC6.2: 2 of 25 sampled terminated users were removed late. Management response: automated deprovisioning implemented Jul 2026."],["Subservice org","Microsoft Azure (carve-out method)"],["Complementary user entity controls","1) Customers notify MedBridge of terminated users within 1 business day. 2) Customers review their users' access quarterly."],["Business associate agreement","Signed Mar 2021. Covers claims submission only; MedBridge added eligibility checks in 2025."]],
  qs:[{q:"Which follow-ups are needed? Select all that apply.",multi:true,opts:["Get a bridge letter covering Jul 1 to Dec 31","Evaluate whether the CC6.2 exception affects our reliance","Confirm our own user entity controls (termination notice, quarterly review) are operating","Get and review Azure's SOC report for the carved-out subservice","Update the business associate agreement to cover the eligibility checks","Drop the vendor because the report has an exception","No action needed; the opinion is unqualified"],correct:[0,1,2,3,4]},
   {q:"Why does your APD-02 result matter for this review?",short:"Link to APD-02",opts:["It doesn't; it's a different system","MedBridge relies on us to report terminations on time. Our late terminations mean that user entity control is failing.","It means MedBridge's opinion should be qualified"],correct:1,pts:3}],
  lesson:"A clean SOC 2 opinion isn't the end of the review. Cover the gap period, weigh the exceptions, check the carved-out subservice provider, confirm your own side of the user entity controls, and make sure the business associate agreement covers what the vendor actually does."},
 {id:"G8",ctrl:"POL-EX",title:"Decide a policy exception request",kind:"quiz",
  intro:"<p>After IAM Ops rejected the shared <span class=\"mono\">3west-station</span> login, Nursing filed a formal policy exception: \"Nurses lose 20 minutes a shift to workstation sign-ins. Badge-tap single sign-on is budgeted for Q2 2027.\"</p>",
  qs:[{q:"What is the decision?",short:"Exception decision",opts:["Deny outright; policy is policy","Approve as asked: one shared login for the workstation and the EHR","Approve temporarily for the workstation sign-in only, with every nurse still signing in to the EHR individually, compensating controls and risk owner sign-off"],correct:2,pts:3},
   {q:"Which conditions belong in the approval? Select all that apply.",multi:true,opts:["The shared login opens the workstation only; every EHR session uses the nurse's own account","Expiry of 90 days or less, with re-review","EHR automatic logoff after a short idle period","Sign-off by the risk owner (the Chief Nursing Officer)","Tracked project to replace it with badge-tap single sign-on","Let the shared login open the EHR too, to save time","Tape the password to the monitor for night shift"],correct:[0,1,2,3,4]}],
  lesson:"GRC's job is managed risk, not saying no. HIPAA's unique user identification is a required specification, so the exception can't reach the EHR itself. Keep it narrow, time-limited, compensated and owned by the business."},
 {id:"G9",ctrl:"MAP",title:"Map APD-02 to frameworks",kind:"quiz",
  intro:"<p>Map APD-02 (disable accounts within one business day of separation) so one test can answer several reviews.</p>",
  qs:[{q:"Select every requirement APD-02 supports.",multi:true,opts:["HIPAA 164.308(a)(3)(ii)(C) Termination procedures","NIST 800-53 PS-4 Personnel Termination","NIST 800-53 AC-2 Account Management","ISO 27001:2022 A.5.18 Access rights","SOC 2 CC6.2 (removal of credentials)","HIPAA 164.308(a)(7)(ii)(A) Data backup plan","HIPAA 164.310(d)(2)(i) Disposal","NIST 800-53 CP-9 System Backup","ISO 27001:2022 A.8.13 Information backup"],correct:[0,1,2,3,4]}],
  lesson:"Test once, satisfy many. A mapped control lets one set of APD-02 evidence answer the HIPAA evaluation, a SOC 2 request from a partner, and an ISO audit."},
 {id:"G10",ctrl:"APD-02",title:"Write the termination finding",kind:"quiz",
  intro:"<p>Build the APD-02 finding. Pick the strongest statement for each element.</p>",
  qs:[{q:"Condition",short:"Condition",opts:["Access was removed late for some staff.","4 of 12 sampled separations (33%) were not disabled within one business day. Two accounts were still active at extract, and two former workforce members used their accounts after leaving, one to open patient charts.","IT doesn't take separations seriously."],correct:1,pts:2},
   {q:"Criteria",short:"Criteria",opts:["The Termination Procedures policy requires accounts to be disabled within one business day of the HR separation date (control APD-02), implementing HIPAA 164.308(a)(3)(ii)(C).","Best practice says access should be removed quickly.","HIPAA requires same-day removal."],correct:0,pts:2},
   {q:"Cause",short:"Cause",opts:["The service desk was careless.","Unknown.","Separations are processed by hand from HR emails. There is no automated HR-to-directory trigger or daily reconciliation."],correct:2,pts:2},
   {q:"Effect",short:"Effect",opts:["Harbor Health will be fined.","Former workforce members could reach ePHI after leaving, and one did (3 patient charts, now under breach assessment).","No impact, because nothing was stolen."],correct:1,pts:2},
   {q:"Recommendation",short:"Recommendation",opts:["Automate deprovisioning from the HR separation event, and add a daily HR-to-directory reconciliation with exceptions reviewed by the Security Official.","Remind the service desk to be faster.","Remove all users' access every quarter."],correct:0,pts:2}],
  lesson:"A finding that holds up is specific (numbers), cites the actual requirement, names a fixable cause, states real impact without exaggeration, and recommends a fix that addresses the cause."}
];
