// Harbor Health Network's PAM shift. The kit (lib/pamKit.js) supplies grading, hints, the playbook
// and the PAM runbook; this file is the story. Lessons cite the HIPAA Security Rule (45 CFR 164)
// and NIST SP 800-53 Rev. 5.
import { buildPam } from "../lib/pamKit.js";
import * as company from "./company";
import * as policy from "./policy";

const hipaa = id => ({ label: `45 CFR ${id}`, href: "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-C" });
const n53 = id => ({ label: `NIST SP 800-53 Rev. 5, ${id}`, href: "https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final" });
const ADMIN = "IT|Systems Administrator", STAFF = ["GRP-All-Staff", "APP-Office-Suite", "APP-Service-Desk-Agent"];

export const pam = buildPam({
  id: "harbor-health",
  eligible: { [ADMIN]: ["ROLE-Server-Admin"], "IT|EHR Analyst": ["ROLE-EHR-Security-Admin"], "IT|IT Director": ["ROLE-User-Admin"], "Vendors|PACS Vendor Support": ["ROLE-PACS-Admin"] },
  also: ["ROLE-Global-Admin"],
  roles: { [ADMIN]: [...STAFF, "ROLE-Server-Admin"], "Vendors|PACS Vendor Support": ["GRP-Contractors"] },
  cast: [
    ["anika.rao", "Anika Rao", "HHN-10191", "IT|EHR Analyst", "Rashid Karimi"],
    ["tobias.weller", "Tobias Weller", "HHN-10193", ADMIN, "Rashid Karimi", { groups: [...STAFF, "ROLE-Server-Admin"] }],
    ["marisol.vega", "Marisol Vega", "HHN-10195", "IT|Service Desk Analyst", "Rashid Karimi", { groups: [...STAFF, "ROLE-Helpdesk-Admin", "ROLE-EHR-Security-Admin"] }],
    ["hollis.mercer", "Hollis Mercer", "HHN-10197", ADMIN, "Rashid Karimi"],
    ["priyanka.das", "Priyanka Das", "HHN-10199", ADMIN, "Rashid Karimi", { groups: [...STAFF, "ROLE-Server-Admin"], jit: { "ROLE-Server-Admin": 2 } }],
    ["dorian.blake", "Dorian Blake", "HHN-10201", ADMIN, "Rashid Karimi"],
    ["jasper.quinn", "Jasper Quinn", "HHN-10203", "IT|Service Desk Analyst", "Rashid Karimi"],
    ["gunnar.eklund", "Gunnar Eklund", "HHN-V-0217", "Vendors|PACS Vendor Support", "Rashid Karimi (sponsor)", { type: "Contractor", enabled: false, expiry: 220, last: 27 }],
    ["bg-admin-01", "bg-admin-01", "BG-01", null, "Rashid Karimi (owner)", { dept: "IT", title: "Break-glass account: emergency Global Admin", type: "Break-glass", groups: ["ROLE-Global-Admin"], enabled: false, mfa: false, last: 240 }],
  ],
  hr: [{ type: "Termination", who: "Dorian Blake", detail: "Involuntary. Effective today, 9:30 AM. Systems Administrator with server admin eligibility.", when: 0 }],
  cite: { "pam-jit": [hipaa("164.308(a)(4)(ii)(B)"), n53("AC-6(5)")], "pam-eligible": [hipaa("164.308(a)(3)(ii)(A)"), n53("AC-2(7)")], "pam-breakglass": [hipaa("164.312(a)(2)(ii)"), n53("AC-2(2)")],
    "pam-vault": [hipaa("164.308(a)(5)(ii)(D)"), n53("IA-5")], "pam-session": [hipaa("164.312(b)"), n53("AC-6(9)")], "pam-vendor": [hipaa("164.308(b)(1)"), n53("AC-17(4)")], "pam-shared": [hipaa("164.312(a)(2)(i)")] },
  mon: {
    jit: { id: "REQ0028101", uid: "anika.rao", group: "ROLE-EHR-Security-Admin", hours: 2, change: "CHG0051220", approver: "Renee Kowalski",
      what: "set up the EHR security classes for the new oncology clinic", from: "Anika Rao", channel: "Portal", opened: "6:40 AM",
      lesson: "Activate an eligible role for the approved window only, with the approval on the ticket first. HIPAA 164.308(a)(4)(ii)(B) (access authorization); NIST AC-6(5)." },
    breakGlass: { id: "INC0053101", uid: "rashid.karimi", bg: "bg-admin-01", title: "Emergency: admins locked out, need break-glass", from: "Rashid Karimi", channel: "Phone", opened: "7:02 AM",
      body: "<p>\"It's Rashid. The identity provider's MFA service is down and none of the admins can sign in. The interface to the lab system has stalled and results aren't reaching the ED. I'm declaring an emergency. Enable bg-admin-01, please.\"</p>",
      lesson: "Emergency access is required by HIPAA, and it's real admin power. Verify the caller, enable only the documented account, and tell Security at once. HIPAA 164.312(a)(2)(ii) (emergency access procedure)." },
    notEligible: { id: "REQ0028104", uid: "jasper.quinn", group: "ROLE-EHR-Security-Admin", title: "EHR security admin for the service desk", from: "Jasper Quinn", channel: "Portal", opened: "7:20 AM",
      body: "<p>Half my calls are nurses missing an EHR permission after a float. If I had EHR security admin I could fix their security class myself instead of waiting for the EHR team. Rashid's approved it.</p>",
      alt: "explain that Service Desk Analysts aren't eligible for ROLE-EHR-Security-Admin. EHR security changes go to an EHR Analyst.",
      lesson: "Eligibility for a privileged role comes from the job. A manager's approval can't add a role the job doesn't include. HIPAA 164.308(a)(3)(ii)(A) (authorization and supervision)." },
    rotate: { id: "REQ0028107", svc: "svc-hl7", down: "The HL7 interface between the EHR and the lab system", title: "svc-hl7 password in a vendor ticket", from: "Wen Zhao", channel: "Portal", opened: "7:35 AM",
      body: "<p>While troubleshooting the lab interface, someone attached a config file with the <span class=\"mono\">svc-hl7</span> password in plain text to a ticket in the vendor's public support portal. The vendor has taken the attachment down, but it was up for about 12 hours.</p><p>Please deal with the password. The interface has to keep running: lab results flow through it.</p>",
      lesson: "An exposed service credential is rotated, not disabled. Lab results keep flowing and the leaked password stops working. HIPAA 164.308(a)(5)(ii)(D) (password management)." },
    standing: { id: "TSK0012101", holders: [["tobias.weller", "ROLE-Server-Admin"], ["marisol.vega", "ROLE-EHR-Security-Admin"]], bg: "bg-admin-01", bgGroup: "ROLE-Global-Admin",
      title: "PAM report: standing privileged memberships", from: "PAM vault (weekly report)", channel: "Automated", opened: "7:55 AM",
      body: "<p>These accounts hold a vaulted role permanently instead of activating it:</p><ul><li><span class=\"mono\">tobias.weller</span>: ROLE-Server-Admin (since the vault migration)</li><li><span class=\"mono\">marisol.vega</span>: ROLE-EHR-Security-Admin (added during the EHR upgrade in July)</li><li><span class=\"mono\">bg-admin-01</span>: ROLE-Global-Admin</li></ul><p>Clean up the standing access per the PAM runbook.</p>",
      lesson: "Standing admin access to systems holding ePHI is the gap PAM closes. Remove it, except where the runbook documents an exception. HIPAA 164.308(a)(4)." },
    adminLeaver: { id: "REQ0028110", uid: "dorian.blake", svc: "svc-ehr-backup", title: "Termination: Dorian Blake, Systems Administrator", from: "HR system (automated)", channel: "HR integration", opened: "8:10 AM",
      body: "<p>Involuntary termination, effective 9:30 AM today. Remove all access before the meeting.</p><p>PAM vault note: Dorian checked out the <span class=\"mono\">svc-ehr-backup</span> password last Thursday and it hasn't been rotated since.</p>",
      lesson: "An admin leaver's access ends only when what they knew stops working: rotate any credential they checked out. HIPAA 164.308(a)(3)(ii)(C) (termination procedures)." },
    vendor: { id: "REQ0028113", uid: "gunnar.eklund", group: "ROLE-PACS-Admin", hours: 2, title: "Vendor support session: PACS storage fix", from: "Rashid Karimi", channel: "Portal", opened: "8:25 AM",
      body: "<p>Gunnar from the PACS vendor needs admin on the imaging servers to fix the archive that stopped accepting new studies. The session is booked from 9:00 to 11:00 AM. His account is off between sessions.</p>",
      lesson: "Vendor access is opened for one approved session: sponsor approval, the account enabled, the role for the session only. HIPAA 164.308(b)(1) (business associates); NIST AC-17(4)." },
    noChange: { id: "REQ0028116", uid: "hollis.mercer", group: "ROLE-Server-Admin", target: "The imaging archive server", title: "Server admin for the weekend", from: "Hollis Mercer", channel: "Portal", opened: "8:55 AM",
      body: "<p>I want to clear out old scratch folders on the imaging archive server over the weekend while volumes are low. Can you activate server admin for me from Friday evening to Sunday night, about 48 hours? There's no change raised, it's routine cleanup.</p>",
      alt: "explain that eligibility isn't enough: the work needs an approved change, and activations are capped at 4 hours.",
      lesson: "Eligible isn't approved. Privileged roles are activated for an approved change, for a short window. NIST AC-6(5)." },
    session: { id: "REQ0028119", title: "Weekly privileged session review", from: "Privacy and Security Office", channel: "Email", opened: "9:20 AM",
      intro: "<p>Yesterday's recorded admin sessions are below. Check each one against the change or incident it was opened for, and send us the IDs of any session that went outside it.</p>",
      rows: [
        ["PSM-40211", "tobias.weller", "CHG0051190: patch the lab interface server", "HL7-ENG-01", "Installed patches, restarted the interface engine, confirmed messages flowing", false],
        ["PSM-40216", "hollis.mercer", "CHG0051194: replace the print server", "PRN-02", "Moved print queues, <b>queried the EHR database for a local celebrity's chart</b>", true],
        ["PSM-40223", "priyanka.das", "INC0053050: slow image loading", "PACS-APP-01", "Read performance counters, restarted the viewer service", false],
        ["PSM-40229", "tobias.weller", "CHG0051199: add storage to the EHR database server", "EHR-DB-01", "Extended the volume, <b>turned off audit logging on the EHR database</b>", true],
        ["PSM-40235", "anika.rao", "CHG0051201: renew the patient portal certificate", "PORTAL-01", "Imported the new certificate, restarted the web service", false],
      ],
      lesson: "A recorded session only protects patients if someone compares it with the reason it was opened. HIPAA 164.312(b) (audit controls) and 164.308(a)(1)(ii)(D) (activity review)." },
    compromised: { id: "INC0053104", uid: "priyanka.das", group: "ROLE-Server-Admin", title: "SIEM alert: admin sign-in from abroad", from: "SIEM alert", channel: "Automated", opened: "9:40 AM",
      body: "<p>At 5:51 AM <span class=\"mono\">priyanka.das</span> approved an MFA prompt after 22 push requests, signed in from an IP address in Vietnam, and activated ROLE-Server-Admin for 2 hours. Priyanka was asleep and says she approved a prompt to make the phone stop.</p>",
      lesson: "A compromised admin account is contained when the attacker has nothing left: no session, password, MFA method or privileged role. Then Security takes it. HIPAA 164.308(a)(6)(ii) (response and reporting)." },
    shared: { id: "REQ0028122", uid: "kyle.morrison", title: "Admin password for the night shift", from: "Kyle Morrison", channel: "Portal", opened: "9:55 AM",
      body: "<p>Nights have no admin on site and the night desk keeps getting stuck on printer and badge-reader servers. Could we tape the server admin password inside the night desk binder, or make a shared <span class=\"mono\">nightadmin</span> login?</p>",
      alt: "explain that admin passwords are never shared. Night-shift admins check credentials out of the vault under their own accounts, and urgent work goes to the on-call Systems Administrator.",
      lesson: "Shared admin credentials make every change anonymous. HIPAA requires unique user identification. HIPAA 164.312(a)(2)(i)." },
    auditQ: { id: "REQ0028125", group: "ROLE-Server-Admin", title: "Risk analysis request: who holds server admin", from: "Compliance (HIPAA risk analysis)", channel: "Email", opened: "10:10 AM",
      body: "<p>For the annual HIPAA risk analysis, please list every enabled account that holds <span class=\"mono\">ROLE-Server-Admin</span> right now, including any just-in-time activations still running. Usernames are fine.</p>",
      lesson: "Evidence for a risk analysis is pulled from the system as it stands. HIPAA 164.308(a)(1)(ii)(A) (risk analysis)." },
  },
  thu: {
    bgClose: { id: "TSK0012104", from: "Rashid Karimi", channel: "Portal", opened: "10:35 AM",
      body: "<p>MFA is back and the admins can sign in. Emergency over as of 10:30 AM. Please close out bg-admin-01 per the break-glass procedure.</p>",
      lesson: "Emergency access is closed as deliberately as it's opened: disabled, rotated and signed out. HIPAA 164.312(a)(2)(ii); NIST AC-2(2)." },
    vendorEnd: { id: "TSK0012107", from: "Rashid Karimi", channel: "Portal", opened: "11:00 AM",
      body: "<p>Gunnar fixed the archive and new studies are coming in. Please close his access.</p>",
      lesson: "Third-party access ends with the session. NIST AC-17(4)." },
  },
  conseq: {
    standingJit: { id: "INC0053110", from: "PAM vault", channel: "Automated", opened: "Afternoon" },
    notEligible: { id: "INC0053113", from: "Privacy and Security Office", channel: "Email", opened: "Afternoon" },
    svcDown: { id: "INC0053116", from: "Emergency department", channel: "Phone", opened: "Afternoon" },
    svcLeak: { id: "INC0053119", from: "SIEM alert", channel: "Automated", opened: "Afternoon" },
    leaver: { id: "INC0053122", from: "Privacy and Security Office", channel: "Email", opened: "Afternoon" },
    noChange: { id: "INC0053125", from: "Privacy and Security Office", channel: "Email", opened: "Afternoon" },
    compromised: { id: "INC0053128", from: "SIEM alert", channel: "Automated", opened: "Afternoon" },
    bgOpen: { id: "INC0053131", from: "PAM vault", channel: "Automated", opened: "Afternoon" },
    vendorOpen: { id: "INC0053134", from: "Privacy and Security Office", channel: "Email", opened: "Afternoon" },
  },
}, company, policy);
