// Harbor Health Network's shift on the service desk. The kit (lib/ticketKit.js) supplies grading,
// hints, the playbook and Jordan Reyes' shift; this file is the story. Lessons cite the HIPAA
// Security Rule (45 CFR Part 164, Subpart C) and NIST SP 800-53 Rev. 5.
import { buildTicketSet } from "../lib/ticketKit.js";
import { ROLES, SOD, buildUsers } from "./company";
import { G } from "./grc.js";

const m = x => `<span class="mono">${x}</span>`;

export const set = buildTicketSet({
  id: "harbor-health", ROLES, SOD, buildUsers,
  mon: {
    joiner: { id: "REQ0027104", uid: "jada.okonkwo", rk: "Clinical|Registered Nurse", title: "New hire: Jada Okonkwo, Registered Nurse",
      from: "HR system (automated)", channel: "HR integration", opened: "6:05 AM",
      body: "<p>New hire starting today on 3 West. The pre-hire account was created by the HR sync but is disabled with no access.</p><p>Please activate the account and provision access for the role. Her first shift starts at 7:00 AM.</p>",
      lesson: "Provision clinical access from the role in the access matrix, nothing more. HIPAA 164.308(a)(4)(ii)(B) (access authorization); NIST AC-2, AC-6." },
    callerPw: { id: "INC0052311", uid: "monique.dubois", title: "Forgot password after vacation",
      from: "Monique Dubois", channel: "Phone", opened: "7:41 AM",
      body: "<p>\"Hi, I just got back from a week off and my password expired while I was gone. I tried a new one and now I can't remember which. Can you reset it? I've got claims to get out before the 10 o'clock cutoff.\"</p>",
      lesson: "Verify identity against the system of record before any credential reset. HIPAA 164.312(d) (person or entity authentication); NIST IA-5." },
    callerLock: { id: "INC0052314", uid: "lorraine.pittman", title: "Locked out at the registration desk",
      from: "Lorraine Pittman", channel: "Phone", opened: "7:52 AM",
      body: "<p>\"The registration kiosk kept rejecting me, so I typed my password a few too many times and now it says I'm locked. I know my password. I've got patients lining up.\"</p>",
      lesson: "A lockout is not a forgotten password. Unlock only; a reset adds risk and slows the front desk for no reason." },
    callerMfa: { id: "INC0052318", uid: "elias.morrow", title: "New phone, can't sign prescriptions",
      from: "Dr. Elias Morrow", channel: "Phone (desk line)", opened: "8:01 AM",
      body: "<p>\"My phone was stolen at the gym last night. It had the authenticator app on it. I've got a new phone, but I can't approve sign-ins or sign controlled-substance prescriptions until MFA is set up again. Clinic starts at 8:30.\"</p>",
      lesson: "Clear the stolen authenticator and end sessions the phone may still hold. DEA rules require two-factor authentication to sign controlled-substance prescriptions, so this one is urgent. HIPAA 164.312(d); NIST IA-5, AC-12." },
    leaver: { id: "REQ0027112", uid: "victor.halvorsen", title: "Termination: Victor Halvorsen, effective 10:00 AM",
      from: "Olivia Brandt (HR Director)", channel: "HR integration", opened: "8:06 AM",
      body: "<p>Involuntary termination effective today at 10:00 AM, following a pharmacy inventory review. Remove all access per the leaver policy before he is told.</p>",
      lesson: "Leavers: disable, revoke sessions, remove all access. HIPAA 164.308(a)(3)(ii)(C) (termination procedures); NIST PS-4, AC-2." },
    mover: { id: "REQ0027115", uid: "leticia.moreno", fromRk: "Patient Access|Patient Access Representative", toRk: "Revenue Cycle|Billing Specialist",
      title: "Transfer: Leticia Moreno, Patient Access to Billing", from: "HR system (automated)", channel: "HR integration", opened: "8:14 AM",
      body: "<p>Leticia Moreno is moving from Patient Access Representative to Billing Specialist (Revenue Cycle), effective today. New manager: Luis Arroyo. Update her job info and access.</p>",
      lesson: "Movers are where privilege creep starts. Remove the old role's access, not just add the new. HIPAA 164.308(a)(4)(ii)(C) (access establishment and modification); NIST PS-5." },
    sodReq: { id: "REQ0027119", uid: "quentin.ashworth", group: "APP-EHR-Orders-Sign", holds: "APP-Pharmacy-Dispense",
      title: "Access request: order signing for Quentin Ashworth", from: "Quentin Ashworth", channel: "Self-service portal", opened: "8:22 AM",
      approval: "Farid Rahimi replied: \"Approved. It'll save the night pharmacist a phone call on verbal orders.\"",
      alt: "suggest the night pharmacist sends verbal orders to the on-call provider to sign, so ordering and dispensing stay with two different people.",
      body: `<p>Requesting ${m("APP-EHR-Orders-Sign")} so I can enter and sign verbal medication orders on night shift instead of paging the provider.</p>`,
      lesson: "Manager approval doesn't override separation of duties. The person who dispenses a drug must never be the person who orders it. HIPAA 164.308(a)(4)(ii)(B); NIST AC-5." },
    request: { id: "REQ0027123", uid: "corinne.faulkner", group: "APP-PACS-Viewer", approver: "Keisha",
      title: "Access request: imaging viewer", from: "Corinne Faulkner", channel: "Self-service portal", opened: "8:29 AM",
      approval: "Keisha Holloway replied: \"Approved. Corinne is covering the wound care clinic and needs to see the wound photos.\"",
      body: `<p>Requesting ${m("APP-PACS-Viewer")} to view wound imaging while I cover the wound care clinic this quarter.</p>`,
      lesson: "Requestable access needs a documented approval before it's granted, and only what was asked: HIPAA's minimum necessary standard applies. 164.308(a)(4)(ii)(B); NIST AC-2, AC-6." },
    exec: { id: "INC0052326", uid: "renee.kowalski", saidEmpId: "HHN-10070", title: "URGENT: CFO locked out before payroll funding",
      from: "Caller says: Renee Kowalski (CFO)", channel: "Phone (unknown mobile number)", opened: "8:34 AM",
      body: "<p>\"This is Renee Kowalski. I'm at the healthcare finance conference in Chicago and my phone died. I'm on a borrowed one. Move my MFA to this number now. If payroll isn't funded by 9, three hundred nurses don't get paid Friday.\"</p>",
      lesson: "Urgency plus authority plus a new device is the classic social-engineering pattern. Check the details, refuse, and report it. HIPAA 164.312(d), 164.308(a)(6)(ii); NIST IA-5, IR-6." },
    contractor: { id: "REQ0027127", uid: "tessa.lindqvist", title: "Extend agency nurse: Tessa Lindqvist",
      from: "Keisha Holloway (sponsor)", channel: "Email", opened: "8:41 AM",
      approval: "Keisha Holloway (sponsor) replied: \"Approved. The agency renewed her assignment for 13 weeks.\"",
      body: "<p>Tessa's agency assignment was renewed. Her account expires in 2 days. Please extend it for the new assignment.</p>",
      lesson: "Agency staff accounts always have an end date and a sponsor approval, capped at 90 days per extension. HIPAA 164.308(a)(3)(ii)(C); NIST AC-2(2), PS-7." },
    sweep: { id: "TSK0009208", dormant: [["theresa.quinlan", 121], ["patrick.doyle", 96]], under: ["gloria.fitzgerald", 89], svc: "svc-ehr-backup",
      title: "Weekly: disable inactive accounts", from: "Scheduled report", channel: "Automated task", opened: "8:47 AM",
      body: "<p>Weekly inactive-account sweep. Per policy, disable any user account with no sign-in for more than 90 days. Pre-hire accounts are excluded.</p><p>Use the Directory's sort by last sign-in.</p>",
      lesson: "Dormant accounts with access to patient records are a favorite target. Apply the threshold exactly, and send service accounts to their owner instead of breaking a production job. NIST AC-2(3)." },
    recon: { id: "INC0052333", uid: "maya.estrada", left: "Sep 25", signedIn: "yesterday",
      title: "HR reconciliation: former nurse still active", from: "HR-to-directory reconciliation report", channel: "Automated report", opened: "8:55 AM",
      body: "<p>The weekly HR reconciliation found an account that is still enabled for a person HR shows as separated. Check the HR feed and the account's last sign-in.</p>",
      lesson: "A former workforce member who can still open patient charts is a security incident, and possibly a breach. Contain it, then report it. HIPAA 164.308(a)(3)(ii)(C), 164.308(a)(6)(ii); NIST PS-4, IR-4." },
    priv: { id: "REQ0027131", uid: "kyle.morrison", group: "ROLE-EHR-Security-Admin",
      route: "point Kyle to the EHR team: EHR security changes need Change Advisory Board approval and are made by the EHR analysts.",
      title: "Need EHR Security Admin to fix a template", from: "Kyle Morrison (Service Desk)", channel: "Teams message", opened: "9:03 AM",
      body: "<p>\"Can you put me in EHR Security Admin for the day? Dr. Pike's order templates are broken and the EHR analysts are slammed. Rashid said it's fine.\"</p>",
      lesson: "EHR security administration is never granted by ticket. It changes who can see every patient's record, so it goes through change control. HIPAA 164.308(a)(4)(ii)(B); NIST AC-6(5)." },
    rehire: { id: "REQ0027134", uid: "naomi.castell", rk: "Clinical|Medical Assistant", pwAge: "10-month",
      title: "Rehire: Naomi Castell, Medical Assistant", from: "HR system (automated)", channel: "HR integration", opened: "9:08 AM",
      body: "<p>Rehire starting today. The HR sync matched her existing disabled account. Reactivate and provision for the role.</p>",
      lesson: "Rehires carry old access and old passwords. Check access against the role, and issue a fresh credential. HIPAA 164.308(a)(4)(ii)(C); NIST AC-2, IA-5." },
    shared: { id: "REQ0027138", uid: "keisha.holloway",
      alt: "offer badge-tap single sign-on for the nursing station workstations so each nurse signs in with a tap.",
      title: "Shared login for the 3 West nursing station", from: "Keisha Holloway (Nurse Manager)", channel: "Email", opened: "9:14 AM",
      body: `<p>"Can we get one login like ${m("3west-station")} for the workstation at the nursing station? Nurses lose minutes every hour logging in and out between patients."</p>`,
      lesson: "Shared accounts destroy accountability: nobody can say who opened which chart. HIPAA requires unique user identification, 164.312(a)(2)(i); NIST IA-2." },
    review: { id: "REQ0027141", uid: "delphine.okafor", group: "APP-Lab-Results",
      title: "Access review action: remove lab results", from: "Q3 access review (Keisha Holloway)", channel: "Access review", opened: "9:19 AM",
      body: "<p>Q3 user access review result: reviewer Keisha Holloway marked <b>Delphine Okafor: APP-Lab-Results</b> as <b>Revoke</b> (\"Medical assistants don't release results\"). All other entitlements certified.</p>",
      lesson: "A review only counts if the revocations are carried out and evidenced. Remove exactly what the reviewer marked. HIPAA 164.308(a)(4)(ii)(C); NIST AC-2(j)." },
    loa: { id: "REQ0027144", uid: "siddharth.rao", title: "Leave of absence: Siddharth Rao",
      from: "HR system (automated)", channel: "HR integration", opened: "9:24 AM",
      body: "<p>Siddharth Rao begins medical leave today. Expected return Dec 14, 2026. Apply the leave of absence policy.</p>",
      lesson: "Leave is not termination. Disable to block use, but keep entitlements so he returns on day one. NIST AC-2." },
    copy: { id: "REQ0027147", uid: "ben.castellanos", peer: "tamara.lindsey", rk: "Patient Access|Patient Access Representative", extras: ["APP-EHR-Billing", "APP-Finance-Reports"],
      title: "New hire Ben Castellanos: \"same as Tamara\"", from: "Carmen Velasquez (Patient Access Manager)", channel: "Email", opened: "9:31 AM",
      body: "<p>\"Ben starts at registration today. Just give him whatever Tamara Lindsey has so she can train him. Thanks!\"</p>",
      lesson: "Never mirror a peer. Peers carry leftover access, and copying spreads it to more patient data. Provision from the role, and flag the peer's extras for review. HIPAA minimum necessary; NIST AC-6." },
    auditQ: { id: "REQ0027150", groups: ["APP-EHR-Orders-Sign", "APP-Pharmacy-Dispense"],
      title: "Privacy Officer request: order and dispense conflicts", from: "Beatrice Njoroge (Privacy Officer)", channel: "Email", opened: "9:38 AM",
      body: "<p>\"For the controlled-substance diversion review, please list every <b>enabled</b> user who currently holds <b>both</b> APP-EHR-Orders-Sign and APP-Pharmacy-Dispense.\"</p><p>Enter usernames (first.last) separated by commas, or <b>none</b>, in the answer box when you close the ticket.</p>",
      lesson: "Audit evidence must be complete and accurate. Pull it from the system, not from memory. Remediation is a separate, approved change. HIPAA 164.308(a)(1)(ii)(D); NIST AC-5." },
    compromise: { id: "INC0052342", uid: "felicity.ward", title: "Impossible travel + MFA fatigue: Felicity Ward",
      from: "Identity protection alert", channel: "SIEM alert", opened: "9:46 AM",
      body: "<p>High-risk sign-in. Felicity Ward signed in from Portland at 9:04 AM and from Lagos at 9:21 AM. The Lagos sign-in followed 11 MFA push prompts, one of which was approved.</p><p>Felicity confirmed by desk phone she did not travel and approved a prompt \"to make them stop.\" Her account can reach the claims clearinghouse.</p>",
      lesson: "Contain first: revoke sessions, rotate the password, re-register MFA, then hand off to Security. Billing accounts reach patient data, so the Privacy Officer will need to know. HIPAA 164.308(a)(6)(ii); NIST IR-4, AC-12." },
  },
  thu: {
    adminReq: { id: "REQ0027182", uid: "corinne.faulkner", group: "ROLE-EHR-BreakGlass",
      alt: "Break-glass is used per event when care can't wait, and every use is reviewed by the Privacy Officer. It's never a standing grant.",
      jordanNote: "Manager approved for rapid response coverage.",
      title: "Access request: standing break-glass for Corinne Faulkner", from: "Corinne Faulkner", channel: "Self-service portal",
      approval: "Keisha Holloway replied: \"Approved. She's on the rapid response team and can't wait on access during a code.\"",
      body: `<p>Requesting ${m("ROLE-EHR-BreakGlass")} permanently so I can open any patient's chart during rapid response calls.</p>`,
      lesson: "Emergency access is a procedure, not a role you hold. HIPAA 164.312(a)(2)(ii) (emergency access procedure); NIST AC-6." },
    loaReturn: { id: "REQ0027185", title: "Leave postponed: Siddharth Rao", from: "HR system (automated)", channel: "HR integration",
      body: "<p>Update to REQ0027144: Siddharth Rao's procedure has been moved to next month, so his leave is postponed and he is working today after all. Restore his access so he can work.</p>",
      lesson: "Because leave means disable-and-keep, a return is one click. If his groups were removed when his leave was processed, you're rebuilding access from the matrix now. NIST AC-2." },
  },
  conseq: {
    stale: { id: "INC0052403", title: n => "Dormant account signed in from unknown IP: " + n, from: "Identity protection alert", channel: "SIEM alert",
      body: n => `<p>${n}'s account had no sign-in for months. In the last half hour it signed in from a hosting-provider IP after a password spray, registered a new MFA method, and opened 37 patient charts.</p><p>This account was on the inactive-account sweep (TSK0009208).</p>`,
      prevented: "A few minutes ago, an attacker sprayed passwords at dormant accounts. Every attempt failed because you disabled them in the sweep (TSK0009208).",
      lesson: "A stale account is a door nobody is watching. Contain it, hand it to Security and the Privacy Officer (patient charts were opened), and fix the sweep. HIPAA 164.308(a)(6)(ii); NIST AC-2(3), IR-4." },
    svc: { id: "INC0052406", restores: "the EHR backups", title: "EHR backups failing since the account sweep", from: "Backup monitoring", channel: "Automated alert",
      body: `<p>The EHR database backup job has failed on every run since the account was switched off: ${m("Logon failure: account disabled (svc-ehr-backup)")}.</p><p>There is no restorable copy of the EHR from after the inactive-account sweep (TSK0009208).</p>`,
      prevented: "EHR backups kept running clean. You sent svc-ehr-backup to its owner instead of disabling it.",
      lesson: "Service accounts aren't people. Disabling one breaks production silently, and HIPAA requires retrievable exact copies of ePHI. Restore service, then let the owner decide. HIPAA 164.308(a)(7)(ii)(A); NIST CP-9." },
    leaver: { id: "INC0052409", title: "Terminated technician opened controlled-substance counts", from: "Pharmacy inventory audit report", channel: "Email",
      body: "<p>HR told Victor Halvorsen about his termination (REQ0027112) this morning. His session is still live: in the last half hour it signed in to the pharmacy inventory system from an off-site IP address and viewed the controlled-substance counts for the last 30 days.</p>",
      prevented: "Victor Halvorsen tried the pharmacy inventory system from his phone right after HR told him, and was blocked. Clean offboarding.",
      effect: "Victor Halvorsen viewed controlled-substance counts after his termination (INC0052409).",
      lesson: "Offboarding isn't done until the account is disabled, sessions are revoked and access is removed. Post-termination access is an incident for Security, and pharmacy will need to rule out diversion. HIPAA 164.308(a)(3)(ii)(C); NIST PS-4, IR-4." },
    recon: { id: "INC0052412", title: "Former nurse viewed 23 patient charts", from: "EHR privacy monitoring", channel: "SIEM alert",
      body: "<p>maya.estrada opened 23 patient charts in the last hour, including her neighbor's. HR shows she left Harbor Health on Sep 25. The account was flagged by HR reconciliation this morning (INC0052333).</p>",
      prevented: "Maya Estrada's old account tried to open the EHR a few minutes ago and was blocked.",
      effect: "A former nurse opened 23 patient charts after she left (INC0052412).",
      lesson: "Every day a former workforce member stays enabled is a day of exposure. This is now a likely HIPAA breach for the Privacy Officer to assess. HIPAA 164.308(a)(3)(ii)(C), 164.308(a)(6)(ii); NIST PS-4." },
    sodReq: { id: "INC0052415", title: "Pharmacist ordered and dispensed his own oxycodone order", from: "Pharmacy diversion analytics", channel: "SIEM alert",
      body: "<p>In the last hour, a verbal order for oxycodone 10 mg was entered and signed by quentin.ashworth and dispensed by the same account seven minutes later. No provider is linked to the order.</p>",
      prevented: "Every medication order this shift had two people: one to order, one to dispense.",
      effect: "A pharmacist ordered and dispensed a controlled substance with no second person involved (INC0052415).",
      lesson: "This is exactly what separation of duties prevents. Remove the conflicting access now and send it to Security as possible diversion. NIST AC-5; HIPAA 164.308(a)(4)." },
    copy: { id: "REQ0027188", title: "Re: New hire Ben Castellanos: billing access?", from: "Luis Arroyo (Revenue Cycle Manager)", channel: "Email",
      body: "<p>\"Ben Castellanos just started at registration and he's already opened patient account balances in billing. How does he have that? Fix it, and check whoever he was copied from.\"</p>",
      prevented: "Ben started with clean registration access. Tamara Lindsey's leftover billing access is still worth a review.",
      effect: "A new registration rep opened patient billing records with access copied from a peer (REQ0027188).",
      lesson: "Copying a peer copies their mistakes. Fix both people, and use the role matrix from now on. HIPAA minimum necessary; NIST AC-6." },
    priv: { id: "INC0052418", title: "EHR Security Admin created a hidden provider account", from: "EHR audit alert", channel: "SIEM alert",
      body: "<p>kyle.morrison used EHR Security Admin to create a provider account with access to every department's charts. Kyle says he didn't do it. His account signed in from a new device earlier this morning.</p>",
      prevented: "EHR security administration stayed with the two EHR analysts, under change control.",
      effect: "A standing EHR Security Admin grant was used to create a rogue provider account (INC0052418).",
      lesson: "Standing admin rights turn one phished technician into a breach of every chart. Remove the role, contain the account, and keep admin rights under change control. NIST AC-6(5); HIPAA 164.308(a)(4)." },
    exec: { id: "INC0052421", title: "$310,000 paid to a fake medical supplier", from: "Daniel Ferreira (Controller)", channel: "Phone",
      body: "<p>A $310,000 payment to a new medical supply vendor was approved from Renee Kowalski's account minutes after the MFA change on INC0052326. The real Renee has been in the office all morning and never called the desk. The attacker registered their own phone for MFA.</p>",
      prevented: "The real Renee Kowalski thanked the desk. The \"conference call\" came from a fraud crew targeting hospital finance teams this month.",
      effect: "An attacker impersonating the CFO got a $310,000 payment to a fake supplier approved (INC0052421).",
      lesson: "One skipped identity check paid for the attacker's quarter. Contain the account, remove their MFA method, and involve Security, Legal and the bank right away. HIPAA 164.312(d); NIST IA-5, IR-4." },
    contractor: { id: "INC0052424", title: "Re: Extend agency nurse: still locked out", from: "Keisha Holloway (sponsor)", channel: "Email",
      approval: "Keisha Holloway (sponsor) replied: \"Approved. Same 13-week assignment I sent this morning.\"",
      body: "<p>\"This didn't work. Tessa's account says it's expired and she can't chart, so we've pulled a nurse from step-down to cover the ICU. I sent this request first thing this morning!\"</p>",
      prevented: "Tessa Lindqvist's assignment rolled over without a gap.",
      lesson: "Missed requests have a patient-care cost too. Agency accounts need the end date, the sponsor approval and the extension handled together. NIST PS-7." },
    compromise: { id: "INC0052427", title: "Felicity Ward's mailbox sent 400 fake billing notices", from: "Email security", channel: "SIEM alert",
      body: "<p>In the last half hour, felicity.ward sent 400 emails with a fake \"pay your balance\" link to patients. The sign-ins came from the same Lagos infrastructure as this morning's alert (INC0052342).</p>",
      prevented: "Security traced the Lagos sign-in to a phishing kit and blocked it network-wide after your escalation.",
      lesson: "Half-contained is not contained. The attacker kept a session or token and came back. Do every step, then escalate. HIPAA 164.308(a)(6)(ii); NIST IR-4, AC-12." },
    callerPw: { id: "INC0052430", title: "\"I never asked for a password reset\"", from: "Monique Dubois", channel: "Phone (desk line)",
      body: "<p>\"I only just got to my desk after my vacation. Someone called in as me earlier, got my password reset, and has been in my email and the claims clearinghouse since. How did they get through?\"</p><p>There is no identity verification on record for the reset on INC0052311.</p>",
      prevented: "Monique Dubois confirmed the reset was her, and your verification is on record.",
      effect: "An unverified reset let an attacker into Monique Dubois' email and the claims clearinghouse (INC0052430).",
      lesson: "If verification isn't recorded, it didn't happen. That's true for auditors and for attackers. Contain, rotate, escalate. HIPAA 164.312(d); NIST IA-5." },
    review: { id: "REQ0027191", title: "Re: Q3 revocation not done", from: "Beatrice Njoroge (Privacy Officer)", channel: "Email",
      body: "<p>\"This was closed, but it didn't work. Follow-up testing shows Delphine Okafor still holds APP-Lab-Results, which the Q3 reviewer marked for revocation. This goes in the compliance report as an exception unless it's fixed and evidenced today.\"</p>",
      prevented: "The Privacy Officer closed the Q3 access review with no open revocations.",
      lesson: "An access review isn't finished when the manager clicks Revoke. It's finished when access is actually removed. HIPAA 164.308(a)(4)(ii)(C); NIST AC-2(j)." },
    mover: { id: "REQ0027194", title: "Re: Transfer: Leticia still has scheduling", from: "Carmen Velasquez (Patient Access Manager)", channel: "Email",
      body: "<p>\"This didn't work. Leticia moved to billing this morning, but she just rescheduled four of her old patients' appointments. Why does she still have scheduling?\"</p>",
      prevented: "Leticia's transfer was clean. Patient Access confirmed she has no scheduling access.",
      effect: "Leticia Moreno kept scheduling access after moving to billing and changed patients' appointments (REQ0027194).",
      lesson: "Movers keep old access unless someone removes it. This is how privilege creep builds. HIPAA 164.308(a)(4)(ii)(C); NIST PS-5." },
  },
  audit: { manager: { name: "Rashid Karimi", title: "IT Director" } },
  grc: {
    G,
    ctx: "HIPAA access control audit",
    intro: "You're Harbor Health's internal auditor, testing access controls for the annual HIPAA Security Rule evaluation.",
    levels: { title: "Incident or breach (HIPAA)", items: [
      ["Security incident", "an attempted or successful unauthorized access, use, disclosure, modification or destruction of information, or interference with system operations (45 CFR 164.304)."],
      ["Breach", "an access, use or disclosure of unsecured PHI that the Privacy Rule doesn't permit and that compromises it. It's presumed to be a breach unless a documented risk assessment shows a low probability that the PHI was compromised (45 CFR 164.402)."],
      ["Notification", "affected individuals are told without unreasonable delay and no later than 60 days after discovery (164.404). HHS is notified too, and the media when more than 500 residents of a state are affected."]],
      note: "Audit findings go to the Security Official and the compliance committee. Anything that may be a breach goes to the Privacy Officer at once." },
  },
});
