// AWS IAM lab guide: seed a free-tier account with a CloudFormation stack from CloudShell, work six
// Monday tickets in the IAM console, run a read-only check in CloudShell and grade it in the browser.
import { type ReactNode } from "react";
import { labSpec } from "../../lab/core";
import { AWS_PATH, AWS_STACK, gradeAwsExport, parseAwsExport } from "../../lab/aws";
import { Code, Ext, Mono, Scripts, Step, TicketList, type LabGuide } from "./shared";

const SCRIPTS = [
  ["rolevara-lab-aws.json", "The CloudFormation template: IAM users and groups with no permissions attached."],
  ["seed_rolevara_lab.py", "Checks the account, then creates the stack. Asks you to confirm the account first."],
  ["check_rolevara_lab.py", "Read-only. Writes rolevara-aws-export.json for grading."],
  ["remove_rolevara_lab.py", "Removes only the lab stack and what you added to its users and groups."],
] as const;

const TODO: Record<string, string> = {
  REQ0018841: "Give Maria Lopez console access (autogenerated password) and add her to exactly the AP Clerk groups.",
  REQ0018850: "Offboard Robert Hayes: disable console access, deactivate his access key, and remove him from every group.",
  REQ0018852: "Move Tanya Wright to Operations / Dispatcher: edit her Department and JobTitle tags, swap Sales groups for Dispatcher groups.",
  REQ0018870: "Rehire Sofia Ramirez as HR / HR Generalist: enable console access with a new password, update her tags, remove old access, add the new role's groups.",
  REQ0018879: "Put Rachel Adams on leave: disable console access and keep her groups.",
  REQ0018881: "Provision Ethan Moore as a Dispatcher from the access matrix: enable console access and add the Dispatcher groups, not Bob Turner's.",
};

function Setup() {
  return (
    <ol className="space-y-7">
      <Step n={1} title="Get a free-tier AWS account">
        <p>Use an account you created for practice. <b>Never run the scripts in an employer's account.</b> The seed script stops if an account has more than 50 IAM users. IAM, CloudFormation and CloudShell have no charge.</p>
        <p className="text-sm text-muted-foreground">See <Ext href="https://aws.amazon.com/free/">AWS Free Tier</Ext>.</p>
      </Step>
      <Step n={2} title="Sign in as an administrator">
        <p>Seeding and cleanup create and delete IAM users, groups and a CloudFormation stack. Use an administrator rather than the root user. The check only reads, so it also runs as a user or role with the AWS managed <Mono>ReadOnlyAccess</Mono> policy.</p>
        <p className="text-sm text-muted-foreground">See <Ext href="https://docs.aws.amazon.com/IAM/latest/UserGuide/root-user-best-practices.html">Root user best practices</Ext>.</p>
      </Step>
      <Step n={3} title="Open CloudShell">
        <p>Choose the CloudShell icon in the console's top bar. CloudShell runs with your console sign-in, so no access keys are created or stored. Use the same Region for every script; the stack lives there.</p>
        <p className="text-sm text-muted-foreground">See <Ext href="https://docs.aws.amazon.com/cloudshell/latest/userguide/welcome.html">What is AWS CloudShell?</Ext></p>
      </Step>
      <Step n={4} title="Download the files and upload them to CloudShell">
        <Scripts lab="aws" files={SCRIPTS} />
        <p>In CloudShell, choose <b>Actions &gt; Upload file</b> for each one. Read the scripts before you run them; each explains what it does at the top.</p>
      </Step>
    </ol>
  );
}

function Run() {
  const spec = labSpec();
  return (
    <ol className="space-y-7">
      <Step n={1} title="Seed the account">
        <p>The dry run checks the account and lists what would be created, without changing anything. The seed then asks you to type the account ID:</p>
        <Code>{"python3 seed_rolevara_lab.py --dry-run\npython3 seed_rolevara_lab.py"}</Code>
        <p>It creates the CloudFormation stack <Mono>{AWS_STACK}</Mono>: {spec.users.length} IAM users and {spec.groups.length} IAM groups under the path <Mono>{AWS_PATH}</Mono>, with no permissions attached, so the lab users can't do anything in the account.</p>
      </Step>
      <Step n={2} title="Work the six tickets in the IAM console">
        <p>Open <b>IAM &gt; Users</b> and <b>IAM &gt; User groups</b>. In IAM terms, an enabled account has <b>console access</b>, a leaver's sessions are revoked by <b>deactivating his access key</b>, and department and job title are the <Mono>Department</Mono> and <Mono>JobTitle</Mono> tags. The access matrix and runbook are on the <a href="#/policy" className="font-medium text-primary-strong underline underline-offset-2">Policy &amp; matrix</a> page.</p>
        <TicketList todo={TODO} />
      </Step>
      <Step n={3} title="Check the results">
        <p>The check makes only describe, list and get calls and writes <Mono>rolevara-aws-export.json</Mono>. Download it with <b>Actions &gt; Download file</b>, then open the <b>Upload results</b> tab:</p>
        <Code>{"python3 check_rolevara_lab.py"}</Code>
        <p>You can fix things in IAM and check again as often as you like.</p>
      </Step>
      <Step n={4} title="Clean up when you're done">
        <p>This removes what you added to the lab users (console passwords, keys, group memberships), then deletes the stack. It touches only users and groups under <Mono>{AWS_PATH}</Mono>.</p>
        <Code>{"python3 remove_rolevara_lab.py --dry-run\npython3 remove_rolevara_lab.py"}</Code>
      </Step>
    </ol>
  );
}

const TROUBLE: [string, ReactNode][] = [
  ["\"This account has N IAM users\"", <>The seed stops on accounts with more than 50 IAM users so it can't touch a real organization. If the account really is a lab, run it with <code className="font-mono">--lab-account</code>.</>],
  ["\"A stack named rolevara-lab already exists\"", <>A previous lab is still there. Run <code className="font-mono">python3 remove_rolevara_lab.py</code>, then seed again.</>],
  ["\"No 'rolevara-lab' stack in this account and Region\"", <>CloudShell is in a different Region from the one you seeded in. Switch Regions in the console's top bar and open CloudShell again.</>],
  ["\"AccessDenied\" or \"not authorized\"", <>Seeding and cleanup need permission to manage IAM and CloudFormation, such as <code className="font-mono">AdministratorAccess</code>. The check needs only <code className="font-mono">ReadOnlyAccess</code>. See <Ext href="https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html">AWS managed policies for job functions</Ext>.</>],
  ["Enabling console access fails on the password", <>Choose an autogenerated password. A custom one must meet the account's password policy.</>],
  ["Robert's access key still counts as active", <>Deactivating or deleting the key both count. Check that you changed the key on Robert Hayes, under <b>Security credentials</b>.</>],
  ["The check says a user \"was not found\"", <>The user was deleted. The runbook removes access instead, so that ticket scores 0. Remove the lab and seed it again to retry.</>],
  ["The stack didn't delete cleanly", <>Run <code className="font-mono">python3 remove_rolevara_lab.py</code> again. It retries and removes what is left.</>],
  ["The upload says the file isn't a lab export", <>Upload <code className="font-mono">rolevara-aws-export.json</code> from the check script. If you edited it, check again.</>],
];

const RESOURCES = [
  ["AWS Free Tier", "https://aws.amazon.com/free/", "A free account for practice."],
  ["AWS CloudShell", "https://docs.aws.amazon.com/cloudshell/latest/userguide/welcome.html", "A browser shell with your console credentials."],
  ["Manage IAM user console access", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_passwords_admin-change-user.html", "Enabling, resetting and disabling console passwords."],
  ["Manage access keys", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html", "Deactivating and deleting a user's keys."],
  ["Add and remove users in a group", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_groups_manage_add-remove-users.html", "Group membership in the IAM console."],
  ["Tag IAM users", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags_users.html", "Where department and job title live in this lab."],
  ["What is CloudFormation?", "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html", "How the lab is seeded and removed."],
] as const;

export const AWS: LabGuide = {
  id: "aws", name: "AWS IAM lab", vendor: "Amazon Web Services",
  sub: "Work six Pacific Crest Monday tickets in a free-tier AWS account, then grade a read-only check in your browser.",
  setup: Setup, run: Run, trouble: TROUBLE, resources: RESOURCES,
  upload: { file: "rolevara-aws-export.json", script: "check_rolevara_lab.py", grade: text => gradeAwsExport(parseAwsExport(text)) },
};
