// Brightpath SaaS's SOC 2 audit desk: access controls tested internally before the SOC 2 Type II
// auditors arrive. Criteria are cited by ID only (the text is copyrighted by the AICPA).
import { PROV_OPTS, TERM_OPTS, G4, rowKit } from "../../engine/grcKit.js";
import { ROLES, buildUsers } from "./company";

const { J, X, RR } = rowKit(ROLES);
// The directory as the review population: employees, contractors and service accounts.
const people = Object.values(buildUsers());
const contractors = people.filter(u => u.type === "Contractor").length;
const service = people.filter(u => u.type === "Service").length;
const staff = people.length - contractors - service;

export const G = [
 {id:"G1",ctrl:"APD-01",title:"Test new user provisioning",kind:"table",opts:PROV_OPTS,
  intro:"<p><b>APD-01:</b> Access for new employees is approved by the manager <i>before</i> provisioning and limited to the role's birthright groups (SOC 2 CC6.2, CC6.3).</p><p>Test the 15 sampled Q3 joiners. Compare approval date to provisioned date, and groups granted to the access matrix (Policy &amp; matrix tab). Pre-hire accounts are created disabled before the start date; that's normal.</p>",
  rows:[J("Alana Brightwater","Engineering|Software Engineer","Mon, Jul 6","Tamsin Okoro, Jul 1","Jul 2",null,0),
   J("Benedict Shaw","Sales|Account Executive","Mon, Jul 13","Dante Russo, Jul 8","Jul 9",null,0),
   J("Celeste Novak","Customer Success|Support Engineer","Mon, Jul 20","Priya Shankar, Jul 14","Jul 15",null,0),
   J("Dorian Webb","Engineering|Senior Software Engineer","Mon, Jul 20","None on file","Jul 16",null,1),
   J("Esme Calder","Product|Product Designer","Mon, Jul 27","Marisol Ibanez, Jul 21","Jul 22",null,0),
   J("Felix Arden","Sales|Sales Development Rep","Mon, Aug 3","Dante Russo, Jul 28","Jul 29",null,0),
   J("Greta Lund","Engineering|Software Engineer","Mon, Aug 3","Raul Dominguez, Jul 29","Jul 30",null,0),
   J("Hugo Barrett","Customer Success|Customer Success Manager","Mon, Aug 10","Priya Shankar, Aug 4","Aug 5",null,0),
   J("Ivy Sterling","Engineering|Software Engineer","Mon, Aug 17","Tamsin Okoro, Aug 13","Aug 11",null,2,"Provisioned Aug 11, approved Aug 13."),
   J("Jude Halvorsen","Marketing|Marketing Manager","Mon, Aug 24","Owen Fairclough, Aug 18","Aug 19",null,0),
   J("Kira Monteiro","Customer Success|Support Engineer","Mon, Aug 31","Priya Shankar, Aug 25","Aug 26",null,0),
   J("Lowell Pratt","Engineering|Software Engineer","Tue, Sep 8","Raul Dominguez, Sep 1","Sep 2",["APP-Prod-DB-Read"],3,"Production database read isn't a birthright group; it needs the Head of Security's approval and expires in 30 days."),
   J("Maeve Donovan","Sales|Account Executive","Mon, Sep 14","Dante Russo, Sep 9","Sep 10",null,0),
   J("Niall Forsythe","Engineering|Site Reliability Engineer","Mon, Sep 21","Raul Dominguez, Sep 15","Sep 16",null,0),
   J("Oona Fitzroy","Sales|Sales Development Rep","Mon, Sep 28","Dante Russo, Sep 24","Sep 23",null,2,"Provisioned Sep 23, approved Sep 24.")],
  lesson:"Test both halves of the control: approval before access, and access limited to the role. 4 of 15 failed (27%). In the Type II report, that would appear as exceptions under CC6.2 and CC6.3, which customers will read."},
 {id:"G2",ctrl:"APD-02",title:"Test timely terminations",kind:"table",opts:TERM_OPTS,
  intro:"<p><b>APD-02:</b> Accounts are disabled within <b>one business day</b> of the HR separation date (SOC 2 CC6.2, removing access when it's no longer authorized).</p><p>Test the 12 sampled Q3 separations from the Oct 2 directory extract. Weekends don't count as business days.</p>",
  rows:[X("Phoebe Langford","Software Engineer","Wed, Jul 8","Wed, Jul 8","Jul 7",0),
   X("Quincy Abbott","Account Executive","Fri, Jul 10","Mon, Jul 13","Jul 10",0,"Friday to Monday is one business day."),
   X("Romy Gallagher","Support Engineer","Thu, Jul 16","Thu, Jul 16","Jul 16",0),
   X("Sterling Hayes","Sales Development Rep","Tue, Jul 21","Tue, Jul 28","Jul 20",1,"Five business days late; no sign-in after separation."),
   X("Talia Brennan","Product Designer","Fri, Jul 31","Fri, Jul 31","Jul 30",0),
   X("Ulysses Kerr","Site Reliability Engineer","Mon, Aug 3","Fri, Aug 14","Aug 7",2,"Used a cloud console token on Aug 7, four days after separation."),
   X("Vivian Hale","Customer Success Manager","Fri, Aug 14","Wed, Aug 26","Aug 20",2,"Signed in to email and chat after separation."),
   X("Warren Blythe","Software Engineer","Fri, Aug 21","Mon, Aug 24","Aug 20",0,"Friday to Monday is one business day."),
   X("Xenia Rowe","Account Executive","Tue, Sep 1","Tue, Sep 1","Aug 31",0),
   X("Yusuf Ashby","Support Engineer","Thu, Sep 10","Thu, Sep 10","Sep 10",0),
   X("Sienna Park","Customer Success Manager","Wed, Sep 30","Not disabled","Oct 1",3,"Still enabled at extract and signing in. This is the same account from IAM Ops ticket INC0084333."),
   X("Zane Whitaker","Sales Development Rep","Thu, Oct 1","Fri, Oct 2","Oct 1",0,"Next business day is within policy.")],
  lesson:"Measure against the policy exactly: Friday to Monday passes. Keep \"late\" separate from \"late and used\". At a SaaS company, use after separation can mean customer data or production in the hands of someone who left."},
 {id:"G3",ctrl:"APD-02",title:"Evaluate the termination exceptions",kind:"quiz",
  intro:"<p>Your APD-02 test found 4 exceptions in 12 samples. Additional facts from follow-up:</p><ul><li>Sterling Hayes (SDR) kept CRM access for 5 extra business days. Logs show no activity after separation.</li><li>Ulysses Kerr used a still-valid cloud console token on Aug 7 to read a production storage bucket that holds customer exports.</li><li>Vivian Hale signed in to email and chat on Aug 20. She didn't open customer data.</li><li>Sienna Park's account is still active and signed in on Oct 1.</li></ul><p>Definitions are on the Controls tab.</p>",
  qs:[{q:"Is APD-02 operating effectively for Q3?",short:"Effectiveness conclusion",opts:["Yes: 8 of 12 passed","No: 4 of 12 (33%) failed, which is well above a tolerable rate for a per-event control"],correct:1,pts:2},
   {q:"Ulysses Kerr read customer exports after he left. What happens with that?",short:"Customer data accessed after separation",opts:["Document it in the finding only","Send it to Security now as a security incident. Security works out which customers' data was in the bucket and what their contracts require Brightpath to tell them.","Ask Ulysses to delete anything he downloaded, and close it if he agrees"],correct:1,pts:3},
   {q:"Vivian Hale signed in after she left but didn't open customer data. How do you treat it?",short:"Use without customer data",opts:["No issue, because no customer data was involved","Refer it to Security as a security incident, confirm the account is disabled, and include it in the finding","Wait for the next quarterly access review"],correct:1,pts:3}],
  lesson:"A failed termination control isn't only an audit exception. Customer data reached after someone leaves is an incident with contractual notice duties, and any use after separation goes to Security."},
 G4,
 {id:"G5",ctrl:"UAR-01",title:"Review the Q3 access review for completeness",kind:"quiz",
  intro:"<p><b>UAR-01:</b> Each quarter, managers certify <i>all</i> directory accounts (employees, contractors, service accounts). Revocations are completed within 5 business days (SOC 2 CC6.2, CC6.3).</p>",
  evidence:[["Directory extract, Sep 30",`${people.length} accounts: ${staff} employees, ${contractors} contractors, ${service} service accounts`],["Access review file",`${staff} accounts, all certified by managers`],["Reviewer sign-off","Kai Mahoe, Oct 1"],["Population source","CSV export provided by IT; no query or run parameters attached"]],
  qs:[{q:"What is the main issue?",short:"Issue identified",opts:[`Completeness: the ${contractors} contractors and ${service} service accounts were left out of the review`,"Timeliness: sign-off came after quarter end","Accuracy: managers certified too quickly","No issue"],correct:0,pts:3},
   {q:"What evidence do you request? Select all that apply.",multi:true,opts:["A system-generated population with the query, parameters and run date",`Review evidence for the ${contractors + service} excluded accounts`,"A Slack message from IT confirming the review was complete","Re-perform the whole review yourself"],correct:[0,1]},
   {q:"Until those accounts are reviewed, can UAR-01 be relied on to catch the access APD-02 missed?",short:"Reliance on UAR-01",opts:["Yes","No"],correct:1,pts:2}],
  lesson:"Before testing a review, test the population. SOC 2 auditors ask exactly this: how do you know the list was complete? Service accounts with production access are the usual gap."},
 {id:"G6",ctrl:"RISK",title:"Rate the security risk register",kind:"table",opts:["High","Medium","Low"],
  intro:"<p>SOC 2 CC3.2 expects the company to identify and analyze risks to its objectives. Rate each risk's inherent level. Score = likelihood × impact. <b>High</b> 15–25, <b>Medium</b> 8–14, <b>Low</b> 1–7.</p><p class=\"mono\" style=\"font-size:12px\">Likelihood: Rare 1 · Unlikely 2 · Possible 3 · Likely 4 · Almost certain 5<br>Impact: Minimal 1 · Minor 2 · Moderate 3 · Major 4 · Severe 5</p>",
  rows:[RR("R-01 Former employees keep production or customer access","APD-02 failures; 3 accounts used after separation","Likely","Severe",0),
   RR("R-02 Shared demo environment login","Requested by Sales","Possible","Minor",2),
   RR("R-03 Self-approved production changes","An engineer holds review approval and deploy","Possible","Severe",0),
   RR("R-04 Email vendor SOC 2 coverage gap","Report ends Jun 30","Unlikely","Moderate",2),
   RR("R-05 MFA fatigue attacks","One successful push approval this week","Likely","Moderate",1)],
  lesson:"Apply the matrix the same way every time. R-02 feels risky, but a demo environment with no customer data scores 6. R-01 (20) and R-03 (15) lead the remediation plan."},
 {id:"G7",ctrl:"VEN-01",title:"Review a subprocessor's SOC 2 report",kind:"quiz",
  intro:"<p>Postwell Email Delivery sends Brightpath's appointment reminders, so it receives customers' end users' names, emails and appointment times. It's listed as a subprocessor in customer contracts. Brightpath's own audit period ends Dec 31.</p>",
  evidence:[["Report","SOC 2 Type II, Security and Confidentiality"],["Period","Oct 1, 2025 to Jun 30, 2026"],["Opinion","Unqualified"],["Exception","CC6.2: 2 of 25 sampled terminated users were removed late. Management response: automated deprovisioning implemented Jul 2026."],["Subservice org","A public cloud provider (carve-out method)"],["Complementary user entity controls","1) Customers remove their users from the Postwell console within 1 business day. 2) Customers rotate their API keys at least yearly."],["Data processing agreement","Signed 2022. Covers email delivery only; Brightpath started sending SMS through Postwell in 2026."]],
  qs:[{q:"Which follow-ups are needed? Select all that apply.",multi:true,opts:["Get a bridge letter covering Jul 1 to Dec 31","Evaluate whether the CC6.2 exception affects our reliance","Confirm our own user entity controls (console user removal, API key rotation) are operating","Get and review the cloud provider's SOC report for the carved-out subservice","Update the data processing agreement to cover SMS","Drop the vendor because the report has an exception","No action needed; the opinion is unqualified"],correct:[0,1,2,3,4]},
   {q:"Why does your APD-02 result matter for this review?",short:"Link to APD-02",opts:["It doesn't; it's a different system","Postwell relies on us to remove our users from its console on time. Our late terminations mean that user entity control is failing.","It means Postwell's opinion should be qualified"],correct:1,pts:3}],
  lesson:"A clean SOC 2 opinion isn't the end of the review. Cover the gap period, weigh the exceptions, check the carved-out subservice provider, confirm your side of the user entity controls, and make sure the agreement covers what the vendor actually does."},
 {id:"G8",ctrl:"POL-EX",title:"Decide a policy exception request",kind:"quiz",
  intro:"<p>After IAM Ops rejected the shared <span class=\"mono\">sales-demo</span> login, Sales filed a formal policy exception: \"New SDRs wait days for demo accounts. SSO for the demo environment is on the Q2 2027 roadmap.\"</p>",
  qs:[{q:"What is the decision?",short:"Exception decision",opts:["Deny outright; policy is policy","Approve as asked: one shared login for the demo environment, with access to the production admin console for setup","Approve temporarily for the demo environment only, holding no customer data, with compensating controls and risk owner sign-off"],correct:2,pts:3},
   {q:"Which conditions belong in the approval? Select all that apply.",multi:true,opts:["The demo environment holds only synthetic data, never customer data","Expiry of 90 days or less, with re-review","Password kept in the secrets manager and rotated whenever an SDR leaves","Sign-off by the risk owner (Dante Russo, Sales Director)","Tracked project to put the demo environment behind SSO","Let the shared login reach production, to save setup time","Post the password in the #sales channel"],correct:[0,1,2,3,4]}],
  lesson:"GRC's job is managed risk, not saying no. A shared login can be acceptable where there's nothing to protect and nobody to trace. Keep it narrow, time-limited, compensated and owned by the business."},
 {id:"G9",ctrl:"MAP",title:"Map APD-02 to frameworks",kind:"quiz",
  intro:"<p>Map APD-02 (disable accounts within one business day of separation) so one test can answer several reviews.</p>",
  qs:[{q:"Select every requirement APD-02 supports.",multi:true,opts:["SOC 2 CC6.2 (removing access when no longer authorized)","SOC 2 CC6.3 (role-based access and removal)","NIST 800-53 PS-4 Personnel Termination","NIST 800-53 AC-2 Account Management","ISO 27001:2022 A.5.18 Access rights","SOC 2 A1.2 (backups and recovery)","SOC 2 CC8.1 (change management)","NIST 800-53 CP-9 System Backup","ISO 27001:2022 A.8.13 Information backup"],correct:[0,1,2,3,4]}],
  lesson:"Test once, satisfy many. A mapped control lets one set of APD-02 evidence answer the SOC 2 auditors, an ISO 27001 audit and every customer security questionnaire."},
 {id:"G10",ctrl:"APD-02",title:"Write the termination finding",kind:"quiz",
  intro:"<p>Build the APD-02 finding. Pick the strongest statement for each element.</p>",
  qs:[{q:"Condition",short:"Condition",opts:["Access was removed late for some staff.","4 of 12 sampled separations (33%) were not disabled within one business day. One account was still active at extract, and three former employees used their access after leaving, one to read customer exports.","IT doesn't take separations seriously."],correct:1,pts:2},
   {q:"Criteria",short:"Criteria",opts:["The Access Control policy requires accounts to be disabled within one business day of the HR separation date (control APD-02), which Brightpath describes to customers under SOC 2 CC6.2.","Best practice says access should be removed quickly.","SOC 2 requires same-day removal."],correct:0,pts:2},
   {q:"Cause",short:"Cause",opts:["The service desk was careless.","Unknown.","Separations are processed by hand from HRIS emails. There is no automated HRIS-to-IdP trigger, and cloud console tokens aren't revoked when the IdP account is disabled."],correct:2,pts:2},
   {q:"Effect",short:"Effect",opts:["Brightpath will lose every customer.","Former employees could reach production and customer data after leaving, and one did (customer exports, now under incident review). The Type II report would show exceptions customers will ask about.","No impact, because nothing was leaked."],correct:1,pts:2},
   {q:"Recommendation",short:"Recommendation",opts:["Automate deprovisioning from the HRIS separation event, revoke cloud tokens with the IdP account, and add a daily HRIS-to-IdP reconciliation with exceptions reviewed by Security.","Remind the service desk to be faster.","Remove all users' access every quarter."],correct:0,pts:2}],
  lesson:"A finding that holds up is specific (numbers), cites the actual requirement, names a fixable cause, states real impact without exaggeration, and recommends a fix that addresses the cause."}
];
