// Brightpath SaaS's week on the service desk. The kit (lib/ticketKit.js) supplies grading, hints,
// the playbook and Jordan Reyes' week; this file is the story. Lessons cite the SOC 2 Trust
// Services Criteria by ID only (the criteria text is copyrighted by the AICPA).
import { buildTicketSet } from "../lib/ticketKit.js";
import { ROLES, SOD, buildUsers } from "./company";
import { G } from "./grc.js";

const m = x => `<span class="mono">${x}</span>`;

export const set = buildTicketSet({
  id: "brightpath", ROLES, SOD, buildUsers,
  mon: {
    joiner: { id: "REQ0051104", uid: "mateo.silva", rk: "Sales|Sales Development Rep", title: "New hire: Mateo Silva, Sales Development Rep",
      from: "HRIS (automated)", channel: "HR integration", opened: "7:02 AM",
      body: "<p>New hire starting today in Sales. The pre-hire account was created by the HRIS sync but is disabled with no access.</p><p>Please activate the account and provision access for the role. Onboarding starts at 9:30 AM.</p>",
      lesson: "Provision from the role in the access matrix, nothing more, and only from an HR record. SOC 2 CC6.2 (registering and authorizing new users)." },
    callerPw: { id: "INC0084311", uid: "cosima.hartley", title: "Forgot password after vacation",
      from: "Cosima Hartley", channel: "Video call", opened: "7:44 AM",
      body: "<p>\"Hey, I just got back from two weeks off and my password expired while I was out. I tried a new one and now I can't remember which. Can you reset it? I've got a renewal call at 9.\"</p>",
      lesson: "Verify identity against the system of record before any credential reset. SOC 2 CC6.1 (logical access security)." },
    callerLock: { id: "INC0084314", uid: "percy.underhill", title: "Locked out before support shift",
      from: "Percy Underhill", channel: "Chat (personal phone)", opened: "7:53 AM",
      body: "<p>\"Fat-fingered my password a bunch of times on the new keyboard and now SSO says I'm locked. I know my password. The support queue opens at 8.\"</p>",
      lesson: "A lockout is not a forgotten password. Unlock only after verifying who's asking; a reset adds risk for no reason." },
    callerMfa: { id: "INC0084318", uid: "juniper.ashworth", title: "Phone stolen, can't approve sign-ins",
      from: "Juniper Ashworth", channel: "Video call", opened: "8:02 AM",
      body: "<p>\"My phone was stolen on the train Friday. The authenticator was on it. I've got a new phone, but I can't sign in and I'm running sprint planning at 10.\"</p>",
      lesson: "Clear the stolen authenticator and end any sessions the phone may still hold. SOC 2 CC6.1." },
    leaver: { id: "REQ0051112", uid: "hana.kobayashi", title: "Termination: Hana Kobayashi, effective 11:00 AM",
      from: "Freya Nilsen (People Operations)", channel: "HR integration", opened: "8:07 AM",
      body: "<p>Involuntary termination effective today at 11:00 AM. Hana holds production admin access. Remove all access per the leaver policy before she is told.</p>",
      lesson: "Leavers: disable, revoke sessions and tokens, remove all access, before a production admin is told. SOC 2 CC6.2 (removing access when no longer authorized)." },
    mover: { id: "REQ0051115", uid: "theo.vandenberg", fromRk: "Customer Success|Support Engineer", toRk: "Engineering|Software Engineer",
      title: "Transfer: Theo Vandenberg, Support to Engineering", from: "HRIS (automated)", channel: "HR integration", opened: "8:15 AM",
      body: "<p>Theo Vandenberg is moving from Support Engineer to Software Engineer, effective today. New manager: Tamsin Okoro. Update his job info and access.</p>",
      lesson: "Movers are where privilege creep starts. Remove the old role's access, not just add the new. An engineer who can still impersonate customers has customer data nobody reviews. SOC 2 CC6.3." },
    sodReq: { id: "REQ0051119", uid: "leander.voss", group: "APP-CI-CD-Deploy-Prod", holds: "APP-Code-Review-Approve",
      title: "Access request: production deploy for Leander Voss", from: "Leander Voss", channel: "Self-service portal", opened: "8:23 AM",
      approval: "Tamsin Okoro replied: \"Approved. He shouldn't have to wait on SRE for Friday hotfixes.\"",
      alt: "suggest hotfixes go through the pipeline with an SRE or a second engineer approving, so no one ships a change they reviewed themselves.",
      body: `<p>Requesting ${m("APP-CI-CD-Deploy-Prod")} so I can ship small hotfixes myself instead of waiting for an SRE.</p>`,
      lesson: "Manager approval doesn't override separation of duties. The person who approves a code change must never be the one who deploys it alone. SOC 2 CC8.1 (change management), CC6.3." },
    request: { id: "REQ0051123", uid: "priya.shankar", group: "APP-Finance-Reports", approver: "Elena",
      title: "Access request: finance reports", from: "Priya Shankar", channel: "Self-service portal", opened: "8:28 AM",
      approval: "Elena Marchetti replied: \"Approved. Priya owns the churn numbers for the board deck.\"",
      body: `<p>Requesting ${m("APP-Finance-Reports")} to pull net revenue retention and churn by customer for the quarterly board deck.</p>`,
      lesson: "Requestable access needs a documented approval before it's granted, and only what was asked. SOC 2 CC6.2, CC6.3." },
    exec: { id: "INC0084326", uid: "hollis.grant", saidEmpId: "BP-0050", title: "URGENT: CFO locked out before a wire",
      from: "Caller says: Hollis Grant (CFO)", channel: "Phone (unknown mobile number)", opened: "8:35 AM",
      body: "<p>\"This is Hollis Grant. I'm at the investor meeting in New York and my phone died. I'm on a borrowed one. Move my MFA to this number now. If the deposit for the office lease isn't wired by 9, we lose the space.\"</p>",
      lesson: "Urgency plus authority plus a new device is the classic social-engineering pattern. Check the details, refuse, and report it. SOC 2 CC6.1, CC7.3." },
    contractor: { id: "REQ0051127", uid: "lukas.brenner", title: "Extend contractor: Lukas Brenner",
      from: "Tamsin Okoro (sponsor)", channel: "Email", opened: "8:41 AM",
      approval: "Tamsin Okoro (sponsor) replied: \"Approved. His contract was renewed through the mobile app launch.\"",
      body: "<p>Lukas's contract was renewed for the mobile app work. His account expires in 2 days. Please extend it.</p>",
      lesson: "Contractor accounts always have an end date and a sponsor approval, capped at 90 days per extension. SOC 2 CC6.2." },
    sweep: { id: "TSK0015208", dormant: [["chris.albrecht", 131], ["lorenzo.gatti", 95]], under: ["philippa.grange", 89], svc: "svc-db-backup",
      title: "Weekly: disable inactive accounts", from: "Scheduled report", channel: "Automated task", opened: "8:48 AM",
      body: "<p>Weekly inactive-account sweep. Per policy, disable any user account with no sign-in for more than 90 days. Pre-hire accounts are excluded.</p><p>Use the Directory's sort by last sign-in.</p>",
      lesson: "Dormant accounts are a favorite target. Apply the threshold exactly, and send service accounts to their owner instead of breaking a production job. SOC 2 CC6.2." },
    recon: { id: "INC0084333", uid: "sienna.park", left: "Sep 30", signedIn: "yesterday",
      title: "HR reconciliation: former CSM still active", from: "HRIS-to-directory reconciliation report", channel: "Automated report", opened: "8:56 AM",
      body: "<p>The weekly HR reconciliation found an account that is still enabled for a person HR shows as separated. Check the HR feed and the account's last sign-in.</p>",
      lesson: "A former employee who can still reach customer data is a security incident. Contain it, then report it. SOC 2 CC6.2, CC7.3." },
    priv: { id: "REQ0051131", uid: "callum.ridley", group: "ROLE-IdP-Admin",
      route: "point Callum to Kai Mahoe: identity provider admin is held only by the IT administrators, through just-in-time elevation with a ticket reference.",
      title: "Need IdP Admin to set up SSO", from: "Callum Ridley (IT Support)", channel: "Chat message", opened: "9:04 AM",
      body: "<p>\"Can you add me to IdP Admin for the day? Marketing's new webinar tool needs SSO set up and Kai is slammed. Kai said it's fine.\"</p>",
      lesson: "Identity provider admin is never granted by ticket. It can create any account and grant any app. SOC 2 CC6.1, CC6.3." },
    rehire: { id: "REQ0051134", uid: "gideon.mensah", rk: "Customer Success|Support Engineer", pwAge: "11-month",
      title: "Rehire: Gideon Mensah, Support Engineer", from: "HRIS (automated)", channel: "HR integration", opened: "9:09 AM",
      body: "<p>Rehire starting today. The HRIS sync matched his existing disabled account. Reactivate and provision for the role.</p>",
      lesson: "Rehires carry old access and old passwords. Check access against the role, and issue a fresh credential. SOC 2 CC6.2." },
    shared: { id: "REQ0051138", uid: "dante.russo",
      alt: "offer each rep their own demo-environment account through SSO, set up from the role.",
      title: "Shared login for the demo environment", from: "Dante Russo (Sales Director)", channel: "Email", opened: "9:15 AM",
      body: `<p>"Can we get one login like ${m("sales-demo")} for the demo environment? The SDRs keep waiting on accounts and I just want them demoing."</p>`,
      lesson: "Shared accounts destroy accountability: nobody can say who changed what. Every person gets a unique ID. SOC 2 CC6.1." },
    review: { id: "REQ0051141", uid: "ottilie.marsh", group: "APP-Prod-DB-Read",
      title: "Access review action: remove production database read", from: "Monthly customer-data review (Raul Dominguez)", channel: "Access review", opened: "9:20 AM",
      body: "<p>Monthly customer-data access review result: reviewer Raul Dominguez marked <b>Ottilie Marsh: APP-Prod-DB-Read</b> as <b>Revoke</b> (\"Migration debugging finished in August\"). All other entitlements certified.</p>",
      lesson: "A review only counts if the revocations are carried out and evidenced. Remove exactly what the reviewer marked. SOC 2 CC6.2, CC6.3." },
    loa: { id: "REQ0051144", uid: "amelia.stroud", title: "Leave of absence: Amelia Stroud",
      from: "HRIS (automated)", channel: "HR integration", opened: "9:25 AM",
      body: "<p>Amelia Stroud begins leave today. Expected return Jan 18, 2027. Apply the leave of absence policy.</p>",
      lesson: "Leave is not termination. Disable to block use, but keep entitlements so she returns on day one." },
    copy: { id: "REQ0051147", uid: "ayanna.brooks", peer: "seraphina.holt", rk: "Engineering|Software Engineer", extras: ["APP-CI-CD-Deploy-Prod", "APP-Support-Desk"],
      title: "New hire Ayanna Brooks: \"same as Seraphina\"", from: "Tamsin Okoro (Engineering Manager)", channel: "Email", opened: "9:32 AM",
      body: "<p>\"Ayanna starts on my team today. Just give her whatever Seraphina Holt has so Seraphina can onboard her. Thanks!\"</p>",
      lesson: "Never mirror a peer. Peers carry leftover access, and copying spreads it. Provision from the role, and flag the peer's extras for review. SOC 2 CC6.3." },
    auditQ: { id: "REQ0051150", groups: ["ROLE-Cloud-Prod-Admin", "ROLE-SIEM-Admin"],
      title: "SOC 2 auditor request: production and SIEM admins", from: "Adrienne Cole (Head of Security)", channel: "Email", opened: "9:39 AM",
      body: "<p>\"The SOC 2 auditors want a list of every <b>enabled</b> user who currently holds <b>both</b> ROLE-Cloud-Prod-Admin and ROLE-SIEM-Admin.\"</p><p>Enter usernames (first.last) separated by commas, or <b>none</b>, in the answer box when you close the ticket.</p>",
      lesson: "Audit evidence must be complete and accurate. Pull it from the system, not from memory. Remediation is a separate, approved change." },
    compromise: { id: "INC0084342", uid: "evander.pike", title: "Impossible travel + MFA fatigue: Evander Pike",
      from: "Identity protection alert", channel: "SIEM alert", opened: "9:47 AM",
      body: "<p>High-risk sign-in. Evander Pike signed in from Denver at 9:05 AM and from Jakarta at 9:22 AM. The Jakarta sign-in followed 13 MFA push prompts, one of which was approved.</p><p>Evander confirmed on a video call he did not travel and approved a prompt \"to make them stop.\" His account can impersonate customer users.</p>",
      lesson: "Contain first: revoke sessions and tokens, rotate the password, re-register MFA, then hand off to Security, who decides whether customers must be told. SOC 2 CC7.3, CC7.4." },
  },
  thu: {
    adminReq: { id: "REQ0051182", uid: "tamsin.okoro", group: "ROLE-Cloud-Prod-Admin",
      alt: "During an incident, production admin comes through just-in-time elevation with a ticket reference. It's never a standing grant, and it isn't part of the Engineering Manager role.",
      jordanNote: "CTO approved for incident coverage.",
      title: "Access request: standing production admin for Tamsin Okoro", from: "Tamsin Okoro", channel: "Self-service portal", opened: "7:43 AM",
      approval: "Tunde Bakare replied: \"Approved. She's incident commander this month and can't wait on elevation during an outage.\"",
      body: `<p>Requesting ${m("ROLE-Cloud-Prod-Admin")} permanently so I can act fast as incident commander.</p>`,
      lesson: "Admin roles aren't requestable, whoever approves. Emergency access is a procedure with a record, not a role you keep. SOC 2 CC6.1, CC6.3." },
    loaReturn: { id: "REQ0051185", title: "Early return from leave: Amelia Stroud", from: "HRIS (automated)", channel: "HR integration", opened: "8:00 AM",
      body: "<p>Amelia Stroud has decided to return early and is back today. Restore her access so she can work.</p>",
      lesson: "Because leave means disable-and-keep, a return is one click. If her groups were removed Monday, you're rebuilding access from the matrix now." },
  },
  conseq: {
    stale: { id: "INC0084403", title: n => "Dormant account signed in from unknown IP: " + n, from: "Identity protection alert", channel: "SIEM alert", opened: "2:16 AM",
      body: n => `<p>${n}'s account had no sign-in for months. At 2:16 AM it signed in from a hosting-provider IP after a password spray, registered a new MFA method, and exported the CRM's customer contact list.</p><p>This account was on Monday's inactive-account report.</p>`,
      prevented: "Overnight, an attacker sprayed passwords at dormant accounts. Every attempt failed because you disabled them Monday.",
      lesson: "A stale account is a door nobody is watching. Contain it and hand it to Security, who will decide on customer notice. SOC 2 CC6.2, CC7.3." },
    svc: { id: "INC0084406", restores: "the database backups", title: "Nightly database backups failing since Monday", from: "Backup monitoring", channel: "Automated alert", opened: "6:05 AM",
      body: `<p>The production database backup job has failed three nights in a row: ${m("Authentication failed: account disabled (svc-db-backup)")}.</p><p>There is no restorable copy of customer data since Sunday, and the SOC 2 availability commitment is at risk.</p>`,
      prevented: "Nightly database backups ran clean all week. You sent svc-db-backup to its owner instead of disabling it.",
      lesson: "Service accounts aren't people. Disabling one breaks production silently. Restore service, then let the owner decide. SOC 2 A1.2 (backups and recovery)." },
    leaver: { id: "INC0084409", title: "Terminated SRE used a live session in production", from: "Cloud audit log alert", channel: "SIEM alert", opened: "7:21 AM",
      body: "<p>Hana Kobayashi, terminated Monday at 11:00 AM, used a still-valid cloud console session Tuesday at 10:50 PM to list the production storage buckets and download a database snapshot.</p>",
      prevented: "Hana Kobayashi's sessions were dead by Monday lunchtime. Her attempt to reach the cloud console Tuesday was blocked.",
      effect: "Hana Kobayashi downloaded a production database snapshot the night after her termination (INC0084409).",
      lesson: "Offboarding isn't done until the account is disabled, sessions and tokens are revoked and access is removed. Post-termination access to customer data is a security incident. SOC 2 CC6.2, CC7.3." },
    recon: { id: "INC0084412", title: "Former CSM exported customer accounts", from: "CRM activity monitoring", channel: "SIEM alert", opened: "7:48 AM",
      body: "<p>sienna.park exported 340 customer accounts with renewal dates and contract values from the CRM Wednesday night. HR shows she left Brightpath on Sep 30 to join a competitor.</p>",
      prevented: "Sienna Park's old account tried the CRM Tuesday and was blocked.",
      effect: "A former customer success manager exported 340 customer accounts after she left (INC0084412).",
      lesson: "Every day a former employee stays enabled is a day of exposure. Contain it and report it. SOC 2 CC6.2, CC7.3." },
    sodReq: { id: "INC0084415", title: "Engineer approved and deployed his own change", from: "Deploy pipeline audit", channel: "SIEM alert", opened: "8:05 AM",
      body: "<p>A change to the billing service was written, approved and deployed to production by leander.voss Tuesday at 6:40 PM. It turned off invoice rounding checks. No second person reviewed it.</p>",
      prevented: "Every production change this week had a second reviewer before deploy.",
      effect: "An engineer approved and deployed his own change to the billing service with no second reviewer (INC0084415).",
      lesson: "This is exactly what separation of duties prevents. Remove the conflicting access now and send it to Security to review the change. SOC 2 CC8.1." },
    copy: { id: "REQ0051188", title: "Why can a new engineer deploy to production?", from: "Raul Dominguez (Engineering Manager)", channel: "Email", opened: "8:13 AM",
      body: "<p>\"Ayanna Brooks started Monday and shows up in the production deploy group and the support desk. New engineers don't deploy for 90 days. How does she have that? Fix it, and check whoever she was copied from.\"</p>",
      prevented: "Ayanna started with clean software engineer access. Seraphina Holt's leftover access is still worth a review.",
      effect: "A new engineer got production deploy access copied from a peer (REQ0051188).",
      lesson: "Copying a peer copies their mistakes. Fix both people, and use the role matrix from now on. SOC 2 CC6.3." },
    priv: { id: "INC0084418", title: "IdP Admin created a hidden admin account", from: "Identity provider audit alert", channel: "SIEM alert", opened: "8:24 AM",
      body: "<p>callum.ridley used IdP Admin to create an account named <span class=\"mono\">sso-test2</span> and assign it to the cloud console with admin rights. Callum says he didn't do it. His account signed in from a new device Tuesday.</p>",
      prevented: "Identity provider admin stayed with the IT administrators, through just-in-time elevation.",
      effect: "A standing IdP Admin grant was used to create a hidden admin account (INC0084418).",
      lesson: "Standing admin rights turn one phished account into control of every app. Remove the role, contain the account, and keep admin rights just-in-time. SOC 2 CC6.1, CC6.3." },
    exec: { id: "INC0084421", title: "$260,000 wired to a fake landlord", from: "Yolanda Reyes (Controller)", channel: "Phone", opened: "8:32 AM",
      body: "<p>A $260,000 wire for a lease deposit was approved from Hollis Grant's account Monday at 9:05 AM. The real Hollis was in the office all day and never called the desk. The attacker registered their own phone for MFA.</p>",
      prevented: "The real Hollis Grant thanked the desk. The \"investor meeting\" call came from a fraud crew targeting startup finance teams this month.",
      effect: "An attacker impersonating the CFO got a $260,000 wire approved (INC0084421).",
      lesson: "One skipped identity check paid for the attacker's quarter. Contain the account, remove their MFA method, and involve Security, Legal and the bank right away. SOC 2 CC6.1, CC7.4." },
    contractor: { id: "INC0084424", title: "Contractor locked out; launch work stalled", from: "Tamsin Okoro (sponsor)", channel: "Chat message", opened: "8:45 AM",
      approval: "Tamsin Okoro (sponsor) replied: \"Approved. Same renewal I sent Monday.\"",
      body: "<p>\"Lukas's account expired Wednesday and he couldn't push the release branch. The launch is next week. I asked for this Monday!\"</p>",
      prevented: "Lukas Brenner's contract rolled over without a gap.",
      lesson: "Missed requests have a cost too. Contractor accounts need the end date, the sponsor approval and the extension handled together. SOC 2 CC6.2." },
    compromise: { id: "INC0084427", title: "Evander Pike's account impersonated 12 customers", from: "Support audit log", channel: "SIEM alert", opened: "9:01 AM",
      body: "<p>evander.pike opened impersonation sessions into 12 customer accounts overnight and downloaded their staff schedules. The sign-ins came from the same Jakarta infrastructure as Monday's alert.</p>",
      prevented: "Security traced the Jakarta sign-in to a phishing kit and blocked it network-wide after your escalation.",
      lesson: "Half-contained is not contained. The attacker kept a session or token and came back into customer data. Do every step, then escalate. SOC 2 CC7.3, CC7.4." },
    callerPw: { id: "INC0084430", title: "\"I never asked for a password reset\"", from: "Cosima Hartley", channel: "Video call", opened: "9:13 AM",
      body: "<p>\"I was still on vacation Monday morning. Someone got my password reset and has been in my email and the CRM since. How did they get through?\"</p><p>There is no identity verification on record for Monday's reset.</p>",
      prevented: "Cosima Hartley confirmed the reset was her, and your verification is on record.",
      effect: "An unverified reset let an attacker into Cosima Hartley's email and the CRM (INC0084430).",
      lesson: "If verification isn't recorded, it didn't happen. That's true for auditors and for attackers. Contain, rotate, escalate. SOC 2 CC6.1." },
    review: { id: "REQ0051191", title: "SOC 2 testing: customer-data revocation still open", from: "Adrienne Cole (Head of Security)", channel: "Email", opened: "9:23 AM",
      body: "<p>\"The auditors' follow-up testing shows Ottilie Marsh still holds APP-Prod-DB-Read, which the monthly reviewer marked for revocation. That's a SOC 2 exception unless it's fixed and evidenced today.\"</p>",
      prevented: "The monthly customer-data review closed with no open revocations.",
      lesson: "An access review isn't finished when the manager clicks Revoke. It's finished when access is actually removed. SOC 2 CC6.2." },
    mover: { id: "REQ0051194", title: "Transferred engineer still impersonating customers", from: "Priya Shankar (Support Manager)", channel: "Email", opened: "9:34 AM",
      body: "<p>\"Theo moved to engineering Monday, but he opened two customer impersonation sessions yesterday with no support ticket. Why does he still have the impersonation tool?\"</p>",
      prevented: "Theo's transfer was clean. Support confirmed he has no impersonation access.",
      effect: "Theo Vandenberg kept customer impersonation after moving to engineering and used it with no ticket (REQ0051194).",
      lesson: "Movers keep old access unless someone removes it. Customer-data access never carries over between teams. SOC 2 CC6.3." },
  },
  audit: { manager: { name: "Kai Mahoe", title: "IT Administrator" } },
  grc: {
    G,
    ctx: "SOC 2 Type II audit",
    intro: "You're Brightpath's GRC analyst, getting access controls ready for the SOC 2 Type II examination period.",
    levels: { title: "Event, incident or breach (SOC 2)", items: [
      ["Security event", "anything that could affect the system's security, such as a failed sign-in or an alert. Most are triaged and closed."],
      ["Security incident", "an event that actually compromises, or is reasonably likely to compromise, the security of the system or its data. The incident response plan applies (SOC 2 CC7.3, CC7.4)."],
      ["Customer notice", "when an incident affects a customer's data, Brightpath tells the customer within the time its contract sets, and the customer decides on any notice to its own people under the laws that apply to it."]],
      note: "Audit findings go to the Head of Security. Anything that may involve customer data goes to Security at once." },
  },
});
