// Sunset Retail Group's PCI DSS audit desk: access controls tested by internal audit before the
// annual PCI DSS assessment. PCI DSS v4.0.1 is cited by requirement number only (the standard is
// copyrighted by the PCI SSC). Sunset's termination standard is same-day, per Req. 8.2.5.
import { PROV_OPTS, TERM_OPTS, G4, rowKit } from "../../engine/grcKit.js";
import { ROLES, buildUsers } from "./company";

const { J, X, RR } = rowKit(ROLES);
// The directory as the review population: employees, seasonal staff and service accounts.
const people = Object.values(buildUsers());
const seasonal = people.filter(u => u.type === "Contractor" || u.title === "Seasonal Associate").length;
const service = people.filter(u => u.type === "Service").length;
const staff = people.length - seasonal - service;

export const G = [
 {id:"G1",ctrl:"APD-01",title:"Test new user provisioning",kind:"table",opts:PROV_OPTS,
  intro:"<p><b>APD-01:</b> Access for new employees is approved by the manager <i>before</i> provisioning and limited to the role's birthright groups (PCI DSS Req. 7.2.2, 8.2.4).</p><p>Test the 15 sampled Q3 joiners. Compare approval date to provisioned date, and groups granted to the access matrix (Policy &amp; matrix tab). Pre-hire accounts are created disabled before the start date; that's normal.</p>",
  rows:[J("Adele Kingsley","Stores|Sales Associate","Mon, Jul 6","Rafael Montoya, Jul 1","Jul 2",null,0),
   J("Bram Holloway","Stores|Stock Associate","Mon, Jul 13","Keiko Hartley, Jul 8","Jul 9",null,0),
   J("Cecily Vance","Customer Care|Customer Care Agent","Mon, Jul 20","Samir Haddad, Jul 14","Jul 15",null,0),
   J("Dashiell Moore","Stores|Cash Office Associate","Mon, Jul 20","None on file","Jul 16",null,1),
   J("Eloise Brandt","Stores|Sales Associate","Mon, Jul 27","Anneliese Vogt, Jul 21","Jul 22",null,0),
   J("Finnian Rhys","Merchandising|Buyer","Mon, Aug 3","Ingrid Solberg, Jul 28","Jul 29",null,0),
   J("Georgia Platt","Stores|Sales Associate","Mon, Aug 3","Bernadette Quaye, Jul 29","Jul 30",null,0),
   J("Hamish Coyle","Ecommerce|Ecommerce Specialist","Mon, Aug 10","Samir Haddad, Aug 4","Aug 5",null,0),
   J("Ione Delacroix","Stores|Stock Associate","Mon, Aug 17","Rafael Montoya, Aug 13","Aug 11",null,2,"Provisioned Aug 11, approved Aug 13."),
   J("Jasper Wilde","Customer Care|Customer Care Agent","Mon, Aug 24","Samir Haddad, Aug 18","Aug 19",null,0),
   J("Kezia Barlow","Finance|Staff Accountant","Mon, Aug 31","Colleen McBride, Aug 25","Aug 26",null,0),
   J("Lachlan Reid","Stores|Sales Associate","Tue, Sep 8","Keiko Hartley, Sep 1","Sep 2",["APP-POS-Refund-Override"],3,"Refund override isn't a Sales Associate birthright group; only managers approve refunds."),
   J("Mirabel Stone","Stores|Sales Associate","Mon, Sep 14","Anneliese Vogt, Sep 9","Sep 10",null,0),
   J("Nico Varela","Stores|Stock Associate","Mon, Sep 21","Bernadette Quaye, Sep 15","Sep 16",null,0),
   J("Orla Brennan","Stores|Sales Associate","Mon, Sep 28","Rafael Montoya, Sep 24","Sep 23",null,2,"Provisioned Sep 23, approved Sep 24.")],
  lesson:"Test both halves of the control: approval before access, and access limited to the role. 4 of 15 failed (27%), so APD-01 is not operating effectively. A sales associate who can approve their own refunds is a cash-theft risk as well as an audit exception."},
 {id:"G2",ctrl:"APD-02",title:"Test timely terminations",kind:"table",opts:TERM_OPTS,
  intro:"<p><b>APD-02:</b> Accounts are disabled <b>on the HR termination date</b> (PCI DSS Req. 8.2.5: access for terminated users is revoked immediately).</p><p>Test the 12 sampled Q3 separations from the Oct 2 directory extract. Note the standard: same day, not next business day.</p>",
  rows:[X("Arlo Pemberton","Sales Associate","Wed, Jul 8","Wed, Jul 8","Jul 7",0),
   X("Bettina Cruz","Stock Associate","Fri, Jul 10","Mon, Jul 13","Jul 10",1,"Disabled the next business day. PCI DSS requires immediate revocation, so a weekend gap is late even with no sign-in."),
   X("Cassius Lowe","Cash Office Associate","Thu, Jul 16","Thu, Jul 16","Jul 16",0),
   X("Dahlia Fern","Sales Associate","Tue, Jul 21","Tue, Jul 28","Jul 20",1,"Five business days late; no sign-in after separation."),
   X("Elliot Marsh","Buyer","Fri, Jul 31","Fri, Jul 31","Jul 30",0),
   X("Flora Bennett","Assistant Store Manager","Mon, Aug 3","Fri, Aug 14","Aug 7",2,"Approved 3 refund overrides at the POS on Aug 7, four days after separation."),
   X("Garth Willoughby","Customer Care Agent","Fri, Aug 14","Fri, Aug 14","Aug 13",0),
   X("Douglas Whitcombe","Store Manager","Fri, Aug 28","Not disabled","Sep 15",3,"Still enabled at extract, and approved a purchase order after he left."),
   X("Harper Quill","Sales Associate","Tue, Sep 1","Tue, Sep 1","Aug 31",0),
   X("Inez Calloway","Stock Associate","Thu, Sep 10","Thu, Sep 10","Sep 10",0),
   X("Sabrina Cortez","Assistant Store Manager","Sat, Sep 26","Not disabled","Oct 1",3,"Still enabled at extract and signing in. This is the same account from IAM Ops ticket INC0095333."),
   X("Jett Halloway","Ecommerce Specialist","Wed, Sep 30","Wed, Sep 30","Sep 29",0)],
  lesson:"Measure against the standard that applies. Sunset's policy follows PCI DSS, so next business day is late here, even though it would pass at a company with a one-day standard. Keep \"late\" separate from \"late and used\"."},
 {id:"G3",ctrl:"APD-02",title:"Evaluate the termination exceptions",kind:"quiz",
  intro:"<p>Your APD-02 test found 5 exceptions in 12 samples. Additional facts from follow-up:</p><ul><li>Bettina Cruz and Dahlia Fern were disabled late. Logs show no activity after separation.</li><li>Flora Bennett approved 3 refund overrides on Aug 7, four days after separation, all to the same card.</li><li>Douglas Whitcombe's account approved a $6,400 purchase order on Sep 15, after he left.</li><li>Sabrina Cortez's account is still active and signed in on Oct 1.</li></ul><p>Definitions are on the Controls tab.</p>",
  qs:[{q:"Is APD-02 operating effectively for Q3?",short:"Effectiveness conclusion",opts:["Yes: 7 of 12 passed","No: 5 of 12 (42%) failed, which is well above a tolerable rate for a per-event control"],correct:1,pts:2},
   {q:"Flora Bennett approved refunds to one card after she left. What happens with that?",short:"Refunds after separation",opts:["Document it in the finding only","Send it to Security and Loss Prevention now as a security incident and possible fraud. The incident response plan starts, and the refunds are traced and recovered.","Ask Flora about the refunds, and close it if she has an explanation"],correct:1,pts:3},
   {q:"Douglas Whitcombe's account approved a purchase order after he left. How do you treat it?",short:"Purchase approved after separation",opts:["No issue, because the store needed the goods","Refer it to Security and the Controller, have the account disabled now, and tell Internal Audit: a former employee approving a purchase is a SOX control deficiency to evaluate","Wait for the next access review"],correct:1,pts:3}],
  lesson:"At a public retailer, one failed termination control hits two audits: PCI DSS for the stores and payments, and SOX for the purchases and the ledger. Any use after separation is a security incident, and money moved after separation is possible fraud."},
 G4,
 {id:"G5",ctrl:"UAR-01",title:"Review the access review for completeness",kind:"quiz",
  intro:"<p><b>UAR-01:</b> Every six months, managers certify <i>all</i> directory accounts (employees, seasonal staff, service accounts). Revocations are completed within 5 business days (PCI DSS Req. 7.2.4, 7.2.5).</p>",
  evidence:[["Directory extract, Sep 30",`${people.length} accounts: ${staff} employees, ${seasonal} seasonal and contract staff, ${service} service accounts`],["Access review file",`${staff} accounts, all certified by managers`],["Reviewer sign-off","Walter Ng, Oct 1"],["Population source","Excel export provided by IT; no query or run parameters attached"]],
  qs:[{q:"What is the main issue?",short:"Issue identified",opts:[`Completeness: the ${seasonal} seasonal and contract staff and ${service} service accounts were left out of the review`,"Timeliness: sign-off came after quarter end","Accuracy: managers certified too quickly","No issue"],correct:0,pts:3},
   {q:"What evidence do you request? Select all that apply.",multi:true,opts:["A system-generated population with the query, parameters and run date",`Review evidence for the ${seasonal + service} excluded accounts`,"An email from IT confirming the review was complete","Re-perform the whole review yourself"],correct:[0,1]},
   {q:"Until those accounts are reviewed, can UAR-01 be relied on to catch the access APD-02 missed?",short:"Reliance on UAR-01",opts:["Yes","No"],correct:1,pts:2}],
  lesson:"Before testing a review, test the population. Seasonal staff and service accounts are the usual gaps, and PCI DSS asks for service accounts to be reviewed too (Req. 7.2.5)."},
 {id:"G6",ctrl:"RISK",title:"Rate the risk register",kind:"table",opts:["High","Medium","Low"],
  intro:"<p>PCI DSS Req. 12.3.1 calls for targeted risk analyses, and SOX for a risk assessment over financial reporting. Rate each risk's inherent level. Score = likelihood × impact. <b>High</b> 15–25, <b>Medium</b> 8–14, <b>Low</b> 1–7.</p><p class=\"mono\" style=\"font-size:12px\">Likelihood: Rare 1 · Unlikely 2 · Possible 3 · Likely 4 · Almost certain 5<br>Impact: Minimal 1 · Minor 2 · Moderate 3 · Major 4 · Severe 5</p>",
  rows:[RR("R-01 Former staff keep POS and refund access","APD-02 failures; 3 accounts used after separation","Likely","Major",0),
   RR("R-02 Shared register login","Requested for the holiday rush","Possible","Moderate",1),
   RR("R-03 CDE admin who can clear security logs","A payments engineer holds both","Possible","Severe",0),
   RR("R-04 Payment gateway compliance evidence gap","Provider's attestation doesn't cover the token vault","Unlikely","Moderate",2),
   RR("R-05 MFA fatigue attacks","One successful push approval this week","Likely","Moderate",1)],
  lesson:"Apply the matrix the same way every time. R-01 (16) and R-03 (15) lead the remediation plan, ahead of the shared login that feels more urgent in the stores."},
 {id:"G7",ctrl:"VEN-01",title:"Review the payment gateway's PCI attestation",kind:"quiz",
  intro:"<p>Saguaro Payments runs Sunset's online payment gateway and, since this year, stores saved cards as tokens. It's a third-party service provider for PCI DSS (Req. 12.8). The assessment period ends Dec 31.</p>",
  evidence:[["Evidence","Attestation of Compliance for Service Providers, PCI DSS v4.0.1"],["Date","Mar 2026, compliant"],["Services assessed","Payment gateway"],["Services not assessed","Card-on-file token vault"],["Responsibility matrix","Not provided"],["Written agreement","Signed 2021. Doesn't include the provider's acknowledgment of responsibility for the card data it handles."]],
  qs:[{q:"Which follow-ups are needed? Select all that apply.",multi:true,opts:["Get evidence that the token vault Sunset now uses was assessed","Get the responsibility matrix showing which requirements Saguaro and Sunset each manage","Update the agreement to include Saguaro's acknowledgment of responsibility for card data","Confirm Sunset's own responsibilities, such as managing its users in the gateway console, are operating","Track the attestation's renewal so compliance status is checked at least once a year","Drop the provider because a service wasn't assessed","No action needed; the attestation says compliant"],correct:[0,1,2,3,4]},
   {q:"Why does your APD-02 result matter for this review?",short:"Link to APD-02",opts:["It doesn't; Saguaro runs the gateway","Sunset manages its own users in the gateway console. Late terminations mean a Sunset-side responsibility is failing, whatever Saguaro's status.","It means Saguaro's attestation is invalid"],correct:1,pts:3}],
  lesson:"An attestation covers what was assessed, not everything the provider does for you. Check the services in scope, get the responsibility split in writing, and make sure your own half is working (PCI DSS Req. 12.8.2, 12.8.4, 12.8.5)."},
 {id:"G8",ctrl:"POL-EX",title:"Decide a policy exception request",kind:"quiz",
  intro:"<p>After IAM Ops rejected the shared <span class=\"mono\">reg-01</span> login, Stores filed a formal policy exception: \"Associates rotate registers every hour in the holiday rush and the line backs up at every sign-in. Badge sign-in is budgeted for Q2 2027.\"</p>",
  qs:[{q:"What is the decision?",short:"Exception decision",opts:["Deny outright; policy is policy","Approve as asked: one shared login for the registers, including refunds and voids","Approve temporarily for opening the register only, with every refund, void and override still needing the associate's own ID, compensating controls and risk owner sign-off"],correct:2,pts:3},
   {q:"Which conditions belong in the approval? Select all that apply.",multi:true,opts:["Refunds, voids and overrides always need the associate's own ID, so each one traces to a person","Ends Jan 15, after the holidays, with re-review","Register drawer assigned to one associate per shift","Sign-off by the risk owner (Lorraine Okafor, Regional Manager)","Tracked project to replace it with badge sign-in","Let the shared login approve refunds too, to keep the line moving","Tape the password inside the register drawer"],correct:[0,1,2,3,4]}],
  lesson:"GRC's job is managed risk, not saying no. PCI DSS allows a shared ID only as a documented exception where every action can still be traced to one person (Req. 8.2.2). Keep it narrow, time-limited, compensated and owned by the business."},
 {id:"G9",ctrl:"MAP",title:"Map APD-02 to frameworks",kind:"quiz",
  intro:"<p>Map APD-02 (disable accounts on the termination date) so one test can answer several reviews.</p>",
  qs:[{q:"Select every requirement APD-02 supports.",multi:true,opts:["PCI DSS v4.0.1 Req. 8.2.5 (revoke terminated users immediately)","SOX 404 IT general control: logical access, terminations","NIST 800-53 PS-4 Personnel Termination","NIST 800-53 AC-2 Account Management","ISO 27001:2022 A.5.18 Access rights","PCI DSS v4.0.1 Req. 3.5.1 (stored card numbers unreadable)","PCI DSS v4.0.1 Req. 11.3.1 (internal vulnerability scans)","NIST 800-53 CP-9 System Backup","ISO 27001:2022 A.8.13 Information backup"],correct:[0,1,2,3,4]}],
  lesson:"Test once, satisfy many. A mapped control lets one set of APD-02 evidence answer the PCI DSS assessment, the SOX audit and an ISO review."},
 {id:"G10",ctrl:"APD-02",title:"Write the termination finding",kind:"quiz",
  intro:"<p>Build the APD-02 finding. Pick the strongest statement for each element.</p>",
  qs:[{q:"Condition",short:"Condition",opts:["Access was removed late for some staff.","5 of 12 sampled terminations (42%) were not disabled on the termination date. Two accounts were still active at extract, and three former employees used their accounts after leaving, two to move money.","IT doesn't take terminations seriously."],correct:1,pts:2},
   {q:"Criteria",short:"Criteria",opts:["The Termination Procedures policy requires access to be disabled on the termination date (control APD-02), meeting PCI DSS Req. 8.2.5 and supporting the SOX logical access controls.","Best practice says access should be removed quickly.","PCI DSS allows one business day."],correct:0,pts:2},
   {q:"Cause",short:"Cause",opts:["Store managers are careless.","Unknown.","Store terminations reach IT by email, often days later. There is no automated HRIS-to-directory trigger or daily reconciliation."],correct:2,pts:2},
   {q:"Effect",short:"Effect",opts:["Sunset will lose the ability to take cards.","Former employees could approve refunds and purchases after leaving, and two did ($6,400 purchase and refunds to one card, now under investigation). The assessor would mark Req. 8.2.5 not in place, and Internal Audit must evaluate the SOX deficiency.","No impact, because the amounts were small."],correct:1,pts:2},
   {q:"Recommendation",short:"Recommendation",opts:["Automate deprovisioning from the HRIS termination event, and add a daily HRIS-to-directory reconciliation with exceptions reviewed by Security and Loss Prevention.","Remind store managers to email IT faster.","Remove all users' access every quarter."],correct:0,pts:2}],
  lesson:"A finding that holds up is specific (numbers), cites the actual requirement, names a fixable cause, states real impact without exaggeration, and recommends a fix that addresses the cause."}
];
