// Sunset Retail Group's PAM shift. The kit (lib/pamKit.js) supplies grading, hints, the playbook and
// the PAM runbook; this file is the story. Lessons cite PCI DSS v4.0.1 and SOX IT general controls.
import { buildPam } from "../lib/pamKit.js";
import * as company from "./company";
import * as policy from "./policy";

const PCI = id => ({ label: `PCI DSS v4.0.1 Req. ${id}`, href: "https://www.pcisecuritystandards.org/document_library/" });
const SOX = { label: "SOX ITGC (PCAOB AS 2201)", href: "https://pcaobus.org/oversight/standards/auditing-standards/details/AS2201" };
const PSE = "IT|Payments Systems Engineer", STAFF = ["GRP-All-Staff", "APP-Office-Suite", "APP-Service-Desk"];

export const pam = buildPam({
  id: "sunset-retail",
  eligible: { [PSE]: ["ROLE-CDE-Admin"], "IT|Security Analyst": ["ROLE-Security-Log-Admin"], "IT|IT Director": ["ROLE-User-Admin"], "Vendors|POS Vendor Support": ["ROLE-POS-Admin"] },
  also: ["ROLE-Global-Admin"],
  roles: { "Vendors|POS Vendor Support": ["GRP-Contractors"] },
  cast: [
    ["nikolai.berg", "Nikolai Berg", "SR-100181", PSE, "Walter Ng"],
    ["selena.moss", "Selena Moss", "SR-100183", PSE, "Walter Ng", { groups: [...STAFF, "APP-Payment-Gateway", "ROLE-CDE-Admin"] }],
    ["dexter.vail", "Dexter Vail", "SR-100185", "IT|Security Analyst", "Walter Ng", { groups: [...STAFF, "ROLE-CDE-Admin"] }],
    ["rowan.pike", "Rowan Pike", "SR-100187", PSE, "Walter Ng"],
    ["lucia.ferro", "Lucia Ferro", "SR-100189", PSE, "Walter Ng", { groups: [...STAFF, "APP-Payment-Gateway", "ROLE-CDE-Admin"], jit: { "ROLE-CDE-Admin": 2 } }],
    ["grant.osei", "Grant Osei", "SR-100191", PSE, "Walter Ng"],
    ["paige.lowry", "Paige Lowry", "SR-100193", "IT|Service Desk Analyst", "Walter Ng"],
    ["marek.novak", "Marek Novak", "SRV-0412", "Vendors|POS Vendor Support", "Walter Ng (sponsor)", { type: "Contractor", enabled: false, expiry: 190, last: 23 }],
    ["bg-admin-01", "bg-admin-01", "BG-01", null, "Walter Ng (owner)", { dept: "IT", title: "Break-glass account: emergency Global Admin", type: "Break-glass", groups: ["ROLE-Global-Admin"], enabled: false, mfa: false, last: 266 }],
  ],
  hr: [{ type: "Termination", who: "Grant Osei", detail: "Involuntary. Effective today, 9:30 AM. Payments Systems Engineer with CDE admin eligibility.", when: 0 }],
  cite: { "pam-jit": [PCI("7.2.2"), SOX], "pam-eligible": [PCI("7.2.1"), PCI("7.2.4")], "pam-breakglass": [PCI("8.6.1"), PCI("8.6.3")],
    "pam-vault": [PCI("8.6.3"), PCI("8.3.2")], "pam-session": [PCI("10.2.1.2"), PCI("10.4.1")], "pam-vendor": [PCI("8.2.7")], "pam-shared": [PCI("8.2.2")] },
  mon: {
    jit: { id: "REQ0064101", uid: "nikolai.berg", group: "ROLE-CDE-Admin", hours: 2, change: "CHG0063340", approver: "Colleen McBride",
      what: "update the payment gateway's TLS configuration", from: "Nikolai Berg", channel: "Portal", opened: "6:45 AM",
      lesson: "Activate an eligible role for the approved window only, with the approval on the ticket first. PCI DSS 7.2.2 (access by job and least privilege, including privileged users)." },
    breakGlass: { id: "INC0096101", uid: "walter.ng", bg: "bg-admin-01", title: "Emergency: admins locked out, need break-glass", from: "Walter Ng", channel: "Phone", opened: "7:00 AM",
      body: "<p>\"It's Walter. The MFA service is down and none of the admins can sign in. Stores open at 9 and the POS price file didn't load overnight, so registers will ring up yesterday's prices. I'm declaring an emergency. I need bg-admin-01.\"</p>",
      lesson: "Break-glass access is real admin power with no MFA in front of it. Verify the caller, enable only the documented account, and tell Security straight away. PCI DSS 8.6.1 (system accounts used interactively only by exception)." },
    notEligible: { id: "REQ0064104", uid: "paige.lowry", group: "ROLE-CDE-Admin", title: "CDE admin for the service desk", from: "Paige Lowry", channel: "Portal", opened: "7:20 AM",
      body: "<p>Stores call every morning with a frozen card reader, and I have to wait for payments engineering to restart it. If I had CDE admin I could restart them myself. Walter's approved it.</p>",
      alt: "explain that Service Desk Analysts aren't eligible for ROLE-CDE-Admin. Card reader restarts go to a Payments Systems Engineer.",
      lesson: "Eligibility for a privileged role comes from the job. A manager's approval can't add a role the job doesn't include. PCI DSS 7.2.1 and 7.2.2." },
    rotate: { id: "REQ0064107", svc: "svc-pos-sync", down: "The POS to ERP sales sync", title: "svc-pos-sync password in a store email", from: "Callum Frazer", channel: "Email", opened: "7:35 AM",
      body: "<p>A regional manager forwarded an old setup email with the <span class=\"mono\">svc-pos-sync</span> password in it to all 38 store managers yesterday.</p><p>Please deal with the password. Sales have to keep syncing to the ERP or the daily close won't balance.</p>",
      lesson: "An exposed service credential is rotated, not disabled. Sales keep syncing and the leaked password stops working. PCI DSS 8.6.3 (protect system account passwords, change them on suspected compromise)." },
    standing: { id: "TSK0018101", holders: [["selena.moss", "ROLE-CDE-Admin"], ["dexter.vail", "ROLE-CDE-Admin"]], bg: "bg-admin-01", bgGroup: "ROLE-Global-Admin",
      title: "PAM report: standing privileged memberships", from: "PAM vault (weekly report)", channel: "Automated", opened: "8:00 AM",
      body: "<p>These accounts hold a vaulted role permanently instead of activating it:</p><ul><li><span class=\"mono\">selena.moss</span>: ROLE-CDE-Admin (since the vault migration)</li><li><span class=\"mono\">dexter.vail</span>: ROLE-CDE-Admin (added for a forensics review in April)</li><li><span class=\"mono\">bg-admin-01</span>: ROLE-Global-Admin</li></ul><p>Clean up the standing access per the PAM runbook.</p>",
      lesson: "Standing admin access to the cardholder data environment is what PCI DSS access reviews look for. Remove it, except where the runbook documents an exception. PCI DSS 7.2.4." },
    adminLeaver: { id: "REQ0064110", uid: "grant.osei", svc: "svc-file-backup", title: "Termination: Grant Osei, Payments Systems Engineer", from: "HR system (automated)", channel: "HR integration", opened: "8:15 AM",
      body: "<p>Involuntary termination, effective 9:30 AM today. Remove all access before the meeting.</p><p>PAM vault note: Grant checked out the <span class=\"mono\">svc-file-backup</span> password on Wednesday and it hasn't been rotated since.</p>",
      lesson: "An admin leaver's access ends only when what they knew stops working: rotate any credential they checked out. PCI DSS 8.2.5 and 8.6.3." },
    vendor: { id: "REQ0064113", uid: "marek.novak", group: "ROLE-POS-Admin", hours: 2, title: "Vendor support session: POS software update", from: "Walter Ng", channel: "Portal", opened: "8:30 AM",
      body: "<p>Marek from the POS vendor needs admin on the POS management server to push the fix for the loyalty discount bug. The session is booked from 9:00 to 11:00 AM. His account is off between sessions.</p>",
      lesson: "Vendor access is opened for one approved session: sponsor approval, the account enabled, the role for the session only. PCI DSS 8.2.7 (third-party remote access enabled only when needed)." },
    noChange: { id: "REQ0064116", uid: "rowan.pike", group: "ROLE-CDE-Admin", target: "The payment gateway", title: "CDE admin for the weekend", from: "Rowan Pike", channel: "Portal", opened: "9:00 AM",
      body: "<p>I'd like to clean up old log files on the payment gateway this weekend when sales are quiet. Can you activate CDE admin for me from Friday evening to Sunday night, about 48 hours? There's no change raised, it's routine.</p>",
      alt: "explain that eligibility isn't enough: the work needs an approved change, and activations are capped at 4 hours.",
      lesson: "Eligible isn't approved. Privileged roles are activated for an approved change, for a short window. PCI DSS 7.2.2 and 6.5.1 (change control)." },
    session: { id: "REQ0064119", title: "Weekly privileged session review", from: "Security team", channel: "Email", opened: "9:25 AM",
      intro: "<p>Yesterday's recorded CDE admin sessions are below. Check each one against the change or incident it was opened for, and send us the IDs of any session that went outside it.</p>",
      rows: [
        ["PSM-70503", "selena.moss", "CHG0063310: patch the gateway servers", "PAY-GW-01", "Installed patches, rebooted, <b>ran a query that returned full card numbers from the tokenization vault</b>", true],
        ["PSM-70508", "lucia.ferro", "INC0096050: card reader timeouts at store 112", "POS-MGT-01", "Read the device logs, pushed a reader config refresh", false],
        ["PSM-70512", "rowan.pike", "CHG0063318: firewall rule for the new Bend store", "FW-CDE-01", "Added the store's VPN rule, <b>opened remote desktop on the gateway to the internet</b>", true],
        ["PSM-70519", "nikolai.berg", "CHG0063321: renew the gateway certificate", "PAY-GW-01", "Imported the certificate, restarted the gateway service", false],
        ["PSM-70524", "dexter.vail", "INC0096055: investigate a malware alert", "POS-MGT-01", "Collected the alert's files, isolated one register", false],
      ],
      lesson: "A recorded session only protects card data if someone compares it with the reason it was opened. PCI DSS 10.2.1.2 (log all admin actions) and 10.4.1 (review logs daily)." },
    compromised: { id: "INC0096104", uid: "lucia.ferro", group: "ROLE-CDE-Admin", title: "SIEM alert: admin sign-in from abroad", from: "SIEM alert", channel: "Automated", opened: "9:45 AM",
      body: "<p>At 5:55 AM <span class=\"mono\">lucia.ferro</span> approved an MFA prompt after 29 push requests, signed in from an IP address in Ukraine, and activated ROLE-CDE-Admin for 2 hours. Lucia says she approved a prompt to make her phone stop buzzing.</p>",
      lesson: "A compromised admin account is contained when the attacker has nothing left: no session, password, MFA method or privileged role. Then Security takes it. PCI DSS 12.10.1." },
    shared: { id: "REQ0064122", uid: "fergus.doherty", title: "Shared admin login for store opening", from: "Fergus Doherty", channel: "Portal", opened: "10:00 AM",
      body: "<p>Store-opening calls start at 6 AM and no admin is in until 8. Could the early desk share a <span class=\"mono\">storeadmin</span> login, or could you text them the POS admin password?</p>",
      alt: "explain that admin passwords are never shared. Admins check credentials out of the vault under their own accounts, and early store issues go to the on-call Payments Systems Engineer.",
      lesson: "Shared admin credentials make every change anonymous and can't be taken back from one person. PCI DSS 8.2.2 (shared accounts only by exception, with every action traceable)." },
    auditQ: { id: "REQ0064125", group: "ROLE-CDE-Admin", title: "QSA request: who holds CDE admin", from: "QSA (PCI DSS assessment)", channel: "Email", opened: "10:15 AM",
      body: "<p>For the PCI DSS assessment, please list every enabled account that holds <span class=\"mono\">ROLE-CDE-Admin</span> right now, including any just-in-time activations still running. Usernames are fine.</p>",
      lesson: "Assessment evidence is pulled from the system as it stands. PCI DSS 7.2.4 (review user accounts and access)." },
  },
  thu: {
    bgClose: { id: "TSK0018104", from: "Walter Ng", channel: "Portal", opened: "10:40 AM",
      body: "<p>MFA is back, the price file loaded, and the admins can sign in. Emergency over as of 10:30 AM. Please close out bg-admin-01 per the break-glass procedure.</p>",
      lesson: "Break-glass is closed as deliberately as it's opened: disabled, rotated and signed out. PCI DSS 8.6.1 and 8.6.3." },
    vendorEnd: { id: "TSK0018107", from: "Walter Ng", channel: "Portal", opened: "11:05 AM",
      body: "<p>Marek pushed the loyalty fix and stores have confirmed it. Session's over. Please close his access.</p>",
      lesson: "Third-party access ends with the session. PCI DSS 8.2.7." },
  },
  conseq: {
    standingJit: { id: "INC0096110", from: "PAM vault", channel: "Automated", opened: "Afternoon" },
    notEligible: { id: "INC0096113", from: "Security team", channel: "Email", opened: "Afternoon" },
    svcDown: { id: "INC0096116", from: "Callum Frazer", channel: "Phone", opened: "Afternoon" },
    svcLeak: { id: "INC0096119", from: "SIEM alert", channel: "Automated", opened: "Afternoon" },
    leaver: { id: "INC0096122", from: "Security team", channel: "Email", opened: "Afternoon" },
    noChange: { id: "INC0096125", from: "Security team", channel: "Email", opened: "Afternoon" },
    compromised: { id: "INC0096128", from: "SIEM alert", channel: "Automated", opened: "Afternoon" },
    bgOpen: { id: "INC0096131", from: "PAM vault", channel: "Automated", opened: "Afternoon" },
    vendorOpen: { id: "INC0096134", from: "Security team", channel: "Email", opened: "Afternoon" },
  },
}, company, policy);
