// Sunset Retail Group's week on the service desk. The kit (lib/ticketKit.js) supplies grading,
// hints, the playbook and Jordan Reyes' week; this file is the story. Lessons cite PCI DSS v4.0.1
// by requirement number only (the standard is copyrighted by the PCI SSC) and SOX section 404.
import { buildTicketSet } from "../lib/ticketKit.js";
import { ROLES, SOD, buildUsers } from "./company";
import { G } from "./grc.js";

const m = x => `<span class="mono">${x}</span>`;

export const set = buildTicketSet({
  id: "sunset-retail", ROLES, SOD, buildUsers,
  mon: {
    joiner: { id: "REQ0063104", uid: "imani.walker", rk: "Stores|Sales Associate", title: "New hire: Imani Walker, Sales Associate",
      from: "HRIS (automated)", channel: "HR integration", opened: "6:15 AM",
      body: "<p>New hire starting today at Canyon Plaza. The pre-hire account was created by the HRIS sync but is disabled with no access.</p><p>Please activate the account and provision access for the role. Register training is on file. The store opens at 10:00 AM.</p>",
      lesson: "Provision from the role in the access matrix, nothing more. PCI DSS Req. 7.2.2 (access based on job function) and 8.2.4 (authorized additions)." },
    callerPw: { id: "INC0095311", uid: "clarissa.wren", title: "Forgot password after vacation",
      from: "Clarissa Wren", channel: "Phone", opened: "7:39 AM",
      body: "<p>\"Hi, I just got back from a week off and my password expired while I was away. I tried a new one and now I can't remember which. Can you reset it? Month-end close starts today.\"</p>",
      lesson: "Verify identity against the system of record before any credential reset. A reset handed to an impostor is a way into the ledger. SOX 404 (logical access to financial systems)." },
    callerLock: { id: "INC0095314", uid: "bartholomew.finch", title: "Locked out on the receiving scanner",
      from: "Bartholomew Finch", channel: "Phone (store line)", opened: "7:50 AM",
      body: "<p>\"The handheld kept rejecting me on the dock, so I typed my password a bunch of times and now it says locked. I know my password. The truck's here and I've got pallets to check in.\"</p>",
      lesson: "A lockout is not a forgotten password. Unlock only after verifying who's calling; a reset adds risk for no reason. PCI DSS Req. 8.3.4." },
    callerMfa: { id: "INC0095318", uid: "isolde.marchbanks", title: "Phone stolen at a trade show",
      from: "Isolde Marchbanks", channel: "Phone (desk line)", opened: "7:59 AM",
      body: "<p>\"My phone was stolen at the home goods show in Las Vegas on Saturday. The authenticator was on it. I've got a new phone, but I can't sign in, and I have holiday orders to place today.\"</p>",
      lesson: "Clear the stolen authenticator and end any sessions the phone may still hold. PCI DSS Req. 8.4 (MFA)." },
    leaver: { id: "REQ0063112", uid: "april.nakamura", title: "Termination: April Nakamura, effective 9:00 AM",
      from: "Ruby Castaneda (HR Director)", channel: "HR integration", opened: "8:05 AM",
      body: "<p>Involuntary termination effective today at 9:00 AM, following a cash-office variance review. Remove all access per the leaver policy before she is told.</p>",
      lesson: "Leavers: disable, revoke sessions, remove all access, before the person is told. PCI DSS Req. 8.2.5 (revoke terminated users immediately)." },
    mover: { id: "REQ0063115", uid: "jonah.feldman", fromRk: "Stores|Sales Associate", toRk: "Stores|Stock Associate",
      title: "Transfer: Jonah Feldman, Sales to Stock", from: "HRIS (automated)", channel: "HR integration", opened: "8:13 AM",
      body: "<p>Jonah Feldman is moving from Sales Associate to Stock Associate at the same store, effective today. Same manager. Update his job info and access.</p>",
      lesson: "Movers are where privilege creep starts. Remove the old role's access, not just add the new. Someone who receives stock and can still ring sales has no second person watching. PCI DSS Req. 7.2.2." },
    sodReq: { id: "REQ0063119", uid: "octavia.rhodes", group: "APP-Vendor-Master", holds: "APP-Purchase-Orders",
      title: "Access request: vendor setup for Octavia Rhodes", from: "Octavia Rhodes", channel: "Self-service portal", opened: "8:21 AM",
      approval: "Ingrid Solberg replied: \"Approved. She's onboarding a lot of small makers for the holiday line.\"",
      alt: "suggest Octavia sends new supplier details to Vendor Setup, who confirm the bank details with a callback, so the person ordering never creates the supplier.",
      body: `<p>Requesting ${m("APP-Vendor-Master")} so I can set up new small suppliers myself for the holiday line instead of waiting on Vendor Setup.</p>`,
      lesson: "Manager approval doesn't override separation of duties. The person who orders from a supplier must never be the person who creates it. SOX 404 (internal control over financial reporting)." },
    request: { id: "REQ0063123", uid: "keiko.hartley", group: "APP-POS-Reports", approver: "Lorraine",
      title: "Access request: POS reports", from: "Keiko Hartley", channel: "Self-service portal", opened: "8:27 AM",
      approval: "Lorraine Okafor replied: \"Approved. Keiko is reviewing refunds and voids at her store after last month's variance.\"",
      body: `<p>Requesting ${m("APP-POS-Reports")} to review refunds and voids by register at my store.</p>`,
      lesson: "Requestable access needs a documented approval before it's granted, and only what was asked. PCI DSS Req. 7.2.2, 8.2.4." },
    exec: { id: "INC0095326", uid: "vikram.sethi", saidEmpId: "SR-100040", title: "URGENT: CFO locked out before an earnings filing",
      from: "Caller says: Vikram Sethi (CFO)", channel: "Phone (unknown mobile number)", opened: "8:34 AM",
      body: "<p>\"This is Vikram Sethi. I'm at the retail investor conference and my phone died. I'm on a borrowed one. Move my MFA to this number right now. If I can't approve the supplier prepayment by 9, the holiday shipment misses the boat.\"</p>",
      lesson: "Urgency plus authority plus a new device is the classic social-engineering pattern. Check the details, refuse, and report it. PCI DSS Req. 12.10 (incident response)." },
    contractor: { id: "REQ0063127", uid: "corey.blackwell", title: "Extend seasonal associate: Corey Blackwell",
      from: "Keiko Hartley (sponsor)", channel: "Email", opened: "8:40 AM",
      approval: "Keiko Hartley (sponsor) replied: \"Approved. We're keeping Corey through the holidays.\"",
      body: "<p>Corey's seasonal assignment was extended through the holidays. His account expires in 2 days. Please extend it.</p>",
      lesson: "Seasonal and contract accounts always have an end date and a sponsor approval, capped at 90 days per extension. PCI DSS Req. 8.2.4." },
    sweep: { id: "TSK0017208", dormant: [["heather.lindgren", 118], ["percy.oyelowo", 99]], under: ["cornelius.ashdown", 89], svc: "svc-file-backup",
      title: "Weekly: disable inactive accounts", from: "Scheduled report", channel: "Automated task", opened: "8:47 AM",
      body: "<p>Weekly inactive-account sweep. Per policy, disable any user account with no sign-in for more than 90 days. Pre-hire accounts are excluded.</p><p>Use the Directory's sort by last sign-in.</p>",
      lesson: "Dormant accounts are a favorite target. Apply the threshold exactly, and send service accounts to their owner instead of breaking a production job. PCI DSS Req. 8.2.6." },
    recon: { id: "INC0095333", uid: "sabrina.cortez", left: "Sep 26", signedIn: "Saturday",
      title: "HR reconciliation: former assistant manager still active", from: "HRIS-to-directory reconciliation report", channel: "Automated report", opened: "8:55 AM",
      body: "<p>The weekly HR reconciliation found an account that is still enabled for a person HR shows as separated. Check the HR feed and the account's last sign-in.</p>",
      lesson: "A former employee who can still approve refunds is a security incident. Contain it, then report it. PCI DSS Req. 8.2.5, 12.10." },
    priv: { id: "REQ0063131", uid: "fergus.doherty", group: "ROLE-CDE-Admin",
      route: "point Fergus to Callum Frazer: cardholder data environment admin needs the CISO's approval and MFA, and is held only by the payments systems engineers.",
      title: "Need CDE Admin to fix a payment terminal", from: "Fergus Doherty (Service Desk)", channel: "Teams message", opened: "9:03 AM",
      body: "<p>\"Can you put me in CDE Admin for the day? Two card terminals at Canyon Plaza won't pair and Callum is out. Walter said it's fine.\"</p>",
      lesson: "Cardholder data environment admin is never granted by ticket. It reaches every card payment. PCI DSS Req. 7.2.1, 7.2.2, 8.4.2." },
    rehire: { id: "REQ0063134", uid: "tatiana.rusu", rk: "Stores|Sales Associate", pwAge: "10-month",
      title: "Rehire: Tatiana Rusu, Sales Associate", from: "HRIS (automated)", channel: "HR integration", opened: "9:08 AM",
      body: "<p>Rehire starting today. The HRIS sync matched her existing disabled account. Reactivate and provision for the role.</p>",
      lesson: "Rehires carry old access and old passwords. Check access against the role, and issue a fresh credential. PCI DSS Req. 8.2.4." },
    shared: { id: "REQ0063138", uid: "rafael.montoya",
      alt: "offer quick-switch POS sign-in with each associate's badge, so every refund and void still traces to one person.",
      title: "Shared register login for the holiday rush", from: "Rafael Montoya (Store Manager)", channel: "Email", opened: "9:14 AM",
      body: `<p>"Can we get one login like ${m("reg-01")} for the front registers through the holidays? Associates rotate every hour and the line backs up while they sign in."</p>`,
      lesson: "Shared accounts destroy accountability: when a drawer is short, nobody can say who ran the refund. PCI DSS Req. 8.2.1, 8.2.2." },
    review: { id: "REQ0063141", uid: "wilhelmina.frost", group: "APP-POS-Reports",
      title: "Access review action: remove POS reports", from: "H2 access review (Bernadette Quaye)", channel: "Access review", opened: "9:19 AM",
      body: "<p>Six-month user access review result: reviewer Bernadette Quaye marked <b>Wilhelmina Frost: APP-POS-Reports</b> as <b>Revoke</b> (\"Only the store manager pulls POS reports now\"). All other entitlements certified.</p>",
      lesson: "A review only counts if the revocations are carried out and evidenced. Remove exactly what the reviewer marked. PCI DSS Req. 7.2.4." },
    loa: { id: "REQ0063144", uid: "leon.baptiste", title: "Leave of absence: Leon Baptiste",
      from: "HRIS (automated)", channel: "HR integration", opened: "9:24 AM",
      body: "<p>Leon Baptiste begins leave today. Expected return Dec 7, 2026. Apply the leave of absence policy.</p>",
      lesson: "Leave is not termination. Disable to block use, but keep entitlements so he returns on day one." },
    copy: { id: "REQ0063147", uid: "noel.garrido", peer: "henrietta.sowerby", rk: "Ecommerce|Ecommerce Specialist", extras: ["APP-Order-Management", "APP-Payment-Gateway"],
      title: "New hire Noel Garrido: \"same as Henrietta\"", from: "Samir Haddad (Ecommerce Manager)", channel: "Email", opened: "9:31 AM",
      body: "<p>\"Noel starts on the ecommerce team today. Just give him whatever Henrietta Sowerby has so she can train him. Thanks!\"</p>",
      lesson: "Never mirror a peer. Peers carry leftover access, and copying can spread it into the cardholder data environment. Provision from the role, and flag the peer's extras for review. PCI DSS Req. 7.2.2." },
    auditQ: { id: "REQ0063150", groups: ["APP-POS-Refund-Override", "APP-Cash-Office-Reconcile"],
      title: "Internal Audit request: refund and cash office conflicts", from: "Jerome Batiste (Internal Audit Manager)", channel: "Email", opened: "9:38 AM",
      body: "<p>\"For our SOX testing of store cash controls, please list every <b>enabled</b> user who currently holds <b>both</b> APP-POS-Refund-Override and APP-Cash-Office-Reconcile.\"</p><p>Enter usernames (first.last) separated by commas, or <b>none</b>, in the answer box when you close the ticket.</p>",
      lesson: "Audit evidence must be complete and accurate. Pull it from the system, not from memory. Remediation is a separate, approved change. SOX 404." },
    compromise: { id: "INC0095342", uid: "fenella.strickland", title: "Impossible travel + MFA fatigue: Fenella Strickland",
      from: "Identity protection alert", channel: "SIEM alert", opened: "9:46 AM",
      body: "<p>High-risk sign-in. Fenella Strickland signed in from Phoenix at 9:03 AM and from Lagos at 9:20 AM. The Lagos sign-in followed 15 MFA push prompts, one of which was approved.</p><p>Fenella confirmed by desk phone she did not travel and approved a prompt \"to make them stop.\" Her account can change online orders and issue refunds.</p>",
      lesson: "Contain first: revoke sessions, rotate the password, re-register MFA, then hand off to Security, who start the incident response plan. PCI DSS Req. 12.10." },
  },
  thu: {
    adminReq: { id: "REQ0063182", uid: "samir.haddad", group: "APP-Payment-Gateway",
      alt: "The payment gateway is in the cardholder data environment: it needs the CISO's approval and is limited to the payments systems engineers. Failed-payment reports can come from order management.",
      jordanNote: "CEO approved so he can see failed payments directly.",
      title: "Access request: payment gateway for Samir Haddad", from: "Samir Haddad", channel: "Self-service portal", opened: "7:42 AM",
      approval: "Marguerite Laine replied: \"Approved. He needs to see why holiday orders are failing at checkout.\"",
      body: `<p>Requesting ${m("APP-Payment-Gateway")} so I can look up failed payments and issue refunds directly in the gateway.</p>`,
      lesson: "Cardholder data environment access isn't requestable, whoever approves. Keep the CDE small and limited to the people who run it. PCI DSS Req. 7.2.1, 7.2.2." },
    loaReturn: { id: "REQ0063185", title: "Early return from leave: Leon Baptiste", from: "HRIS (automated)", channel: "HR integration", opened: "7:58 AM",
      body: "<p>Leon Baptiste has returned from leave early and is back today. Restore his access so he can work.</p>",
      lesson: "Because leave means disable-and-keep, a return is one click. If his groups were removed Monday, you're rebuilding access from the matrix now." },
  },
  conseq: {
    stale: { id: "INC0095403", title: n => "Dormant account signed in from unknown IP: " + n, from: "Identity protection alert", channel: "SIEM alert", opened: "2:13 AM",
      body: n => `<p>${n}'s account had no sign-in for months. At 2:13 AM it signed in from a hosting-provider IP after a password spray, registered a new MFA method, and issued gift-card refunds through the POS back office.</p><p>This account was on Monday's inactive-account report.</p>`,
      prevented: "Overnight, an attacker sprayed passwords at dormant accounts. Every attempt failed because you disabled them Monday.",
      lesson: "A stale account is a door nobody is watching. Contain it and hand it to Security. PCI DSS Req. 8.2.6, 12.10." },
    svc: { id: "INC0095406", restores: "the file server backups", title: "Nightly file server backups failing since Monday", from: "Backup monitoring", channel: "Automated alert", opened: "6:04 AM",
      body: `<p>The finance file server backup job has failed three nights in a row: ${m("Logon failure: account disabled (svc-file-backup)")}.</p><p>There is no restorable copy of the month-end close files since Sunday.</p>`,
      prevented: "Nightly file server backups ran clean all week. You sent svc-file-backup to its owner instead of disabling it.",
      lesson: "Service accounts aren't people. Disabling one breaks production silently, here in the middle of month-end close. Restore service, then let the owner decide." },
    leaver: { id: "INC0095409", title: "Terminated cash office associate used the back office", from: "POS back-office activity report", channel: "Email", opened: "7:20 AM",
      body: "<p>April Nakamura, terminated Monday at 9:00 AM, signed in to the POS back office from home Tuesday at 10:20 PM and edited Monday's cash-office reconciliation.</p>",
      prevented: "April Nakamura tried the POS back office from home Tuesday night and was blocked. Clean offboarding.",
      effect: "April Nakamura edited a cash-office reconciliation from home the night after her termination (INC0095409).",
      lesson: "Offboarding isn't done until the account is disabled, sessions are revoked and access is removed. Post-termination changes to cash records are an incident for Security and Loss Prevention. PCI DSS Req. 8.2.5." },
    recon: { id: "INC0095412", title: "Former assistant manager approved refunds", from: "Loss prevention analytics", channel: "SIEM alert", opened: "7:47 AM",
      body: "<p>sabrina.cortez approved 6 refund overrides to the same card at another store Wednesday, $1,940 in total. HR shows she left Sunset Retail on Sep 26.</p>",
      prevented: "Sabrina Cortez's old account tried the POS Tuesday and was blocked.",
      effect: "A former assistant manager approved $1,940 in refund overrides after she left (INC0095412).",
      lesson: "Every day a former employee stays enabled is a day of exposure. Contain it and report it to Security and Loss Prevention. PCI DSS Req. 8.2.5, 12.10." },
    sodReq: { id: "INC0095415", title: "Buyer set up a supplier and sent it a PO", from: "AP analytics", channel: "SIEM alert", opened: "8:03 AM",
      body: "<p>octavia.rhodes created a new supplier Tuesday at 3:10 PM and sent it a $38,000 purchase order at 3:24 PM. The supplier's bank account was opened last month, and its address is a mailbox store.</p>",
      prevented: "Every new supplier this week was set up by Vendor Setup, with a bank callback.",
      effect: "A buyer created a supplier and sent it a $38,000 purchase order (INC0095415).",
      lesson: "This is exactly what separation of duties prevents. Remove the conflicting access now and send it to Security as possible fraud. SOX 404." },
    copy: { id: "REQ0063188", title: "Why can a new ecommerce specialist reach the payment gateway?", from: "Callum Frazer (Payments Systems Engineer)", channel: "Email", opened: "8:11 AM",
      body: "<p>\"Noel Garrido started Monday and shows up in the payment gateway's user list. That puts him in our PCI scope. How does he have that? Fix it, and check whoever he was copied from.\"</p>",
      prevented: "Noel started with clean ecommerce access. Henrietta Sowerby's leftover access is still worth a review.",
      effect: "A new ecommerce specialist got payment gateway access copied from a peer (REQ0063188).",
      lesson: "Copying a peer copies their mistakes. Fix both people, and use the role matrix from now on. PCI DSS Req. 7.2.2." },
    priv: { id: "INC0095418", title: "CDE Admin installed software on payment terminals", from: "Terminal management alert", channel: "SIEM alert", opened: "8:22 AM",
      body: "<p>fergus.doherty used CDE Admin to push an unapproved software package to 14 payment terminals Tuesday night. Fergus says he didn't do it. His account signed in from a new device Tuesday.</p>",
      prevented: "CDE administration stayed with the payments systems engineers, with CISO approval and MFA.",
      effect: "A standing CDE Admin grant was used to push unapproved software to payment terminals (INC0095418).",
      lesson: "Standing admin rights turn one phished technician into a card-skimming breach. Remove the role, contain the account, and start the incident response plan. PCI DSS Req. 7.2.1, 12.10." },
    exec: { id: "INC0095421", title: "$295,000 paid to a fake supplier", from: "Colleen McBride (Controller)", channel: "Phone", opened: "8:30 AM",
      body: "<p>A $295,000 prepayment to new bank details for a holiday supplier was approved from Vikram Sethi's account Monday at 9:04 AM. The real Vikram was in the office all day and never called the desk. The attacker registered their own phone for MFA.</p>",
      prevented: "The real Vikram Sethi thanked the desk. The \"conference call\" came from a fraud crew targeting retailers before the holidays.",
      effect: "An attacker impersonating the CFO got a $295,000 prepayment approved (INC0095421).",
      lesson: "One skipped identity check paid for the attacker's quarter. Contain the account, remove their MFA method, and involve Security, Legal and the bank right away." },
    contractor: { id: "INC0095424", title: "Seasonal associate locked out; registers short", from: "Keiko Hartley (sponsor)", channel: "Phone", opened: "8:43 AM",
      approval: "Keiko Hartley (sponsor) replied: \"Approved. Same extension I sent Monday.\"",
      body: "<p>\"Corey's account expired Wednesday and he couldn't sign in to a register last night. We ran one lane short all evening. I asked for this Monday!\"</p>",
      prevented: "Corey Blackwell's seasonal assignment rolled over without a gap.",
      lesson: "Missed requests have a cost too. Seasonal accounts need the end date, the sponsor approval and the extension handled together." },
    compromise: { id: "INC0095427", title: "Fenella Strickland's account redirected 30 refunds", from: "Order management alert", channel: "SIEM alert", opened: "8:59 AM",
      body: "<p>fenella.strickland changed the refund method on 30 online orders to a new prepaid card overnight. The sign-ins came from the same Lagos infrastructure as Monday's alert.</p>",
      prevented: "Security traced the Lagos sign-in to a phishing kit and blocked it network-wide after your escalation.",
      lesson: "Half-contained is not contained. The attacker kept a session or token and came back. Do every step, then escalate. PCI DSS Req. 12.10." },
    callerPw: { id: "INC0095430", title: "\"I never asked for a password reset\"", from: "Clarissa Wren", channel: "Phone (desk line)", opened: "9:12 AM",
      body: "<p>\"I was still off Monday morning. Someone called in as me, got my password reset, and has been in my email and the general ledger since. How did they get through?\"</p><p>There is no identity verification on record for Monday's reset.</p>",
      prevented: "Clarissa Wren confirmed the reset was her, and your verification is on record.",
      effect: "An unverified reset let an attacker into Clarissa Wren's email and the general ledger (INC0095430).",
      lesson: "If verification isn't recorded, it didn't happen. That's true for auditors and for attackers. Contain, rotate, escalate." },
    review: { id: "REQ0063191", title: "Internal Audit: H2 review revocation still open", from: "Jerome Batiste (Internal Audit Manager)", channel: "Email", opened: "9:21 AM",
      body: "<p>\"Follow-up testing shows Wilhelmina Frost still holds APP-POS-Reports, which the reviewer marked for revocation. That's an exception in our SOX and PCI testing unless it's fixed and evidenced today.\"</p>",
      prevented: "Internal Audit closed the access review with no open revocations.",
      lesson: "An access review isn't finished when the manager clicks Revoke. It's finished when access is actually removed. PCI DSS Req. 7.2.4." },
    mover: { id: "REQ0063194", title: "Transferred stock associate still ringing sales", from: "Rafael Montoya (Store Manager)", channel: "Email", opened: "9:33 AM",
      body: "<p>\"Jonah moved to stock Monday, but he rang up three sales on register 4 yesterday, all with employee discounts. Why does he still have the POS?\"</p>",
      prevented: "Jonah's transfer was clean. The store confirmed he has no register access.",
      effect: "Jonah Feldman kept POS access after moving to stock and rang discounted sales (REQ0063194).",
      lesson: "Movers keep old access unless someone removes it. This is how privilege creep builds. PCI DSS Req. 7.2.2." },
  },
  audit: { manager: { name: "Walter Ng", title: "IT Director" } },
  grc: {
    G,
    ctx: "PCI DSS assessment",
    intro: "You're Sunset Retail's internal auditor, testing access controls before the annual PCI DSS assessment by the Qualified Security Assessor.",
    levels: { title: "Security incident or card data compromise", items: [
      ["Security event", "anything that could affect the security of systems or card data, such as a failed sign-in or an alert. Most are triaged and closed."],
      ["Security incident", "an event that actually or likely compromises systems or data. The incident response plan starts (PCI DSS Req. 12.10.1)."],
      ["Suspected card data compromise", "the incident response plan includes telling the acquiring bank and following the card brands' rules, which can require a forensic investigation by a PCI Forensic Investigator."]],
      note: "Audit findings go to the IT Director and Internal Audit. Anything that may involve card data goes to Security at once." },
    controls: {
      "APD-02": ["Timely terminations", "Accounts are disabled on the HR termination date (PCI DSS Req. 8.2.5).", "Per event · Manual · Preventive"],
      "UAR-01": ["Access review", "Managers certify all directory accounts, including seasonal staff and service accounts, every six months. Revocations are completed within 5 business days.", "Semiannual · Manual · Detective"],
      "VEN-01": ["Service provider oversight", "PCI attestations for service providers are reviewed each year, including the services assessed, the responsibility matrix and Sunset's own responsibilities.", "Annual · Manual · Detective"],
    },
  },
});
