// Meridian Aerospace's CMMC audit desk: access controls tested ahead of the CMMC Level 2
// certification assessment (32 CFR 170). Requirements cite NIST SP 800-171 Rev. 2.
import { PROV_OPTS, TERM_OPTS, G4, rowKit } from "../../engine/grcKit.js";
import { ROLES, buildUsers } from "./company";

const { J, X, RR } = rowKit(ROLES);
// The directory as the review population: employees, contractors and service accounts.
const people = Object.values(buildUsers());
const contractors = people.filter(u => u.type === "Contractor").length;
const service = people.filter(u => u.type === "Service").length;
const staff = people.length - contractors - service;

export const G = [
 {id:"G1",ctrl:"APD-01",title:"Test new user provisioning",kind:"table",opts:PROV_OPTS,
  intro:"<p><b>APD-01:</b> Access for new employees is approved by the manager <i>before</i> provisioning and limited to the role's birthright groups (NIST SP 800-171 3.1.1, 3.1.5).</p><p>Test the 15 sampled Q3 joiners. Compare approval date to provisioned date, and groups granted to the access matrix (Policy &amp; matrix tab). Pre-hire accounts are created disabled before the start date; that's normal.</p>",
  rows:[J("Aiden Castellano","Manufacturing|Machinist","Mon, Jul 6","Raymond Cho, Jul 1","Jul 2",null,0),
   J("Bianca Lowery","Engineering|Design Engineer","Mon, Jul 13","Gabriel Fontaine, Jul 8","Jul 9",null,0),
   J("Corey Whitfield","Manufacturing|Machinist","Mon, Jul 20","Raymond Cho, Jul 14","Jul 15",null,0),
   J("Della Brannigan","Supply Chain|Buyer","Mon, Jul 20","None on file","Jul 16",null,1),
   J("Emil Strand","Quality|Quality Inspector","Mon, Jul 27","Delia Marquez, Jul 21","Jul 22",null,0),
   J("Fallon Reyes","Engineering|Manufacturing Engineer","Mon, Aug 3","Gabriel Fontaine, Jul 28","Jul 29",null,0),
   J("Garrett Holm","Manufacturing|Machinist","Mon, Aug 3","Raymond Cho, Jul 29","Jul 30",null,0),
   J("Hollis Varga","Supply Chain|Receiving Clerk","Mon, Aug 10","Adaeze Okoro, Aug 4","Aug 5",null,0),
   J("Imogen Clarke","Engineering|Design Engineer","Mon, Aug 17","Gabriel Fontaine, Aug 13","Aug 11",null,2,"Provisioned Aug 11, approved Aug 13."),
   J("Jasper Lindqvist","Manufacturing|Machinist","Mon, Aug 24","Raymond Cho, Aug 18","Aug 19",null,0),
   J("Keira Doyle","Quality|Quality Inspector","Mon, Aug 31","Delia Marquez, Aug 25","Aug 26",null,0),
   J("Leon Abernathy","Manufacturing|Machinist","Tue, Sep 8","Raymond Cho, Sep 1","Sep 2",["APP-QMS-Inspection-Signoff"],3,"Inspection sign-off isn't a Machinist birthright group, and it conflicts with MES operator access."),
   J("Maren Holt","Engineering|Design Engineer","Mon, Sep 14","Gabriel Fontaine, Sep 9","Sep 10",null,0),
   J("Nolan Ashby","Supply Chain|Buyer","Mon, Sep 21","Adaeze Okoro, Sep 15","Sep 16",null,0),
   J("Odette Marsh","Manufacturing|Machinist","Mon, Sep 28","Raymond Cho, Sep 24","Sep 23",null,2,"Provisioned Sep 23, approved Sep 24.")],
  lesson:"Test both halves of the control: approval before access, and access limited to the role. 4 of 15 failed (27%), so APD-01 is not operating effectively, and 3.1.1 and 3.1.5 would be scored NOT MET in the assessment."},
 {id:"G2",ctrl:"APD-02",title:"Test timely terminations",kind:"table",opts:TERM_OPTS,
  intro:"<p><b>APD-02:</b> Accounts are disabled within <b>one business day</b> of the HR separation date (NIST SP 800-171 3.9.2, protect CUI during and after terminations).</p><p>Test the 12 sampled Q3 separations from the Oct 2 directory extract. Weekends don't count as business days.</p>",
  rows:[X("Preston Gale","Machinist","Wed, Jul 8","Wed, Jul 8","Jul 7",0),
   X("Quinn Albright","Buyer","Fri, Jul 10","Mon, Jul 13","Jul 10",0,"Friday to Monday is one business day."),
   X("Rhea Donnelly","Quality Inspector","Thu, Jul 16","Thu, Jul 16","Jul 16",0),
   X("Silas Thorne","Machinist","Tue, Jul 21","Tue, Jul 28","Jul 20",1,"Five business days late; no sign-in after separation."),
   X("Tamsin Reed","Receiving Clerk","Fri, Jul 31","Fri, Jul 31","Jul 30",0),
   X("Ulric Brandt","Design Engineer","Mon, Aug 3","Fri, Aug 14","Aug 7",2,"Downloaded drawings from PLM on Aug 7, four days after separation."),
   X("Vera Kincaid","Machinist","Fri, Aug 14","Wed, Aug 26","Aug 21",2,"Signed in to timekeeping a week after separation."),
   X("Wyatt Sorensen","Manufacturing Engineer","Fri, Aug 21","Mon, Aug 24","Aug 20",0,"Friday to Monday is one business day."),
   X("Xavier Dunn","Design Engineer","Tue, Sep 1","Tue, Sep 1","Aug 31",0),
   X("Yvette Harlan","Buyer","Thu, Sep 10","Thu, Sep 10","Sep 10",0),
   X("Curtis Langley","Machinist","Tue, Sep 29","Not disabled","Oct 1",3,"Still enabled at extract and signing in. This is the same account from IAM Ops ticket INC0061333."),
   X("Zelda Fairbanks","Quality Inspector","Wed, Sep 30","Thu, Oct 1","Sep 30",0,"Next business day is within policy.")],
  lesson:"Measure against the policy exactly: Friday to Monday passes. Keep \"late\" separate from \"late and used\". At a defense supplier, use after separation can mean CUI or export-controlled data left with someone who no longer works here."},
 {id:"G3",ctrl:"APD-02",title:"Evaluate the termination exceptions",kind:"quiz",
  intro:"<p>Your APD-02 test found 4 exceptions in 12 samples. Additional facts from follow-up:</p><ul><li>Silas Thorne (Machinist) kept MES access for 5 extra business days. Logs show no activity after separation.</li><li>Ulric Brandt downloaded 14 drawings marked CUI from PLM on Aug 7, four days after separation. Nobody reported it at the time.</li><li>Vera Kincaid's account signed in to timekeeping on Aug 21. Timekeeping holds no CUI.</li><li>Curtis Langley's account is still active and signed in on Oct 1.</li></ul><p>Definitions are on the Controls tab.</p>",
  qs:[{q:"Is APD-02 operating effectively for Q3?",short:"Effectiveness conclusion",opts:["Yes: 8 of 12 passed","No: 4 of 12 (33%) failed, which is well above a tolerable rate for a per-event control"],correct:1,pts:2},
   {q:"Ulric Brandt downloaded CUI drawings after he left. What happens with that?",short:"CUI accessed after separation",opts:["Document it in the finding only","Send it to Security now as a cyber incident affecting covered defense information. The 72-hour DFARS 7012 report runs from discovery, which is today, and the related logs need to be preserved.","Ask Ulric to delete the files, and close it if he confirms"],correct:1,pts:3},
   {q:"Vera Kincaid's account was used after she left, but timekeeping holds no CUI. How do you treat it?",short:"Use without CUI access",opts:["No issue, because no CUI was involved","Refer it to Security as a security incident, confirm the account is disabled, and include it in the finding","Wait for the next quarterly access review"],correct:1,pts:3}],
  lesson:"For a defense supplier, a failed termination control isn't only an audit exception. CUI reached after someone leaves is a reportable cyber incident with a 72-hour clock, and any use after separation is a security incident."},
 G4,
 {id:"G5",ctrl:"UAR-01",title:"Review the Q3 access review for completeness",kind:"quiz",
  intro:"<p><b>UAR-01:</b> Each quarter, managers certify <i>all</i> directory accounts (employees, contractors, service accounts). Revocations are completed within 5 business days. This supports NIST SP 800-171 3.1.1 and 3.1.5.</p>",
  evidence:[["Directory extract, Sep 30",`${people.length} accounts: ${staff} employees, ${contractors} contractors, ${service} service accounts`],["Access review file",`${staff} accounts, all certified by managers`],["Reviewer sign-off","Kenji Watanabe, Oct 1"],["Population source","Excel export provided by IT; no query or run parameters attached"]],
  qs:[{q:"What is the main issue?",short:"Issue identified",opts:[`Completeness: the ${contractors} contractors and ${service} service accounts were left out of the review`,"Timeliness: sign-off came after quarter end","Accuracy: managers certified too quickly","No issue"],correct:0,pts:3},
   {q:"What evidence do you request? Select all that apply.",multi:true,opts:["A system-generated population with the query, parameters and run date",`Review evidence for the ${contractors + service} excluded accounts`,"An email from IT confirming the review was complete","Re-perform the whole review yourself"],correct:[0,1]},
   {q:"Until those accounts are reviewed, can UAR-01 be relied on to catch the access APD-02 missed?",short:"Reliance on UAR-01",opts:["Yes","No"],correct:1,pts:2}],
  lesson:"Before testing a review, test the population. Contractors and service accounts are the usual gaps, and Meridian's engineering contractors hold CUI access."},
 {id:"G6",ctrl:"RISK",title:"Rate the CUI risk register",kind:"table",opts:["High","Medium","Low"],
  intro:"<p>NIST SP 800-171 3.11.1 calls for periodic risk assessments of the systems that handle CUI. Rate each risk's inherent level. Score = likelihood × impact. <b>High</b> 15–25, <b>Medium</b> 8–14, <b>Low</b> 1–7.</p><p class=\"mono\" style=\"font-size:12px\">Likelihood: Rare 1 · Unlikely 2 · Possible 3 · Likely 4 · Almost certain 5<br>Impact: Minimal 1 · Minor 2 · Moderate 3 · Major 4 · Severe 5</p>",
  rows:[RR("R-01 Former employees keep CUI access","APD-02 failures; 2 accounts used after separation","Likely","Severe",0),
   RR("R-02 Shared shop-floor terminal login","Requested by Manufacturing","Possible","Moderate",1),
   RR("R-03 Domain admin on everyday accounts","A sysadmin also holds security log admin","Possible","Severe",0),
   RR("R-04 Cloud provider evidence gap","FedRAMP equivalency evidence is from Feb 2025","Unlikely","Moderate",2),
   RR("R-05 Foreign-person access to ITAR data","U.S.-person checks are manual","Unlikely","Severe",1)],
  lesson:"Apply the matrix the same way every time. R-01 (20) and R-03 (15) lead the plan of action and milestones (POA&M). R-05 is only 10, but because ITAR violations carry their own penalties, it's worth a note to the risk owner."},
 {id:"G7",ctrl:"VEN-01",title:"Review the cloud provider's FedRAMP evidence",kind:"quiz",
  intro:"<p>Skyforge GovCloud hosts Meridian's email and, since this year, the engineering file vaults. Both hold CUI. DFARS 252.204-7012 requires a cloud provider that stores CUI to meet security requirements equivalent to the FedRAMP Moderate baseline.</p>",
  evidence:[["Authorization","FedRAMP Moderate equivalency, assessed by an accredited third-party assessment organization (3PAO)"],["Assessment date","Feb 2025"],["Open plan of action items","2, both rated low"],["Customer responsibility matrix","42 requirements are Meridian's, including account management (3.1.1), MFA settings (3.5.3) and audit log review (3.3.1)"],["Incident reporting","Provider agrees to report cyber incidents to Meridian and the DoD per 252.204-7012(c) to (g)"],["Contract scope","Signed 2023 for email only. Engineering moved the file vaults to the platform in Mar 2026."]],
  qs:[{q:"Which follow-ups are needed? Select all that apply.",multi:true,opts:["Ask for evidence the 2 open plan of action items are closed; DoD's equivalency standard expects the Moderate baseline to be fully met","Confirm Meridian's own requirements in the customer responsibility matrix are operating","Update the contract so it covers the file vaults, with the 7012 terms","Ask for current evidence, since the assessment is more than a year old","Drop the provider because it has open items","Run our own penetration test of the provider's platform","No action needed; it's FedRAMP equivalent"],correct:[0,1,2,3]},
   {q:"Why does your APD-02 result matter for this review?",short:"Link to APD-02",opts:["It doesn't; the provider manages the platform","Account management is Meridian's responsibility in the matrix. Late terminations mean a customer-side requirement is failing, whatever the provider's status.","It means the provider's equivalency should be withdrawn"],correct:1,pts:3}],
  lesson:"A provider's authorization covers its half. Check that the evidence is current and complete, that the contract covers what the provider actually holds, and that your own half of the responsibility matrix is working."},
 {id:"G8",ctrl:"POL-EX",title:"Decide a policy exception request",kind:"quiz",
  intro:"<p>After IAM Ops rejected the shared <span class=\"mono\">cnc-cell-4</span> login, Manufacturing filed a formal policy exception: \"Three shifts lose ten minutes every changeover to terminal sign-ins. Badge-tap sign-in is budgeted for Q2 2027.\"</p>",
  qs:[{q:"What is the decision?",short:"Exception decision",opts:["Deny outright; policy is policy","Approve as asked: one shared login for the terminal and the MES","Approve temporarily for the terminal sign-in only, with every machinist still signing in to the MES and PLM individually, compensating controls and risk owner sign-off"],correct:2,pts:3},
   {q:"Which conditions belong in the approval? Select all that apply.",multi:true,opts:["The shared login opens the terminal only; every MES and PLM session uses the machinist's own account","Expiry of 90 days or less, with re-review","Short idle lock on the terminal","Sign-off by the risk owner (Catherine Aldous, President)","Tracked project to replace it with badge-tap sign-in, listed on the POA&M","Let the shared login open the MES too, to save time","Write the password on the machine guard for night shift"],correct:[0,1,2,3,4]}],
  lesson:"GRC's job is managed risk, not saying no. NIST SP 800-171 3.5.1 and 3.3.2 require actions to be traceable to individual users, so the exception can't reach the systems that hold CUI. Keep it narrow, time-limited, compensated and owned by the business."},
 {id:"G9",ctrl:"MAP",title:"Map APD-02 to frameworks",kind:"quiz",
  intro:"<p>Map APD-02 (disable accounts within one business day of separation) so one test can answer several reviews.</p>",
  qs:[{q:"Select every requirement APD-02 supports.",multi:true,opts:["NIST SP 800-171 3.9.2 Personnel actions (CMMC PS.L2-3.9.2)","NIST SP 800-171 3.1.1 Authorized access control (CMMC AC.L2-3.1.1)","NIST 800-53 PS-4 Personnel Termination","NIST 800-53 AC-2 Account Management","ISO 27001:2022 A.5.18 Access rights","NIST SP 800-171 3.8.3 Media sanitization","NIST SP 800-171 3.5.3 Multifactor authentication","NIST 800-53 CP-9 System Backup","ISO 27001:2022 A.8.13 Information backup"],correct:[0,1,2,3,4]}],
  lesson:"Test once, satisfy many. A mapped control lets one set of APD-02 evidence answer the CMMC assessment, a prime contractor's questionnaire and an ISO audit."},
 {id:"G10",ctrl:"APD-02",title:"Write the termination finding",kind:"quiz",
  intro:"<p>Build the APD-02 finding. Pick the strongest statement for each element.</p>",
  qs:[{q:"Condition",short:"Condition",opts:["Access was removed late for some staff.","4 of 12 sampled separations (33%) were not disabled within one business day. One account was still active at extract, and three former employees used their accounts after leaving, one to download CUI drawings.","IT doesn't take separations seriously."],correct:1,pts:2},
   {q:"Criteria",short:"Criteria",opts:["The Personnel Actions policy requires accounts to be disabled within one business day of the HR separation date (control APD-02), implementing NIST SP 800-171 3.9.2, a CMMC Level 2 requirement.","Best practice says access should be removed quickly.","CMMC requires same-day removal."],correct:0,pts:2},
   {q:"Cause",short:"Cause",opts:["The service desk was careless.","Unknown.","Separations are processed by hand from HR emails. There is no automated HR-to-directory trigger or daily reconciliation."],correct:2,pts:2},
   {q:"Effect",short:"Effect",opts:["Meridian will lose all its contracts.","Former employees could reach CUI after leaving, and one did (14 drawings, now reported to the DoD). 3.9.2 would be scored NOT MET, lowering the SPRS score and putting certification at risk.","No impact, because nothing was stolen."],correct:1,pts:2},
   {q:"Recommendation",short:"Recommendation",opts:["Automate deprovisioning from the HR separation event, and add a daily HR-to-directory reconciliation with exceptions reviewed by the IT Manager.","Remind the service desk to be faster.","Remove all users' access every quarter."],correct:0,pts:2}],
  lesson:"A finding that holds up is specific (numbers), cites the actual requirement, names a fixable cause, states real impact without exaggeration, and recommends a fix that addresses the cause."}
];
