// Meridian Aerospace's PAM shift. The kit (lib/pamKit.js) supplies grading, hints, the playbook
// and the PAM runbook; this file is the story. Lessons cite NIST SP 800-171 Rev. 2 (the CMMC
// Level 2 requirements).
import { buildPam } from "../lib/pamKit.js";
import * as company from "./company";
import * as policy from "./policy";

const n171 = id => ({ label: `NIST SP 800-171 Rev. 2, ${id}`, href: "https://csrc.nist.gov/pubs/sp/800/171/r2/upd1/final" });
const ADMIN = "IT|Systems Administrator", STAFF = ["GRP-All-Staff", "APP-Office-Suite-Gov", "APP-Service-Desk"];

export const pam = buildPam({
  id: "meridian",
  eligible: { [ADMIN]: ["ROLE-Domain-Admin"], "IT|Security Analyst": ["ROLE-Security-Log-Admin"], "IT|IT Manager": ["ROLE-User-Admin"], "Vendors|MES Vendor Support": ["ROLE-MES-Server-Admin"] },
  also: ["ROLE-Global-Admin"],
  roles: { "Vendors|MES Vendor Support": ["GRP-Contractors"] },
  cast: [
    ["lucas.ferreira", "Lucas Ferreira", "MA-40181", ADMIN, "Kenji Watanabe"],
    ["hugo.lindqvist", "Hugo Lindqvist", "MA-40183", ADMIN, "Kenji Watanabe", { groups: [...STAFF, "ROLE-Domain-Admin"] }],
    ["farah.siddiqui", "Farah Siddiqui", "MA-40185", "IT|Security Analyst", "Kenji Watanabe", { groups: [...STAFF, "ROLE-Domain-Admin"] }],
    ["greta.holm", "Greta Holm", "MA-40187", ADMIN, "Kenji Watanabe"],
    ["oskar.brandt", "Oskar Brandt", "MA-40189", ADMIN, "Kenji Watanabe", { groups: [...STAFF, "ROLE-Domain-Admin"], jit: { "ROLE-Domain-Admin": 2 } }],
    ["owen.mcbride", "Owen McBride", "MA-40191", "IT|Service Desk Technician", "Kenji Watanabe"],
    ["stefan.albrecht", "Stefan Albrecht", "MA-V-0091", "Vendors|MES Vendor Support", "Raymond Cho (sponsor)", { type: "Contractor", enabled: false, expiry: 180, last: 34 }],
    ["bg-admin-01", "bg-admin-01", "BG-01", null, "Kenji Watanabe (owner)", { dept: "IT", title: "Break-glass account: emergency Global Admin", type: "Break-glass", groups: ["ROLE-Global-Admin"], enabled: false, mfa: false, last: 212 }],
  ],
  cite: { "pam-jit": [n171("3.1.5"), n171("3.1.7")], "pam-eligible": [n171("3.1.5"), n171("3.1.6")], "pam-breakglass": [n171("3.1.5"), n171("3.6.1")],
    "pam-vault": [n171("3.5.10")], "pam-session": [n171("3.1.7"), n171("3.3.2")], "pam-vendor": [n171("3.1.12"), n171("3.1.15")], "pam-shared": [n171("3.3.2"), n171("3.5.1")] },
  mon: {
    jit: { id: "REQ0035101", uid: "lucas.ferreira", group: "ROLE-Domain-Admin", hours: 2, change: "CHG0031877", approver: "Hollis Grant",
      what: "install this month's security patches on the domain controllers", from: "Lucas Ferreira", channel: "Portal", opened: "6:45 AM",
      lesson: "Activate an eligible role for the approved window only, with the approval on the ticket first. NIST SP 800-171 3.1.5 (least privilege, including privileged accounts)." },
    breakGlass: { id: "INC0062101", uid: "kenji.watanabe", bg: "bg-admin-01", title: "Emergency: admins locked out, need break-glass", from: "Kenji Watanabe", channel: "Phone", opened: "7:12 AM",
      body: "<p>\"It's Kenji. The identity provider's MFA service is down company-wide and none of the admins can sign in to the domain controllers. If the MES sync isn't fixed before shift change, the five-axis cell stops. I'm declaring an emergency. I need bg-admin-01 enabled now.\"</p>",
      lesson: "Break-glass access is real admin power with no MFA in front of it. Verify the caller, enable only the documented account, and tell Security immediately. NIST SP 800-171 3.6.1 (incident handling)." },
    notEligible: { id: "REQ0035104", uid: "owen.mcbride", group: "ROLE-Domain-Admin", title: "Domain Admin for the service desk", from: "Owen McBride", channel: "Portal", opened: "7:30 AM",
      body: "<p>The shop-floor terminals keep losing their group policy and the sysadmins are swamped. If I had Domain Admin I could fix them myself between calls. Kenji's approved it.</p>",
      alt: "explain that Service Desk Technicians aren't eligible for ROLE-Domain-Admin. The terminal fix goes to a Systems Administrator under a change.",
      lesson: "Eligibility for a privileged role comes from the job. A manager's approval can't add a role the job doesn't include. NIST SP 800-171 3.1.5 and 3.1.6." },
    rotate: { id: "REQ0035107", svc: "svc-mes", down: "The MES to ERP work-order sync", title: "svc-mes password posted in a chat channel", from: "Lena Hartmann", channel: "Portal", opened: "7:41 AM",
      body: "<p>While troubleshooting this morning, one of the engineers pasted the full svc-mes connection string, password included, into the #mes-support chat channel. There are 46 people in that channel, including two contractors.</p><p>Please deal with the exposed password. The MES integration has to keep running: the line is mid-shift.</p>",
      lesson: "An exposed service credential is rotated, not disabled. Production keeps running and the leaked password stops working. NIST SP 800-171 3.5.10 (protect passwords)." },
    standing: { id: "TSK0010101", holders: [["hugo.lindqvist", "ROLE-Domain-Admin"], ["farah.siddiqui", "ROLE-Domain-Admin"]], bg: "bg-admin-01", bgGroup: "ROLE-Global-Admin",
      title: "PAM report: standing privileged memberships", from: "PAM vault (weekly report)", channel: "Automated", opened: "8:00 AM",
      body: "<p>These accounts hold a vaulted role permanently instead of activating it:</p><ul><li><span class=\"mono\">hugo.lindqvist</span>: ROLE-Domain-Admin (since migration)</li><li><span class=\"mono\">farah.siddiqui</span>: ROLE-Domain-Admin (added during an investigation in June)</li><li><span class=\"mono\">bg-admin-01</span>: ROLE-Global-Admin</li></ul><p>Clean up the standing access per the PAM runbook.</p>",
      lesson: "Standing admin access is the gap PAM exists to close. Remove it, except where the runbook documents an exception. NIST SP 800-171 3.1.5." },
    adminLeaver: { id: "REQ0035110", uid: "dmitri.volkov", svc: "svc-nas-backup", title: "Termination: Dmitri Volkov, Systems Administrator", from: "HR system (automated)", channel: "HR integration", opened: "8:20 AM",
      body: "<p>Involuntary termination, effective 9:00 AM today. Remove all access before the meeting.</p><p>PAM vault note: Dmitri checked out the <span class=\"mono\">svc-nas-backup</span> password on Tuesday and it hasn't been rotated since.</p>",
      lesson: "An admin leaver's access ends only when what they knew stops working: rotate any credential they checked out. NIST SP 800-171 3.9.2 (protect CUI systems during terminations)." },
    vendor: { id: "REQ0035113", uid: "stefan.albrecht", group: "ROLE-MES-Server-Admin", hours: 3, title: "Vendor support session: MES hotfix", from: "Raymond Cho", channel: "Portal", opened: "8:35 AM",
      body: "<p>Stefan from our MES vendor needs admin on the MES application servers to install a hotfix for the work-order queue bug. The session is booked from 9:00 AM to 12:00 PM, so three hours. His account is off until we need it.</p>",
      lesson: "Vendor access is opened for one approved session: sponsor approval, the account enabled, the role for the session only. NIST SP 800-171 3.1.12 (monitor and control remote access)." },
    noChange: { id: "REQ0035116", uid: "greta.holm", group: "ROLE-Domain-Admin", target: "The engineering file server", title: "Domain Admin for the weekend", from: "Greta Holm", channel: "Portal", opened: "9:05 AM",
      body: "<p>I'd like to clear out the old project shares on the engineering file server over the weekend while it's quiet. Can you activate Domain Admin for me from Friday evening to Sunday night, say 48 hours? No change record yet, it's just housekeeping.</p>",
      alt: "explain that eligibility isn't enough: the work needs an approved change, and activations are capped at 4 hours.",
      lesson: "Eligible isn't approved. Privileged roles are activated for an approved change, for a short window. NIST SP 800-171 3.1.5 and 3.1.7." },
    session: { id: "REQ0035119", title: "Weekly privileged session review", from: "Security team", channel: "Email", opened: "9:30 AM",
      intro: "<p>Yesterday's recorded admin sessions are below. Check each one against the change or incident it was opened for, and send us the IDs of any session that went outside it.</p>",
      rows: [
        ["PSM-20417", "hugo.lindqvist", "CHG0031812: replace a failed disk", "FS-ENG-02", "Swapped the disk, checked the RAID rebuild", false],
        ["PSM-20422", "greta.holm", "CHG0031820: patch the PLM servers", "PLM-APP-01", "Installed patches, rebooted, <b>copied the CUI drawing archive to a personal cloud folder</b>", true],
        ["PSM-20431", "farah.siddiqui", "INC0062050: investigate failed sign-ins", "DC-01", "Read security event logs, exported two hours of sign-in events to the incident", false],
        ["PSM-20438", "hugo.lindqvist", "CHG0031825: add a shop-floor print queue", "PRN-01", "Added the print queue, <b>created a local admin account called support2</b>", true],
        ["PSM-20440", "lucas.ferreira", "CHG0031826: renew the web certificate", "WEB-01", "Imported the new certificate, restarted the web service", false],
      ],
      lesson: "A recorded session only protects you if someone compares it with the reason it was opened. NIST SP 800-171 3.1.7 (log privileged functions) and 3.3.2 (trace actions to users)." },
    compromised: { id: "INC0062104", uid: "oskar.brandt", group: "ROLE-Domain-Admin", title: "SIEM alert: admin sign-in from abroad", from: "SIEM alert", channel: "Automated", opened: "9:48 AM",
      body: "<p>At 6:02 AM <span class=\"mono\">oskar.brandt</span> approved an MFA prompt after 31 push requests, signed in from an IP address in Romania, and activated ROLE-Domain-Admin for 2 hours. Oskar is at home in Wichita and says he approved a prompt to make the phone stop buzzing.</p>",
      lesson: "A compromised admin account is contained when the attacker has nothing left: no session, password, MFA method or privileged role. Then Security takes it. NIST SP 800-171 3.6.1." },
    shared: { id: "REQ0035122", uid: "brianna.cole", title: "Admin password for the night shift", from: "Brianna Cole", channel: "Portal", opened: "10:05 AM",
      body: "<p>There's no admin on site at night and the night desk keeps getting stuck. Could we put the domain admin password in the night shift's OneNote, or make a shared <span class=\"mono\">nightadmin</span> login they can all use?</p>",
      alt: "explain that admin passwords are never shared. Night-shift admins check credentials out of the vault under their own accounts, and urgent work goes to the on-call Systems Administrator.",
      lesson: "Shared admin credentials make every change anonymous and can't be taken back from one person. NIST SP 800-171 3.3.2 (actions traceable to individual users)." },
    auditQ: { id: "REQ0035125", group: "ROLE-Domain-Admin", title: "Assessor request: who holds Domain Admin", from: "Internal audit (CMMC readiness)", channel: "Email", opened: "10:20 AM",
      body: "<p>For the CMMC readiness assessment, please list every enabled account that holds <span class=\"mono\">ROLE-Domain-Admin</span> right now, including any just-in-time activations that are still running. Usernames are fine.</p>",
      lesson: "Audit evidence is pulled from the system as it stands. NIST SP 800-171 3.1.5 and 3.3.1 (system audit records)." },
  },
  thu: {
    bgClose: { id: "TSK0010104", from: "Kenji Watanabe", channel: "Portal", opened: "10:40 AM",
      body: "<p>The identity provider is back and the admins can sign in normally. I declared the emergency over at 10:35 AM. Please close out bg-admin-01 per the break-glass procedure.</p>",
      lesson: "Break-glass is closed as deliberately as it's opened: disabled, rotated and signed out. NIST SP 800-171 3.1.5." },
    vendorEnd: { id: "TSK0010107", from: "Raymond Cho", channel: "Portal", opened: "11:15 AM",
      body: "<p>Stefan finished the hotfix early and the work-order queue is clearing. Please close his access.</p>",
      lesson: "Third-party access ends with the session. NIST SP 800-171 3.1.12." },
  },
  conseq: {
    standingJit: { id: "INC0062110", from: "PAM vault", channel: "Automated", opened: "Afternoon" },
    notEligible: { id: "INC0062113", from: "Security team", channel: "Email", opened: "Afternoon" },
    svcDown: { id: "INC0062116", from: "Lena Hartmann", channel: "Phone", opened: "Afternoon" },
    svcLeak: { id: "INC0062119", from: "SIEM alert", channel: "Automated", opened: "Afternoon" },
    leaver: { id: "INC0062122", from: "Security team", channel: "Email", opened: "Afternoon" },
    noChange: { id: "INC0062125", from: "Security team", channel: "Email", opened: "Afternoon" },
    compromised: { id: "INC0062128", from: "SIEM alert", channel: "Automated", opened: "Afternoon" },
    bgOpen: { id: "INC0062131", from: "PAM vault", channel: "Automated", opened: "Afternoon" },
    vendorOpen: { id: "INC0062134", from: "Security team", channel: "Email", opened: "Afternoon" },
  },
}, company, policy);
