// Meridian Aerospace's shift on the service desk. The kit (lib/ticketKit.js) supplies grading,
// hints, the playbook and Jordan Reyes' shift; this file is the story. Lessons cite NIST SP 800-171
// Rev. 2 (the CMMC Level 2 requirements) and DFARS 252.204-7012.
import { buildTicketSet } from "../lib/ticketKit.js";
import { ROLES, SOD, buildUsers } from "./company";
import { G } from "./grc.js";

const m = x => `<span class="mono">${x}</span>`;

export const set = buildTicketSet({
  id: "meridian", ROLES, SOD, buildUsers,
  mon: {
    joiner: { id: "REQ0034104", uid: "felix.moreau", rk: "Manufacturing|Machinist", title: "New hire: Felix Moreau, Machinist",
      from: "HR system (automated)", channel: "HR integration", opened: "6:10 AM",
      body: "<p>New hire starting today on first shift in the five-axis cell. The pre-hire account was created by the HR sync but is disabled with no access.</p><p>Please activate the account and provision access for the role. CUI training is on file. His shift starts at 7:00 AM.</p>",
      lesson: "Provision from the role in the access matrix, nothing more. NIST SP 800-171 3.1.1 (limit system access to authorized users) and 3.9.1 (screen before CUI access)." },
    callerPw: { id: "INC0061311", uid: "bernadette.quigley", title: "Forgot password after vacation",
      from: "Bernadette Quigley", channel: "Phone", opened: "7:38 AM",
      body: "<p>\"Morning. I just got back from a week at the lake and my password expired while I was out. I tried a couple of new ones and now I can't remember which took. Can you reset it? I've got first-article inspections waiting.\"</p>",
      lesson: "Verify identity against the system of record before any credential reset. NIST SP 800-171 3.5.2 (authenticate users before allowing access)." },
    callerLock: { id: "INC0061314", uid: "wendell.haskins", title: "Locked out at the shop floor terminal",
      from: "Wendell Haskins", channel: "Phone", opened: "7:49 AM",
      body: "<p>\"The terminal at my cell kept rejecting me, so I typed my password a few too many times and now it says locked. I know my password, my gloves just kept hitting the wrong keys. The job's waiting on the machine.\"</p>",
      lesson: "A lockout is not a forgotten password. Unlock only after verifying who's calling; a reset adds risk and slows the floor for no reason. NIST SP 800-171 3.1.8." },
    callerMfa: { id: "INC0061318", uid: "fiona.galbraith", title: "Phone stolen at the airport, can't sign in",
      from: "Fiona Galbraith", channel: "Phone (desk line)", opened: "7:58 AM",
      body: "<p>\"My phone was stolen at the airport on the way back from the customer's site Friday. The authenticator was on it. I've got a new phone, but I can't sign in to anything, and I owe the prime a program review deck by noon.\"</p>",
      lesson: "Clear the stolen authenticator and end any sessions the phone may still hold. NIST SP 800-171 3.5.3 (MFA), 3.5.2." },
    leaver: { id: "REQ0034112", uid: "dmitri.volkov", title: "Termination: Dmitri Volkov, effective 9:00 AM",
      from: "Rosalind Pryce (HR Manager)", channel: "HR integration", opened: "8:06 AM",
      body: "<p>Involuntary termination effective today at 9:00 AM. Dmitri holds domain administrator rights. Remove all access per the leaver policy before he is told.</p>",
      lesson: "Leavers: disable, revoke sessions, remove all access, and do it before an administrator is told. NIST SP 800-171 3.9.2 (protect CUI during and after terminations)." },
    mover: { id: "REQ0034115", uid: "nadia.farouk", fromRk: "Quality|Quality Inspector", toRk: "Engineering|Manufacturing Engineer",
      title: "Transfer: Nadia Farouk, Quality to Engineering", from: "HR system (automated)", channel: "HR integration", opened: "8:13 AM",
      body: "<p>Nadia Farouk is moving from Quality Inspector to Manufacturing Engineer (Engineering), effective today. New manager: Gabriel Fontaine. Update her job info and access.</p>",
      lesson: "Movers are where privilege creep starts. Remove the old role's access, not just add the new. An engineer who can still sign off inspections can approve her own process changes. NIST SP 800-171 3.9.2, 3.1.5." },
    sodReq: { id: "REQ0034119", uid: "cyrus.pennington", group: "APP-ERP-Purchasing", holds: "APP-ERP-Receiving",
      title: "Access request: purchasing for Cyrus Pennington", from: "Cyrus Pennington", channel: "Self-service portal", opened: "8:21 AM",
      approval: "Adaeze Okoro replied: \"Approved. He can raise the small consumables POs himself instead of waiting on the buyers.\"",
      alt: "suggest the buyers set up a blanket purchase order for shop consumables, so receiving never has to raise its own orders.",
      body: `<p>Requesting ${m("APP-ERP-Purchasing")} so I can order cutting tools and coolant myself when we run low on second shift.</p>`,
      lesson: "Manager approval doesn't override separation of duties. The person who confirms goods arrived must never be the person who ordered them. NIST SP 800-171 3.1.4." },
    request: { id: "REQ0034123", uid: "lena.hartmann", group: "GRP-ITAR-Technical-Data", approver: "Gabriel",
      title: "Access request: ITAR technical data", from: "Lena Hartmann", channel: "Self-service portal", opened: "8:27 AM",
      approval: "Gabriel Fontaine replied: \"Approved. Lena is writing the routings for the new pylon fittings. Sharon confirmed her U.S.-person status in writing this morning; it's attached.\"",
      body: `<p>Requesting ${m("GRP-ITAR-Technical-Data")} to read the export-controlled drawings for the new pylon fitting job I'm writing routings for.</p>`,
      lesson: "Requestable access needs its documented approvals before it's granted, and only what was asked. For ITAR data that includes the Facility Security Officer's written U.S.-person confirmation. NIST SP 800-171 3.1.1; ITAR, 22 CFR 120 to 130." },
    exec: { id: "INC0061326", uid: "desmond.achebe", saidEmpId: "MA-40060", title: "URGENT: CFO locked out before a supplier payment",
      from: "Caller says: Desmond Achebe (CFO)", channel: "Phone (unknown mobile number)", opened: "8:33 AM",
      body: "<p>\"This is Desmond Achebe. I'm at the defense industry conference in Washington and my phone died. I'm on a colleague's. Move my MFA to this number right now. If the titanium supplier isn't paid by 9, they hold our material and the line stops.\"</p>",
      lesson: "Urgency plus authority plus a new device is the classic social-engineering pattern. Check the details, refuse, and report it. NIST SP 800-171 3.5.2, 3.6.1." },
    contractor: { id: "REQ0034127", uid: "ivan.petrenko", title: "Extend contractor: Ivan Petrenko",
      from: "Gabriel Fontaine (sponsor)", channel: "Email", opened: "8:40 AM",
      approval: "Gabriel Fontaine (sponsor) replied: \"Approved. His statement of work was renewed through the end of the year, with the CUI flow-down clauses.\"",
      body: "<p>Ivan's statement of work was renewed. His account expires in 2 days. Please extend it so he can keep working on the stress analysis.</p>",
      lesson: "Contractor accounts always have an end date and a sponsor approval, capped at 90 days per extension. NIST SP 800-171 3.1.1, 3.9.2." },
    sweep: { id: "TSK0011208", dormant: [["walter.kessler", 143], ["irene.papadakis", 92]], under: ["lorna.breckenridge", 89], svc: "svc-nas-backup",
      title: "Weekly: disable inactive accounts", from: "Scheduled report", channel: "Automated task", opened: "8:46 AM",
      body: "<p>Weekly inactive-account sweep. Per policy, disable any user account with no sign-in for more than 90 days. Pre-hire accounts are excluded.</p><p>Use the Directory's sort by last sign-in.</p>",
      lesson: "Dormant accounts with CUI access are a favorite target. Apply the threshold exactly, and send service accounts to their owner instead of breaking a production job. NIST SP 800-171 3.5.6." },
    recon: { id: "INC0061333", uid: "curtis.langley", left: "Sep 29", signedIn: "Saturday",
      title: "HR reconciliation: former machinist still active", from: "HR-to-directory reconciliation report", channel: "Automated report", opened: "8:54 AM",
      body: "<p>The weekly HR reconciliation found an account that is still enabled for a person HR shows as separated. Check the HR feed and the account's last sign-in.</p>",
      lesson: "A former employee who can still reach CUI is a security incident, and possibly a reportable one. Contain it, then report it. NIST SP 800-171 3.9.2, 3.6.1." },
    priv: { id: "REQ0034131", uid: "brianna.cole", group: "ROLE-Domain-Admin",
      route: "point Brianna to Kenji Watanabe: domain admin is held only by the systems administrators, on separate admin accounts, and changes go through change control.",
      title: "Need Domain Admin to fix a GPO", from: "Brianna Cole (Service Desk)", channel: "Teams message", opened: "9:02 AM",
      body: "<p>\"Can you put me in Domain Admin for the day? The shop floor printers lost their group policy and the sysadmins are tied up with Dmitri's stuff. Kenji said it's fine.\"</p>",
      lesson: "Domain admin is never granted by ticket. It controls every account and every CUI system. NIST SP 800-171 3.1.5, 3.1.6 (non-privileged accounts for everyday work)." },
    rehire: { id: "REQ0034134", uid: "samuel.ortiz", rk: "Manufacturing|Machinist", pwAge: "9-month",
      title: "Rehire: Samuel Ortiz, Machinist", from: "HR system (automated)", channel: "HR integration", opened: "9:07 AM",
      body: "<p>Rehire starting today. The HR sync matched his existing disabled account. CUI training was renewed last week. Reactivate and provision for the role.</p>",
      lesson: "Rehires carry old access and old passwords. Check access against the role, and issue a fresh credential. NIST SP 800-171 3.9.1, 3.5.2." },
    shared: { id: "REQ0034138", uid: "raymond.cho",
      alt: "offer badge-tap sign-in for the cell terminals so each machinist signs in with a tap.",
      title: "Shared login for the five-axis cell terminal", from: "Raymond Cho (Production Manager)", channel: "Email", opened: "9:13 AM",
      body: `<p>"Can we get one login like ${m("cnc-cell-4")} for the terminal in the five-axis cell? Three shifts share it and they lose ten minutes every changeover signing in and out."</p>`,
      lesson: "Shared accounts destroy accountability: nobody can say who loaded which program or touched which CUI drawing. NIST SP 800-171 3.5.1 (identify users) and 3.3.2 (trace actions to individual users)." },
    review: { id: "REQ0034141", uid: "thaddeus.okonjo", group: "GRP-ITAR-Technical-Data",
      title: "Access review action: remove ITAR technical data", from: "Q3 access review (Gabriel Fontaine)", channel: "Access review", opened: "9:18 AM",
      body: "<p>Q3 user access review result: reviewer Gabriel Fontaine marked <b>Thaddeus Okonjo: GRP-ITAR-Technical-Data</b> as <b>Revoke</b> (\"Moved off the pylon program in August\"). All other entitlements certified.</p>",
      lesson: "A review only counts if the revocations are carried out and evidenced. Remove exactly what the reviewer marked. NIST SP 800-171 3.1.1, 3.1.5." },
    loa: { id: "REQ0034144", uid: "joy.adeleke", title: "Leave of absence: Joy Adeleke",
      from: "HR system (automated)", channel: "HR integration", opened: "9:23 AM",
      body: "<p>Joy Adeleke begins parental leave today. Expected return Jan 11, 2027. Apply the leave of absence policy.</p>",
      lesson: "Leave is not termination. Disable to block use, but keep entitlements so she returns on day one. NIST SP 800-171 3.9.2." },
    copy: { id: "REQ0034147", uid: "amara.nwosu", peer: "marguerite.ellison", rk: "Engineering|Design Engineer", extras: ["APP-MES-Engineering", "APP-Timekeeping-Approve"],
      title: "New hire Amara Nwosu: \"same as Marguerite\"", from: "Gabriel Fontaine (Engineering Manager)", channel: "Email", opened: "9:30 AM",
      body: "<p>\"Amara starts in design engineering today. Just give her whatever Marguerite Ellison has so Marguerite can get her going. Thanks!\"</p>",
      lesson: "Never mirror a peer. Peers carry leftover access, and copying spreads it. Provision from the role, and flag the peer's extras for review. NIST SP 800-171 3.1.5 (least privilege)." },
    auditQ: { id: "REQ0034150", groups: ["APP-MES-Operator", "APP-QMS-Inspection-Signoff"],
      title: "Quality request: operator and inspector conflicts", from: "Delia Marquez (Quality Manager)", channel: "Email", opened: "9:37 AM",
      body: "<p>\"For next week's AS9100 surveillance audit, please list every <b>enabled</b> user who currently holds <b>both</b> APP-MES-Operator and APP-QMS-Inspection-Signoff.\"</p><p>Enter usernames (first.last) separated by commas, or <b>none</b>, in the answer box when you close the ticket.</p>",
      lesson: "Audit evidence must be complete and accurate. Pull it from the system, not from memory. Remediation is a separate, approved change. NIST SP 800-171 3.1.4." },
    compromise: { id: "INC0061342", uid: "harriet.vance", title: "Impossible travel + MFA fatigue: Harriet Vance",
      from: "Identity protection alert", channel: "SIEM alert", opened: "9:45 AM",
      body: "<p>High-risk sign-in. Harriet Vance signed in from Wichita at 9:02 AM and from Bucharest at 9:19 AM. The Bucharest sign-in followed 14 MFA push prompts, one of which was approved.</p><p>Harriet confirmed by desk phone she did not travel and approved a prompt \"to make them stop.\" Her mailbox holds supplier drawings marked CUI.</p>",
      lesson: "Contain first: revoke sessions, rotate the password, re-register MFA, then hand off to Security. CUI was reachable, so Security will need to decide on the DFARS 72-hour report. NIST SP 800-171 3.6.1, 3.6.2." },
  },
  thu: {
    adminReq: { id: "REQ0034182", uid: "gabriel.fontaine", group: "ROLE-Helpdesk-Admin",
      alt: "Password resets go through the service desk, which verifies identity first. Helpdesk admin isn't requestable and isn't part of the Engineering Manager role.",
      jordanNote: "Manager approved so he can reset his team's passwords.",
      title: "Access request: helpdesk admin for Gabriel Fontaine", from: "Gabriel Fontaine", channel: "Self-service portal",
      approval: "Catherine Aldous replied: \"Approved. He shouldn't have to wait on the desk every time an engineer forgets a password.\"",
      body: `<p>Requesting ${m("ROLE-Helpdesk-Admin")} so I can reset passwords and unlock accounts for my engineers without opening tickets.</p>`,
      lesson: "Admin roles aren't requestable, whoever approves. A manager who can reset his team's passwords can also sign in as any of them. NIST SP 800-171 3.1.5, 3.1.7." },
    loaReturn: { id: "REQ0034185", title: "Leave postponed: Joy Adeleke", from: "HR system (automated)", channel: "HR integration",
      body: "<p>Update to REQ0034144: Joy Adeleke's leave start date has moved to next month, so her leave is postponed and she is working today after all. Restore her access so she can work.</p>",
      lesson: "Because leave means disable-and-keep, a return is one click. If her groups were removed when her leave was processed, you're rebuilding access from the matrix now. NIST SP 800-171 3.9.2." },
  },
  conseq: {
    stale: { id: "INC0061403", title: n => "Dormant account signed in from unknown IP: " + n, from: "Identity protection alert", channel: "SIEM alert",
      body: n => `<p>${n}'s account had no sign-in for months. In the last half hour it signed in from a hosting-provider IP after a password spray, registered a new MFA method, and downloaded 52 files from the PLM vault, several marked CUI.</p><p>This account was on the inactive-account sweep (TSK0011208).</p>`,
      prevented: "A few minutes ago, an attacker sprayed passwords at dormant accounts. Every attempt failed because you disabled them in the sweep (TSK0011208).",
      lesson: "A stale account is a door nobody is watching. Contain it and hand it to Security: CUI left the building, so the DFARS 72-hour report clock is running. NIST SP 800-171 3.5.6, 3.6.1." },
    svc: { id: "INC0061406", restores: "the file server backups", title: "File server backups failing since the account sweep", from: "Backup monitoring", channel: "Automated alert",
      body: `<p>The engineering file server backup job has failed on every run since the account was switched off: ${m("Logon failure: account disabled (svc-nas-backup)")}.</p><p>There is no restorable copy of the CUI file shares from after the inactive-account sweep (TSK0011208).</p>`,
      prevented: "File server backups kept running clean. You sent svc-nas-backup to its owner instead of disabling it.",
      lesson: "Service accounts aren't people. Disabling one breaks production silently, and backups of CUI have to keep running. Restore service, then let the owner decide. NIST SP 800-171 3.8.9." },
    leaver: { id: "INC0061409", title: "Terminated sysadmin copied a CUI share", from: "Data loss prevention alert", channel: "SIEM alert",
      body: "<p>HR told Dmitri Volkov about his termination (REQ0034112) this morning. His VPN session is still live: in the last half hour he used his domain admin account to copy the engineering CUI share to a personal cloud drive.</p>",
      prevented: "Dmitri Volkov tried the VPN right after HR told him, and was blocked. Clean offboarding.",
      effect: "Dmitri Volkov copied a CUI share to a personal cloud drive after his termination (INC0061409).",
      lesson: "Offboarding isn't done until the account is disabled, sessions are revoked and access is removed. CUI left the company, so this is a reportable cyber incident under DFARS 252.204-7012. NIST SP 800-171 3.9.2, 3.6.2." },
    recon: { id: "INC0061412", title: "Former machinist downloaded part programs", from: "MES activity monitoring", channel: "SIEM alert",
      body: "<p>curtis.langley downloaded 31 CNC part programs for export-controlled parts in the last hour. HR shows he left Meridian Aerospace on Sep 29. The account was flagged by HR reconciliation this morning (INC0061333).</p>",
      prevented: "Curtis Langley's old account tried the MES a few minutes ago and was blocked.",
      effect: "A former machinist downloaded 31 export-controlled part programs after he left (INC0061412).",
      lesson: "Every day a former employee stays enabled is a day of exposure. Export-controlled data is now outside the company, so Security and the Facility Security Officer both need it. NIST SP 800-171 3.9.2, 3.6.1." },
    sodReq: { id: "INC0061415", title: "Receiving clerk ordered and received his own PO", from: "ERP purchasing analytics", channel: "SIEM alert",
      body: "<p>In the last hour, a $4,800 purchase order for carbide tooling was raised by cyrus.pennington and marked received by the same account twelve minutes later. The tooling isn't in the crib.</p>",
      prevented: "Every purchase order this shift had two people: one to order, one to receive.",
      effect: "A receiving clerk raised and received his own purchase order, and the goods aren't there (INC0061415).",
      lesson: "This is exactly what separation of duties prevents. Remove the conflicting access now and send it to Security as possible fraud. NIST SP 800-171 3.1.4." },
    copy: { id: "REQ0034188", title: "Re: New hire Amara Nwosu: timecard access?", from: "Raymond Cho (Production Manager)", channel: "Email",
      body: "<p>\"Amara Nwosu just started in design and she's already approved two of my machinists' timecards, and she can change MES routings. How does she have that? Fix it, and check whoever she was copied from.\"</p>",
      prevented: "Amara started with clean design engineering access. Marguerite Ellison's leftover access is still worth a review.",
      effect: "A new design engineer approved timecards and could change routings with access copied from a peer (REQ0034188).",
      lesson: "Copying a peer copies their mistakes. Fix both people, and use the role matrix from now on. NIST SP 800-171 3.1.5." },
    priv: { id: "INC0061418", title: "Domain Admin created a hidden admin account", from: "Directory audit alert", channel: "SIEM alert",
      body: "<p>brianna.cole used Domain Admin to create an account named <span class=\"mono\">svc-print2</span> and add it to Domain Admins. Brianna says she didn't do it. Her account signed in from a new device earlier this morning.</p>",
      prevented: "Domain admin stayed with the systems administrators, on their separate admin accounts.",
      effect: "A standing Domain Admin grant was used to create a hidden admin account (INC0061418).",
      lesson: "Standing admin rights turn one phished technician into control of every CUI system. Remove the role, contain the account, and keep admin rights under change control. NIST SP 800-171 3.1.5, 3.1.6." },
    exec: { id: "INC0061421", title: "$290,000 paid to a fake titanium supplier", from: "Ruth Kaminski (Controller)", channel: "Phone",
      body: "<p>A $290,000 payment to new bank details for the titanium supplier was approved from Desmond Achebe's account minutes after the MFA change on INC0061326. The real Desmond has been in the office all morning and never called the desk. The attacker registered their own phone for MFA.</p>",
      prevented: "The real Desmond Achebe thanked the desk. The \"conference call\" came from a fraud crew targeting defense suppliers this month.",
      effect: "An attacker impersonating the CFO got a $290,000 payment to fake bank details approved (INC0061421).",
      lesson: "One skipped identity check paid for the attacker's quarter. Contain the account, remove their MFA method, and involve Security, Legal and the bank right away. NIST SP 800-171 3.5.2, 3.6.1." },
    contractor: { id: "INC0061424", title: "Re: Extend contractor: Ivan still locked out", from: "Gabriel Fontaine (sponsor)", channel: "Email",
      approval: "Gabriel Fontaine (sponsor) replied: \"Approved. Same renewal I sent this morning.\"",
      body: "<p>\"This didn't work. Ivan's account says it's expired and he can't open the models, so the stress analysis has stalled. The customer's design review is next week. I sent this request first thing this morning!\"</p>",
      prevented: "Ivan Petrenko's statement of work rolled over without a gap.",
      lesson: "Missed requests have a delivery cost too. Contractor accounts need the end date, the sponsor approval and the extension handled together. NIST SP 800-171 3.1.1." },
    compromise: { id: "INC0061427", title: "Harriet Vance's mailbox sent drawings to a lookalike domain", from: "Email security", channel: "SIEM alert",
      body: "<p>In the last half hour, harriet.vance forwarded 18 supplier drawings marked CUI to an address at a lookalike of a supplier's domain. The sign-ins came from the same Bucharest infrastructure as this morning's alert (INC0061342).</p>",
      prevented: "Security traced the Bucharest sign-in to a phishing kit and blocked it network-wide after your escalation.",
      lesson: "Half-contained is not contained. The attacker kept a session or token, came back, and took CUI. Do every step, then escalate. NIST SP 800-171 3.6.1; DFARS 252.204-7012(c)." },
    callerPw: { id: "INC0061430", title: "\"I never asked for a password reset\"", from: "Bernadette Quigley", channel: "Phone (desk line)",
      body: "<p>\"I only just got to my desk after my week at the lake. Someone called in as me earlier, got my password reset, and has been in my email and the quality system since. How did they get through?\"</p><p>There is no identity verification on record for the reset on INC0061311.</p>",
      prevented: "Bernadette Quigley confirmed the reset was her, and your verification is on record.",
      effect: "An unverified reset let an attacker into Bernadette Quigley's email and the quality system (INC0061430).",
      lesson: "If verification isn't recorded, it didn't happen. That's true for assessors and for attackers. Contain, rotate, escalate. NIST SP 800-171 3.5.2." },
    review: { id: "REQ0034191", title: "Re: Q3 revocation not done", from: "Sharon Whitaker (Facility Security Officer)", channel: "Email",
      body: "<p>\"This was closed, but it didn't work. Follow-up testing shows Thaddeus Okonjo still holds GRP-ITAR-Technical-Data, which the Q3 reviewer marked for revocation. That goes on the POA&amp;M for the CMMC assessment unless it's fixed and evidenced today.\"</p>",
      prevented: "The Facility Security Officer closed the Q3 access review with no open revocations.",
      lesson: "An access review isn't finished when the manager clicks Revoke. It's finished when access is actually removed. NIST SP 800-171 3.1.1, 3.1.5." },
    mover: { id: "REQ0034194", title: "Re: Transfer: Nadia still has inspection sign-off", from: "Delia Marquez (Quality Manager)", channel: "Email",
      body: "<p>\"This didn't work. Nadia moved to manufacturing engineering this morning, but she just signed off two inspections on parts made under her own process change. Why does she still have inspection sign-off?\"</p>",
      prevented: "Nadia's transfer was clean. Quality confirmed she has no inspection sign-off.",
      effect: "Nadia Farouk kept inspection sign-off after moving to engineering and approved inspections of her own process change (REQ0034194).",
      lesson: "Movers keep old access unless someone removes it. This is how privilege creep builds. NIST SP 800-171 3.9.2." },
  },
  audit: { manager: { name: "Kenji Watanabe", title: "IT Manager" } },
  grc: {
    G,
    ctx: "CMMC Level 2 readiness review",
    intro: "You're Meridian Aerospace's internal auditor, testing access controls ahead of the CMMC Level 2 certification assessment.",
    levels: { title: "Cyber incident reporting (DFARS 252.204-7012)", items: [
      ["Cyber incident", "actions taken through the use of computer networks that result in a compromise or an actual or potentially adverse effect on an information system or the information residing in it (252.204-7012(a))."],
      ["Rapid report", "when a cyber incident affects covered defense information, report it to the DoD at dibnet.dod.mil within 72 hours of discovery (252.204-7012(c))."],
      ["Preserve", "keep images of the affected systems and relevant monitoring data for at least 90 days from the report, in case the DoD asks for them (252.204-7012(e))."]],
      note: "Audit findings go to the IT Manager and into the System Security Plan and POA&M. Anything that may involve CUI goes to Security at once, so the 72-hour clock is met." },
    controls: {
      "VEN-01": ["Service provider oversight", "Security evidence for cloud and external service providers is reviewed each year, including FedRAMP equivalency, the customer responsibility matrix and contract coverage.", "Annual · Manual · Detective"],
    },
  },
});
