// Coastline Credit Union's GLBA audit desk: access controls tested by internal audit for the
// Supervisory Committee before the NCUA examination. Requirements cite 12 CFR Part 748 and its
// appendices, NCUA's rule for GLBA safeguards.
import { PROV_OPTS, TERM_OPTS, G4, rowKit } from "../../engine/grcKit.js";
import { ROLES, buildUsers } from "./company";

const { J, X, RR } = rowKit(ROLES);
// The directory as the review population: employees, contractors and service accounts.
const people = Object.values(buildUsers());
const contractors = people.filter(u => u.type === "Contractor").length;
const service = people.filter(u => u.type === "Service").length;
const staff = people.length - contractors - service;

export const G = [
 {id:"G1",ctrl:"APD-01",title:"Test new user provisioning",kind:"table",opts:PROV_OPTS,
  intro:"<p><b>APD-01:</b> Access for new employees is approved by the manager <i>before</i> provisioning and limited to the role's birthright groups (12 CFR Part 748, Appendix A: access only for authorized individuals).</p><p>Test the 15 sampled Q3 joiners. Compare approval date to provisioned date, and groups granted to the access matrix (Policy &amp; matrix tab). Pre-hire accounts are created disabled before the start date; that's normal.</p>",
  rows:[J("Abigail Fenwick","Branch|Teller","Mon, Jul 6","Patrice Duval, Jul 1","Jul 2",null,0),
   J("Bryce Holloway","Lending|Loan Officer","Mon, Jul 13","Nathan Greer, Jul 8","Jul 9",null,0),
   J("Cordelia Banks","Branch|Member Service Representative","Mon, Jul 20","Caroline Ashby, Jul 14","Jul 15",null,0),
   J("Damon Pryce","Operations|Payments Specialist","Mon, Jul 20","None on file","Jul 16",null,1),
   J("Evangeline Ross","Branch|Teller","Mon, Jul 27","Caroline Ashby, Jul 21","Jul 22",null,0),
   J("Fletcher Moss","Lending|Underwriter","Mon, Aug 3","Nathan Greer, Jul 28","Jul 29",null,0),
   J("Gemma Whitley","Branch|Teller","Mon, Aug 3","Patrice Duval, Jul 29","Jul 30",null,0),
   J("Harlan Shaw","Lending|Collections Specialist","Mon, Aug 10","Nathan Greer, Aug 4","Aug 5",null,0),
   J("Isadora Lane","Branch|Member Service Representative","Mon, Aug 17","Patrice Duval, Aug 13","Aug 11",null,2,"Provisioned Aug 11, approved Aug 13."),
   J("Jonah Wilder","Operations|Card Services Specialist","Mon, Aug 24","Simone Achterberg, Aug 18","Aug 19",null,0),
   J("Kendra Oakes","Lending|Loan Servicing Specialist","Mon, Aug 31","Nathan Greer, Aug 25","Aug 26",null,0),
   J("Lionel Burke","Branch|Teller","Tue, Sep 8","Caroline Ashby, Sep 1","Sep 2",["APP-Wire-Initiate"],3,"Wire initiation isn't a Teller birthright group; only head tellers initiate wires."),
   J("Mabel Truong","Finance|Accountant","Mon, Sep 14","Martina Kovac, Sep 9","Sep 10",null,0),
   J("Nigel Ashcroft","Branch|Teller","Mon, Sep 21","Patrice Duval, Sep 15","Sep 16",null,0),
   J("Ophelia Grant","Branch|Member Service Representative","Mon, Sep 28","Caroline Ashby, Sep 24","Sep 23",null,2,"Provisioned Sep 23, approved Sep 24.")],
  lesson:"Test both halves of the control: approval before access, and access limited to the role. 4 of 15 failed (27%), so APD-01 is not operating effectively. Extra payments access at a credit union is a fraud risk as well as an audit exception."},
 {id:"G2",ctrl:"APD-02",title:"Test timely terminations",kind:"table",opts:TERM_OPTS,
  intro:"<p><b>APD-02:</b> Accounts are disabled within <b>one business day</b> of the HR separation date (Access Management policy, part of the information security program under 12 CFR Part 748, Appendix A).</p><p>Test the 12 sampled Q3 separations from the Oct 2 directory extract. Weekends don't count as business days.</p>",
  rows:[X("Pearl Hendricks","Teller","Wed, Jul 8","Wed, Jul 8","Jul 7",0),
   X("Quentin Lyle","Loan Officer","Fri, Jul 10","Mon, Jul 13","Jul 10",0,"Friday to Monday is one business day."),
   X("Rowena Blake","Member Service Representative","Thu, Jul 16","Thu, Jul 16","Jul 16",0),
   X("Stellan Voss","Collections Specialist","Tue, Jul 21","Tue, Jul 28","Jul 20",1,"Five business days late; no sign-in after separation."),
   X("Howard Teague","Branch Manager","Fri, Jul 31","Not disabled","Aug 11",3,"Still enabled at extract, and approved a purchase order after he retired."),
   X("Tabitha Crane","Member Service Representative","Mon, Aug 3","Fri, Aug 14","Aug 7",2,"Looked up member accounts on Aug 7, four days after separation."),
   X("Upton Harrow","Teller","Fri, Aug 14","Mon, Aug 17","Aug 13",0,"Friday to Monday is one business day."),
   X("Verity Cole","Underwriter","Fri, Aug 21","Mon, Aug 24","Aug 20",0,"Friday to Monday is one business day."),
   X("Wilfred Gage","Teller","Tue, Sep 1","Tue, Sep 1","Aug 31",0),
   X("Xanthe Moreland","Card Services Specialist","Thu, Sep 10","Thu, Sep 10","Sep 10",0),
   X("Diego Salcedo","Payments Specialist","Sun, Sep 27","Not disabled","Oct 2",3,"Still enabled at extract and signing in. This is the same account from IAM Ops ticket INC0073333."),
   X("Yolanda Pierce","Teller","Tue, Sep 29","Wed, Sep 30","Sep 29",0,"Next business day is within policy.")],
  lesson:"Measure against the policy exactly: Friday to Monday passes. Keep \"late\" separate from \"late and used\". At a credit union, use after separation can mean a former employee read members' accounts or touched payments."},
 {id:"G3",ctrl:"APD-02",title:"Evaluate the termination exceptions",kind:"quiz",
  intro:"<p>Your APD-02 test found 4 exceptions in 12 samples. Additional facts from follow-up:</p><ul><li>Stellan Voss (Collections Specialist) kept collections access for 5 extra business days. Logs show no activity after separation.</li><li>Tabitha Crane looked up 9 members' accounts in the core system on Aug 7, four days after separation.</li><li>Howard Teague's account approved a $3,200 purchase order on Aug 11, after he retired.</li><li>Diego Salcedo's account is still active and signed in on Oct 2.</li></ul><p>Definitions are on the Controls tab.</p>",
  qs:[{q:"Is APD-02 operating effectively for Q3?",short:"Effectiveness conclusion",opts:["Yes: 8 of 12 passed","No: 4 of 12 (33%) failed, which is well above a tolerable rate for a per-event control"],correct:1,pts:2},
   {q:"Tabitha Crane looked up members' accounts after she left. What happens with that?",short:"Member data accessed after separation",opts:["Document it in the finding only","Refer it to the Information Security Officer now. It's unauthorized access to member information, so the response program applies: decide whether misuse is reasonably possible and members must be notified, and whether NCUA must be told.","Ask Tabitha what she looked at, and close it if she says nothing"],correct:1,pts:3},
   {q:"Howard Teague's account approved a purchase order after he retired. How do you treat it?",short:"Use after retirement",opts:["No issue, because he was a trusted manager","Refer it to Security and the Controller as possible fraud, have the account disabled now, and include it in the finding","Wait for the next quarterly access review"],correct:1,pts:3}],
  lesson:"At a credit union, a failed termination control isn't only an audit exception. Member information reached after someone leaves triggers the response program, and any use after separation is a security incident."},
 G4,
 {id:"G5",ctrl:"UAR-01",title:"Review the Q3 access review for completeness",kind:"quiz",
  intro:"<p><b>UAR-01:</b> Each quarter, managers certify <i>all</i> directory accounts (employees, contractors, service accounts). Revocations are completed within 5 business days.</p>",
  evidence:[["Directory extract, Sep 30",`${people.length} accounts: ${staff} employees, ${contractors} contractors, ${service} service accounts`],["Access review file",`${staff} accounts, all certified by managers`],["Reviewer sign-off","Dennis Mulroney, Oct 1"],["Population source","Excel export provided by IT; no query or run parameters attached"]],
  qs:[{q:"What is the main issue?",short:"Issue identified",opts:[`Completeness: the ${contractors} contractors and ${service} service accounts were left out of the review`,"Timeliness: sign-off came after quarter end","Accuracy: managers certified too quickly","No issue"],correct:0,pts:3},
   {q:"What evidence do you request? Select all that apply.",multi:true,opts:["A system-generated population with the query, parameters and run date",`Review evidence for the ${contractors + service} excluded accounts`,"An email from IT confirming the review was complete","Re-perform the whole review yourself"],correct:[0,1]},
   {q:"Until those accounts are reviewed, can UAR-01 be relied on to catch the access APD-02 missed?",short:"Reliance on UAR-01",opts:["Yes","No"],correct:1,pts:2}],
  lesson:"Before testing a review, test the population. Contractors and service accounts are the usual gaps, and the service accounts here move card and payment files."},
 {id:"G6",ctrl:"RISK",title:"Rate the information security risk register",kind:"table",opts:["High","Medium","Low"],
  intro:"<p>Appendix A to Part 748 asks the credit union to assess reasonably foreseeable threats to member information. Rate each risk's inherent level. Score = likelihood × impact. <b>High</b> 15–25, <b>Medium</b> 8–14, <b>Low</b> 1–7.</p><p class=\"mono\" style=\"font-size:12px\">Likelihood: Rare 1 · Unlikely 2 · Possible 3 · Likely 4 · Almost certain 5<br>Impact: Minimal 1 · Minor 2 · Moderate 3 · Major 4 · Severe 5</p>",
  rows:[RR("R-01 Former employees keep core access","APD-02 failures; 3 accounts used after separation","Likely","Severe",0),
   RR("R-02 Shared drive-up teller login","Requested by a branch manager","Possible","Moderate",1),
   RR("R-03 Wire initiate and approve on one person","A head teller holds both","Possible","Severe",0),
   RR("R-04 Core processor SOC 2 coverage gap","Report ends Jun 30","Unlikely","Moderate",2),
   RR("R-05 MFA fatigue attacks","One successful push approval this week","Likely","Moderate",1)],
  lesson:"Apply the matrix the same way every time. The risk assessment drives what the board sees first, so R-01 (20) and R-03 (15) lead the remediation plan."},
 {id:"G7",ctrl:"VEN-01",title:"Review the core processor's SOC 2 report",kind:"quiz",
  intro:"<p>Tidewater Core Services runs Coastline's core banking system, so it holds every member's account data. Appendix A to Part 748 requires the credit union to oversee service providers and require safeguards by contract. The audit period ends Dec 31.</p>",
  evidence:[["Report","SOC 2 Type II, Security and Availability"],["Period","Oct 1, 2025 to Jun 30, 2026"],["Opinion","Unqualified"],["Exception","CC6.2: 3 of 25 sampled terminated users were removed late. Management response: daily HR reconciliation implemented Aug 2026."],["Subservice org","A colocation data center provider (carve-out method)"],["Complementary user entity controls","1) Customers remove their terminated users within 1 business day. 2) Customers review their users' access quarterly."],["Contract","Signed 2019. Requires safeguards for member information, but has no incident notice deadline."]],
  qs:[{q:"Which follow-ups are needed? Select all that apply.",multi:true,opts:["Get a bridge letter covering Jul 1 to Dec 31","Evaluate whether the CC6.2 exception affects our reliance","Confirm our own user entity controls (termination, quarterly review) are operating","Get and review the data center's SOC report for the carved-out subservice","Add an incident notice deadline to the contract, short enough for NCUA's 72-hour clock","Drop the vendor because the report has an exception","No action needed; the opinion is unqualified"],correct:[0,1,2,3,4]},
   {q:"Why does your APD-02 result matter for this review?",short:"Link to APD-02",opts:["It doesn't; the processor runs the system","Tidewater relies on us to remove our own users on time. Our late terminations mean that user entity control is failing.","It means Tidewater's opinion should be qualified"],correct:1,pts:3}],
  lesson:"A clean SOC 2 opinion isn't the end of the review. Cover the gap period, weigh the exceptions, check the carved-out subservice provider, confirm your own side of the user entity controls, and make sure the contract gets you incident news in time to meet your own reporting duty."},
 {id:"G8",ctrl:"POL-EX",title:"Decide a policy exception request",kind:"quiz",
  intro:"<p>After IAM Ops rejected the shared <span class=\"mono\">driveup-teller</span> login, the branch filed a formal policy exception: \"The drive-up line backs up while tellers sign in at every rotation. Badge sign-in is budgeted for Q2 2027.\"</p>",
  qs:[{q:"What is the decision?",short:"Exception decision",opts:["Deny outright; policy is policy","Approve as asked: one shared login for the drive-up terminal and the core teller system","Approve temporarily for the workstation sign-in only, with every teller still signing in to the core teller system with their own ID, compensating controls and risk owner sign-off"],correct:2,pts:3},
   {q:"Which conditions belong in the approval? Select all that apply.",multi:true,opts:["The shared login opens the workstation only; every teller transaction uses the teller's own ID and drawer","Expiry of 90 days or less, with re-review","Short idle lock on the workstation","Sign-off by the risk owner (Linnea Berg, COO)","Tracked project to replace it with badge sign-in","Let the shared login run teller transactions too, to save time","Keep the password on a sticky note at the window"],correct:[0,1,2,3,4]}],
  lesson:"GRC's job is managed risk, not saying no. Every cash transaction has to trace to one teller, so the exception can't reach the core teller system. Keep it narrow, time-limited, compensated and owned by the business."},
 {id:"G9",ctrl:"MAP",title:"Map APD-02 to frameworks",kind:"quiz",
  intro:"<p>Map APD-02 (disable accounts within one business day of separation) so one test can answer several reviews.</p>",
  qs:[{q:"Select every requirement APD-02 supports.",multi:true,opts:["12 CFR Part 748, Appendix A: access controls on member information systems","FFIEC IT Handbook, Information Security: user access management","NIST 800-53 PS-4 Personnel Termination","NIST 800-53 AC-2 Account Management","ISO 27001:2022 A.5.18 Access rights","12 CFR 748.1(c) Cyber incident notification","NIST 800-53 CP-9 System Backup","ISO 27001:2022 A.8.13 Information backup","12 CFR Part 749 Records preservation"],correct:[0,1,2,3,4]}],
  lesson:"Test once, satisfy many. A mapped control lets one set of APD-02 evidence answer the NCUA exam, the Supervisory Committee audit and a partner's security questionnaire."},
 {id:"G10",ctrl:"APD-02",title:"Write the termination finding",kind:"quiz",
  intro:"<p>Build the APD-02 finding. Pick the strongest statement for each element.</p>",
  qs:[{q:"Condition",short:"Condition",opts:["Access was removed late for some staff.","4 of 12 sampled separations (33%) were not disabled within one business day. Two accounts were still active at extract, and three former employees used their accounts after leaving, one to look up member accounts.","IT doesn't take separations seriously."],correct:1,pts:2},
   {q:"Criteria",short:"Criteria",opts:["The Access Management policy requires accounts to be disabled within one business day of the HR separation date (control APD-02), part of the information security program required by 12 CFR Part 748, Appendix A.","Best practice says access should be removed quickly.","NCUA requires same-day removal."],correct:0,pts:2},
   {q:"Cause",short:"Cause",opts:["The service desk was careless.","Unknown.","Separations are processed by hand from HR emails. There is no automated HR-to-directory trigger or daily reconciliation."],correct:2,pts:2},
   {q:"Effect",short:"Effect",opts:["Coastline will lose its charter.","Former employees could reach member information and payments after leaving, and one did (9 member accounts, now in the member-notice review).","No impact, because no money was lost."],correct:1,pts:2},
   {q:"Recommendation",short:"Recommendation",opts:["Automate deprovisioning from the HR separation event, and add a daily HR-to-directory reconciliation with exceptions reviewed by the Information Security Officer.","Remind the service desk to be faster.","Remove all users' access every quarter."],correct:0,pts:2}],
  lesson:"A finding that holds up is specific (numbers), cites the actual requirement, names a fixable cause, states real impact without exaggeration, and recommends a fix that addresses the cause."}
];
