// Coastline Credit Union's PAM shift. The kit (lib/pamKit.js) supplies grading, hints, the playbook
// and the PAM runbook; this file is the story. Lessons cite 12 CFR Part 748, Appendix A (NCUA's
// GLBA safeguards guidelines) and NIST SP 800-53 Rev. 5.
import { buildPam } from "../lib/pamKit.js";
import * as company from "./company";
import * as policy from "./policy";

const P748 = { label: "12 CFR Part 748, Appendix A", href: "https://www.ecfr.gov/current/title-12/chapter-VII/subchapter-A/part-748" };
const n53 = id => ({ label: `NIST SP 800-53 Rev. 5, ${id}`, href: "https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final" });
const ADMIN = "IT|Systems Administrator", CORE = "IT|Core Systems Administrator", STAFF = ["GRP-All-Staff", "APP-Office-Suite", "APP-Service-Desk"];

export const pam = buildPam({
  id: "coastline",
  eligible: { [CORE]: ["ROLE-Core-Security-Admin"], [ADMIN]: ["ROLE-Server-Admin"], "IT|IT Manager": ["ROLE-User-Admin"], "Vendors|Core Vendor Support": ["ROLE-Core-Vendor-Admin"] },
  also: ["ROLE-Global-Admin"],
  roles: { [ADMIN]: [...STAFF, "ROLE-Server-Admin"], "Vendors|Core Vendor Support": ["GRP-Contractors"] },
  cast: [
    ["elliot.vance", "Elliot Vance", "60181", CORE, "Dennis Mulroney"],
    ["noelle.fisk", "Noelle Fisk", "60183", ADMIN, "Dennis Mulroney", { groups: [...STAFF, "ROLE-Server-Admin"] }],
    ["garrett.lyle", "Garrett Lyle", "60185", "IT|Digital Banking Specialist", "Dennis Mulroney", { groups: ["GRP-All-Staff", "APP-Office-Suite", "APP-Digital-Banking-Admin", "ROLE-Core-Security-Admin"] }],
    ["tristan.hale", "Tristan Hale", "60187", ADMIN, "Dennis Mulroney"],
    ["imogen.price", "Imogen Price", "60189", ADMIN, "Dennis Mulroney", { groups: [...STAFF, "ROLE-Server-Admin"], jit: { "ROLE-Server-Admin": 2 } }],
    ["cyrus.webb", "Cyrus Webb", "60191", CORE, "Dennis Mulroney"],
    ["bianca.ortiz", "Bianca Ortiz", "60193", "IT|Service Desk Analyst", "Dennis Mulroney"],
    ["lars.nyberg", "Lars Nyberg", "V-3381", "Vendors|Core Vendor Support", "Priscilla Ng (sponsor)", { type: "Contractor", enabled: false, expiry: 240, last: 52 }],
    ["bg-admin-01", "bg-admin-01", "BG-01", null, "Dennis Mulroney (owner)", { dept: "IT", title: "Break-glass account: emergency Global Admin", type: "Break-glass", groups: ["ROLE-Global-Admin"], enabled: false, mfa: false, last: 301 }],
  ],
  hr: [{ type: "Termination", who: "Cyrus Webb", detail: "Involuntary. Effective today, 9:00 AM. Core Systems Administrator.", when: 0 }],
  cite: { "pam-jit": [P748, n53("AC-6(5)")], "pam-eligible": [P748, n53("AC-2(7)")], "pam-breakglass": [n53("AC-2(2)"), n53("IA-5")],
    "pam-vault": [P748, n53("IA-5")], "pam-session": [P748, n53("AC-6(9)")], "pam-vendor": [P748, n53("AC-17(4)")], "pam-shared": [n53("IA-2"), n53("AC-2k")] },
  mon: {
    jit: { id: "REQ0043101", uid: "elliot.vance", group: "ROLE-Core-Security-Admin", hours: 2, change: "CHG0062114", approver: "Linnea Berg",
      what: "add the new share-certificate product codes to the core's security tables", from: "Elliot Vance", channel: "Portal", opened: "6:45 AM",
      lesson: "Activate an eligible role for the approved window only, with the approval on the ticket first. 12 CFR Part 748, Appendix A (access controls on member information systems); NIST AC-6(5)." },
    breakGlass: { id: "INC0074101", uid: "dennis.mulroney", bg: "bg-admin-01", title: "Emergency: admins locked out, need break-glass", from: "Dennis Mulroney", channel: "Phone", opened: "7:00 AM",
      body: "<p>\"It's Dennis. The MFA provider is down and none of the admins can sign in. The card processor file transfer failed overnight and members' cards will decline at the branches when they open at 9. I'm declaring an emergency. I need bg-admin-01.\"</p>",
      lesson: "Break-glass access is real admin power with no MFA in front of it. Verify the caller, enable only the documented account, and tell Security straight away. NIST AC-2(2)." },
    notEligible: { id: "REQ0043104", uid: "bianca.ortiz", group: "ROLE-Core-Security-Admin", title: "Core security admin for the service desk", from: "Bianca Ortiz", channel: "Portal", opened: "7:20 AM",
      body: "<p>Member service reps get locked out of the core every Monday and I have to wait for the core team to reset them. If I had core security admin I could do it myself. Dennis is fine with it.</p>",
      alt: "explain that Service Desk Analysts aren't eligible for ROLE-Core-Security-Admin. Core security changes go to a Core Systems Administrator.",
      lesson: "Eligibility for a privileged role comes from the job. A manager's approval can't add a role the job doesn't include. 12 CFR Part 748, Appendix A (dual control and segregation of duties)." },
    rotate: { id: "REQ0043107", svc: "svc-core-batch", down: "The core's nightly batch posting", title: "svc-core-batch password in a shared spreadsheet", from: "Priscilla Ng", channel: "Portal", opened: "7:35 AM",
      body: "<p>The <span class=\"mono\">svc-core-batch</span> password turned up in a spreadsheet on the operations team's shared drive, where anyone in Operations can read it. Nobody knows how long it's been there.</p><p>Please deal with the password. Tonight's batch posting has to run.</p>",
      lesson: "An exposed service credential is rotated, not disabled. The batch keeps running and the leaked password stops working. 12 CFR Part 748, Appendix A; NIST IA-5." },
    standing: { id: "TSK0014101", holders: [["noelle.fisk", "ROLE-Server-Admin"], ["garrett.lyle", "ROLE-Core-Security-Admin"]], bg: "bg-admin-01", bgGroup: "ROLE-Global-Admin",
      title: "PAM report: standing privileged memberships", from: "PAM vault (weekly report)", channel: "Automated", opened: "8:00 AM",
      body: "<p>These accounts hold a vaulted role permanently instead of activating it:</p><ul><li><span class=\"mono\">noelle.fisk</span>: ROLE-Server-Admin (since the vault migration)</li><li><span class=\"mono\">garrett.lyle</span>: ROLE-Core-Security-Admin (added during the online banking conversion)</li><li><span class=\"mono\">bg-admin-01</span>: ROLE-Global-Admin</li></ul><p>Clean up the standing access per the PAM runbook.</p>",
      lesson: "Standing admin access to member information systems is the gap PAM closes. Remove it, except where the runbook documents an exception. 12 CFR Part 748, Appendix A." },
    adminLeaver: { id: "REQ0043110", uid: "cyrus.webb", svc: "svc-card-files", title: "Termination: Cyrus Webb, Core Systems Administrator", from: "HR system (automated)", channel: "HR integration", opened: "8:15 AM",
      body: "<p>Involuntary termination, effective 9:00 AM today. Remove all access before the meeting.</p><p>PAM vault note: Cyrus checked out the <span class=\"mono\">svc-card-files</span> password on Monday and it hasn't been rotated since.</p>",
      lesson: "An admin leaver's access ends only when what they knew stops working: rotate any credential they checked out. 12 CFR Part 748, Appendix A; NIST PS-4." },
    vendor: { id: "REQ0043113", uid: "lars.nyberg", group: "ROLE-Core-Vendor-Admin", hours: 3, title: "Vendor support session: core interest accrual fix", from: "Priscilla Ng", channel: "Portal", opened: "8:30 AM",
      body: "<p>Lars from the core vendor needs admin on the core to apply a fix for the interest accrual bug before month end. The session is booked from 9:00 AM to 12:00 PM. His account is off between sessions.</p>",
      lesson: "Vendor access is opened for one approved session: sponsor approval, the account enabled, the role for the session only. 12 CFR Part 748, Appendix A (oversee service providers); NIST AC-17(4)." },
    noChange: { id: "REQ0043116", uid: "tristan.hale", group: "ROLE-Server-Admin", target: "The branch imaging server", title: "Server admin for the weekend", from: "Tristan Hale", channel: "Portal", opened: "9:00 AM",
      body: "<p>I'd like to clean up the branch imaging server this weekend while the branches are closed. Can you activate server admin for me from Friday night to Sunday night, around 48 hours? No change raised, it's just housekeeping.</p>",
      alt: "explain that eligibility isn't enough: the work needs an approved change, and activations are capped at 4 hours.",
      lesson: "Eligible isn't approved. Privileged roles are activated for an approved change, for a short window. NIST AC-6(5)." },
    session: { id: "REQ0043119", title: "Weekly privileged session review", from: "Information Security Officer", channel: "Email", opened: "9:25 AM",
      intro: "<p>Yesterday's recorded admin sessions are below. Check each one against the change or incident it was opened for, and send me the IDs of any session that went outside it.</p>",
      rows: [
        ["PSM-50308", "noelle.fisk", "CHG0062090: patch the online banking web servers", "OLB-WEB-01", "Installed patches, rebooted, <b>ran a query listing members' Social Security numbers and saved it to her desktop</b>", true],
        ["PSM-50312", "tristan.hale", "CHG0062093: replace the backup tape drive", "BKP-01", "Swapped the drive, ran a test backup", false],
        ["PSM-50317", "imogen.price", "INC0074050: ATM network alert", "ATM-GW-01", "Read the gateway logs, restarted the ATM switch service", false],
        ["PSM-50321", "cyrus.webb", "CHG0062097: renew the core's TLS certificate", "CORE-APP-01", "Imported the certificate, <b>gave his own account wire approval rights in the core</b>", true],
        ["PSM-50326", "elliot.vance", "CHG0062099: add a teller drawer profile", "CORE-APP-01", "Added the drawer profile and tested it with the branch", false],
      ],
      lesson: "A recorded session only protects members if someone compares it with the reason it was opened. 12 CFR Part 748, Appendix A (monitoring to detect attacks and intrusions); NIST AC-6(9)." },
    compromised: { id: "INC0074104", uid: "imogen.price", group: "ROLE-Server-Admin", title: "SIEM alert: admin sign-in from abroad", from: "SIEM alert", channel: "Automated", opened: "9:45 AM",
      body: "<p>At 6:10 AM <span class=\"mono\">imogen.price</span> approved an MFA prompt after 18 push requests, signed in from an IP address in Nigeria, and activated ROLE-Server-Admin for 2 hours. Imogen was getting her kids ready for school and approved a prompt to make it stop.</p>",
      lesson: "A compromised admin account is contained when the attacker has nothing left: no session, password, MFA method or privileged role. Then Security takes it. 12 CFR Part 748, Appendix A (response programs)." },
    shared: { id: "REQ0043122", uid: "wesley.tranter", title: "Shared admin login for Saturday branches", from: "Wesley Tranter", channel: "Portal", opened: "10:00 AM",
      body: "<p>Saturday branch hours keep hitting printer and scanner issues with no admin on call. Could the Saturday desk share a <span class=\"mono\">satadmin</span> login, or could you email them the server admin password?</p>",
      alt: "explain that admin passwords are never shared. Admins check credentials out of the vault under their own accounts, and Saturday issues go to the on-call Systems Administrator.",
      lesson: "Shared admin credentials make every change anonymous and can't be taken back from one person. NIST IA-2, AC-2k." },
    auditQ: { id: "REQ0043125", group: "ROLE-Core-Security-Admin", title: "Exam prep: who holds core security admin", from: "Internal audit (NCUA exam prep)", channel: "Email", opened: "10:15 AM",
      body: "<p>For the upcoming NCUA examination, please list every enabled account that holds <span class=\"mono\">ROLE-Core-Security-Admin</span> right now, including any just-in-time activations still running. Usernames are fine.</p>",
      lesson: "Exam evidence is pulled from the system as it stands. 12 CFR Part 748, Appendix A (test key controls)." },
  },
  thu: {
    bgClose: { id: "TSK0014104", from: "Dennis Mulroney", channel: "Portal", opened: "10:40 AM",
      body: "<p>MFA is back, the card file went through, and the admins can sign in. Emergency over as of 10:30 AM. Please close out bg-admin-01 per the break-glass procedure.</p>",
      lesson: "Break-glass is closed as deliberately as it's opened: disabled, rotated and signed out. NIST AC-2(2), IA-5." },
    vendorEnd: { id: "TSK0014107", from: "Priscilla Ng", channel: "Portal", opened: "11:10 AM",
      body: "<p>Lars applied the accrual fix and tested it. Session's over. Please close his access.</p>",
      lesson: "Third-party access ends with the session. 12 CFR Part 748, Appendix A; NIST AC-17(4)." },
  },
  conseq: {
    standingJit: { id: "INC0074110", from: "PAM vault", channel: "Automated", opened: "Afternoon" },
    notEligible: { id: "INC0074113", from: "Information Security Officer", channel: "Email", opened: "Afternoon" },
    svcDown: { id: "INC0074116", from: "Priscilla Ng", channel: "Phone", opened: "Afternoon" },
    svcLeak: { id: "INC0074119", from: "SIEM alert", channel: "Automated", opened: "Afternoon" },
    leaver: { id: "INC0074122", from: "Information Security Officer", channel: "Email", opened: "Afternoon" },
    noChange: { id: "INC0074125", from: "Information Security Officer", channel: "Email", opened: "Afternoon" },
    compromised: { id: "INC0074128", from: "SIEM alert", channel: "Automated", opened: "Afternoon" },
    bgOpen: { id: "INC0074131", from: "PAM vault", channel: "Automated", opened: "Afternoon" },
    vendorOpen: { id: "INC0074134", from: "Information Security Officer", channel: "Email", opened: "Afternoon" },
  },
}, company, policy);
