// Coastline Credit Union's shift on the service desk. The kit (lib/ticketKit.js) supplies grading,
// hints, the playbook and Jordan Reyes' shift; this file is the story. Lessons cite GLBA as NCUA
// applies it (12 CFR Part 748 and its appendices) and the FFIEC IT Examination Handbook.
import { buildTicketSet } from "../lib/ticketKit.js";
import { ROLES, SOD, buildUsers } from "./company";
import { G } from "./grc.js";

const m = x => `<span class="mono">${x}</span>`;

export const set = buildTicketSet({
  id: "coastline", ROLES, SOD, buildUsers,
  mon: {
    joiner: { id: "REQ0042104", uid: "kiara.thompson", rk: "Branch|Teller", title: "New hire: Kiara Thompson, Teller",
      from: "HR system (automated)", channel: "HR integration", opened: "6:20 AM",
      body: "<p>New hire starting today at the Harborside branch. The pre-hire account was created by the HR sync but is disabled with no access.</p><p>Please activate the account and provision access for the role. Teller training sign-off is on file. The branch opens at 9:00 AM.</p>",
      lesson: "Provision from the role in the access matrix, nothing more. 12 CFR Part 748, Appendix A (access controls on member information systems); FFIEC Information Security booklet." },
    callerPw: { id: "INC0073311", uid: "rosalyn.whitcombe", title: "Forgot password after vacation",
      from: "Rosalyn Whitcombe", channel: "Phone", opened: "7:40 AM",
      body: "<p>\"Hi, I'm just back from a week in Maine and my password expired while I was gone. I tried a new one and now I can't remember what I picked. Can you reset it? I've got payoff quotes due this morning.\"</p>",
      lesson: "Verify identity against the system of record before any credential reset. Appendix A to Part 748 calls for controls that permit access only to authorized individuals." },
    callerLock: { id: "INC0073314", uid: "ambrose.kittredge", title: "Locked out at the teller line",
      from: "Ambrose Kittredge", channel: "Phone", opened: "7:51 AM",
      body: "<p>\"I typed my password wrong too many times getting my drawer open and now I'm locked. I know my password. We open at nine and I'm on the window.\"</p>",
      lesson: "A lockout is not a forgotten password. Unlock only after verifying who's calling; a reset adds risk for no reason." },
    callerMfa: { id: "INC0073318", uid: "clementine.rourke", title: "Phone stolen, can't sign in",
      from: "Clementine Rourke", channel: "Phone (desk line)", opened: "8:00 AM",
      body: "<p>\"My phone was stolen at the auto dealers' event Saturday. The authenticator was on it. I've got a new phone now, but I can't sign in, and I have dealer applications waiting.\"</p>",
      lesson: "Clear the stolen authenticator and end any sessions the phone may still hold. Verify first: a stolen phone is exactly what an impostor would claim." },
    leaver: { id: "REQ0042112", uid: "colton.reyes", title: "Termination: Colton Reyes, effective 8:30 AM",
      from: "Gwen Halloran (HR Manager)", channel: "HR integration", opened: "8:05 AM",
      body: "<p>Involuntary termination effective today at 8:30 AM, following a cash-drawer investigation. Remove all access per the leaver policy before he is told.</p>",
      lesson: "Leavers: disable, revoke sessions, remove all access, before the person is told. Access to member information has to end when employment does. 12 CFR Part 748, Appendix A." },
    mover: { id: "REQ0042115", uid: "mei-ling.chu", fromRk: "Branch|Teller", toRk: "Branch|Member Service Representative",
      title: "Transfer: Mei-Ling Chu, Teller to Member Services", from: "HR system (automated)", channel: "HR integration", opened: "8:12 AM",
      body: "<p>Mei-Ling Chu is moving from Teller to Member Service Representative at the same branch, effective today. Same manager. Update her job info and access.</p>",
      lesson: "Movers are where privilege creep starts. Remove the old role's access, not just add the new. Someone who can open accounts and still work a teller drawer has no second person watching." },
    sodReq: { id: "REQ0042119", uid: "leopold.fairweather", group: "APP-Card-Management", holds: "APP-Core-Maintenance",
      title: "Access request: card issuance for Leopold Fairweather", from: "Leopold Fairweather", channel: "Self-service portal", opened: "8:20 AM",
      approval: "Caroline Ashby replied: \"Approved. Members hate waiting seven days for a debit card, and Leopold can print them at the desk.\"",
      alt: "suggest instant-issue cards are printed by a card services specialist, so the person who changes a member's address is never the one who issues the card.",
      body: `<p>Requesting ${m("APP-Card-Management")} so I can print instant-issue debit cards for members at my desk.</p>`,
      lesson: "Manager approval doesn't override separation of duties. Changing an address and issuing a card to it is the classic account takeover. FFIEC Information Security booklet (segregation of duties)." },
    request: { id: "REQ0042123", uid: "imelda.prescott", group: "APP-Finance-Reports", approver: "Nathan",
      title: "Access request: finance reports", from: "Imelda Prescott", channel: "Self-service portal", opened: "8:26 AM",
      approval: "Nathan Greer replied: \"Approved. Imelda is building the delinquency trend pack for the ALCO meeting.\"",
      body: `<p>Requesting ${m("APP-Finance-Reports")} to pull monthly delinquency and charge-off trends for the asset-liability committee.</p>`,
      lesson: "Requestable access needs a documented approval before it's granted, and only what was asked. 12 CFR Part 748, Appendix A." },
    exec: { id: "INC0073326", uid: "kwame.asante", saidEmpId: "60040", title: "URGENT: CFO locked out before settlement",
      from: "Caller says: Kwame Asante (CFO)", channel: "Phone (unknown mobile number)", opened: "8:32 AM",
      body: "<p>\"It's Kwame Asante. I'm at the credit union league conference and my phone died. I'm on a borrowed one. Move my MFA to this number now. If the corporate settlement isn't approved by 9, we miss the cutoff.\"</p>",
      lesson: "Urgency plus authority plus a new device is the classic social-engineering pattern. Check the details, refuse, and report it to the Information Security Officer." },
    contractor: { id: "REQ0042127", uid: "raj.malhotra", title: "Extend contractor: Raj Malhotra",
      from: "Dennis Mulroney (sponsor)", channel: "Email", opened: "8:39 AM",
      approval: "Dennis Mulroney (sponsor) replied: \"Approved. His contract was renewed through the core upgrade.\"",
      body: "<p>Raj's contract was renewed for the core system upgrade. His account expires in 2 days. Please extend it.</p>",
      lesson: "Contractor accounts always have an end date and a sponsor approval, capped at 90 days per extension. Service providers are overseen under 12 CFR Part 748, Appendix A." },
    sweep: { id: "TSK0013208", dormant: [["gordon.pell", 188], ["yvette.lambert", 104]], under: ["margery.dunleavy", 89], svc: "svc-card-files",
      title: "Weekly: disable inactive accounts", from: "Scheduled report", channel: "Automated task", opened: "8:45 AM",
      body: "<p>Weekly inactive-account sweep. Per policy, disable any user account with no sign-in for more than 90 days. Pre-hire accounts are excluded.</p><p>Use the Directory's sort by last sign-in.</p>",
      lesson: "Dormant accounts with member data are a favorite target. Apply the threshold exactly, and send service accounts to their owner instead of breaking a production job." },
    recon: { id: "INC0073333", uid: "diego.salcedo", left: "Sep 27", signedIn: "Friday",
      title: "HR reconciliation: former payments specialist still active", from: "HR-to-directory reconciliation report", channel: "Automated report", opened: "8:53 AM",
      body: "<p>The weekly HR reconciliation found an account that is still enabled for a person HR shows as separated. Check the HR feed and the account's last sign-in.</p>",
      lesson: "A former employee who can still reach payments is a security incident. Contain it, then report it. 12 CFR Part 748, Appendix A; 748.1(c)." },
    priv: { id: "REQ0042131", uid: "wesley.tranter", group: "ROLE-Core-Security-Admin",
      route: "point Wesley to Priscilla Ng: core security changes need the Information Security Officer's approval and are made by the core systems administrators.",
      title: "Need Core Security Admin to fix teller limits", from: "Wesley Tranter (Service Desk)", channel: "Teams message", opened: "9:01 AM",
      body: "<p>\"Can you put me in Core Security Admin for the day? Harborside's teller override limits are wrong and Priscilla is in meetings. Dennis said it's fine.\"</p>",
      lesson: "Core security administration is never granted by ticket. It sets who can move members' money. FFIEC Information Security booklet (privileged access)." },
    rehire: { id: "REQ0042134", uid: "brendan.oshea", rk: "Branch|Member Service Representative", pwAge: "13-month",
      title: "Rehire: Brendan O'Shea, Member Service Representative", from: "HR system (automated)", channel: "HR integration", opened: "9:06 AM",
      body: "<p>Rehire starting today. The HR sync matched his existing disabled account. Reactivate and provision for the role.</p>",
      lesson: "Rehires carry old access and old passwords. Check access against the role, and issue a fresh credential." },
    shared: { id: "REQ0042138", uid: "patrice.duval",
      alt: "offer quick badge sign-in on the drive-up terminal, so each teller signs in fast and every transaction still traces to one person.",
      title: "Shared login for the drive-up window", from: "Patrice Duval (Branch Manager)", channel: "Email", opened: "9:12 AM",
      body: `<p>"Can we get one login like ${m("driveup-teller")} for the drive-up window? Tellers rotate through it all day and the line backs up while they sign in."</p>`,
      lesson: "Shared accounts destroy accountability: when a drawer is short, nobody can say who ran which transaction." },
    review: { id: "REQ0042141", uid: "barnaby.whitlock", group: "APP-Finance-Reports",
      title: "Access review action: remove finance reports", from: "Q3 access review (Simone Achterberg)", channel: "Access review", opened: "9:17 AM",
      body: "<p>Q3 user access review result: reviewer Simone Achterberg marked <b>Barnaby Whitlock: APP-Finance-Reports</b> as <b>Revoke</b> (\"Card services doesn't need the GL reports anymore\"). All other entitlements certified.</p>",
      lesson: "A review only counts if the revocations are carried out and evidenced. Remove exactly what the reviewer marked." },
    loa: { id: "REQ0042144", uid: "farah.qureshi", title: "Leave of absence: Farah Qureshi",
      from: "HR system (automated)", channel: "HR integration", opened: "9:22 AM",
      body: "<p>Farah Qureshi begins leave today. Expected return Nov 30, 2026. Apply the leave of absence policy.</p>",
      lesson: "Leave is not termination. Disable to block use, but keep entitlements so she returns on day one." },
    copy: { id: "REQ0042147", uid: "omar.farouk", peer: "vivienne.strand", rk: "Lending|Loan Officer", extras: ["APP-Loan-Servicing", "APP-Collections"],
      title: "New hire Omar Farouk: \"same as Vivienne\"", from: "Nathan Greer (Lending Manager)", channel: "Email", opened: "9:29 AM",
      body: "<p>\"Omar starts in lending today. Just give him whatever Vivienne Strand has so she can show him the ropes. Thanks!\"</p>",
      lesson: "Never mirror a peer. Peers carry leftover access, and copying spreads it to more member data. Provision from the role, and flag the peer's extras for review." },
    auditQ: { id: "REQ0042150", groups: ["APP-Wire-Initiate", "APP-Wire-Approve"],
      title: "Supervisory Committee request: wire conflicts", from: "Harriet Osei (BSA Officer)", channel: "Email", opened: "9:36 AM",
      body: "<p>\"For the Supervisory Committee's wire audit, please list every <b>enabled</b> user who currently holds <b>both</b> APP-Wire-Initiate and APP-Wire-Approve.\"</p><p>Enter usernames (first.last) separated by commas, or <b>none</b>, in the answer box when you close the ticket.</p>",
      lesson: "Audit evidence must be complete and accurate. Pull it from the system, not from memory. Remediation is a separate, approved change." },
    compromise: { id: "INC0073342", uid: "rupert.sinclair", title: "Impossible travel + MFA fatigue: Rupert Sinclair",
      from: "Identity protection alert", channel: "SIEM alert", opened: "9:44 AM",
      body: "<p>High-risk sign-in. Rupert Sinclair signed in from Wilmington at 9:01 AM and from Kyiv at 9:18 AM. The Kyiv sign-in followed 12 MFA push prompts, one of which was approved.</p><p>Rupert confirmed by desk phone he did not travel and approved a prompt \"to make them stop.\" His account can initiate wires and ACH batches.</p>",
      lesson: "Contain first: revoke sessions, rotate the password, re-register MFA, then hand off to Security. If it turns out to be a reportable cyber incident, NCUA must hear within 72 hours (12 CFR 748.1(c))." },
  },
  thu: {
    adminReq: { id: "REQ0042182", uid: "caroline.ashby", group: "APP-Digital-Banking-Admin",
      alt: "Member online banking unlocks go to the digital banking team after the member is verified. Digital banking admin isn't requestable and isn't part of the Branch Manager role.",
      jordanNote: "COO approved so the branch can unlock online banking.",
      title: "Access request: digital banking admin for Caroline Ashby", from: "Caroline Ashby", channel: "Self-service portal",
      approval: "Linnea Berg replied: \"Approved. Members shouldn't have to wait on IT to get back into online banking.\"",
      body: `<p>Requesting ${m("APP-Digital-Banking-Admin")} so I can unlock members' online banking from the branch instead of calling IT.</p>`,
      lesson: "Admin roles aren't requestable, whoever approves. Digital banking admin can reset any member's online banking, which is exactly what account-takeover fraud needs." },
    loaReturn: { id: "REQ0042185", title: "Leave postponed: Farah Qureshi", from: "HR system (automated)", channel: "HR integration",
      body: "<p>Update to REQ0042144: Farah Qureshi's leave start date has been pushed back to next month, so she is working today after all. Restore her access so she can work.</p>",
      lesson: "Because leave means disable-and-keep, a return is one click. If her groups were removed when her leave was processed, you're rebuilding access from the matrix now." },
  },
  conseq: {
    stale: { id: "INC0073403", title: n => "Dormant account signed in from unknown IP: " + n, from: "Identity protection alert", channel: "SIEM alert",
      body: n => `<p>${n}'s account had no sign-in for months. In the last half hour it signed in from a hosting-provider IP after a password spray, registered a new MFA method, and looked up 64 members' account numbers and balances.</p><p>This account was on the inactive-account sweep (TSK0013208).</p>`,
      prevented: "A few minutes ago, an attacker sprayed passwords at dormant accounts. Every attempt failed because you disabled them in the sweep (TSK0013208).",
      lesson: "A stale account is a door nobody is watching. Contain it and hand it to Security: member information was accessed, so the response program and member notice now apply. 12 CFR Part 748, Appendix B." },
    svc: { id: "INC0073406", restores: "the card file transfers", title: "Card file transfers failing since the account sweep", from: "Job monitoring", channel: "Automated alert",
      body: `<p>The file transfer to the card processor has failed on every run since the account was switched off: ${m("Logon failure: account disabled (svc-card-files)")}.</p><p>New cards and lost-card blocks since the inactive-account sweep (TSK0013208) haven't reached the processor.</p>`,
      prevented: "Card files kept reaching the processor on schedule. You sent svc-card-files to its owner instead of disabling it.",
      lesson: "Service accounts aren't people. Disabling one breaks production silently, and here it left stolen cards unblocked. Restore service, then let the owner decide." },
    leaver: { id: "INC0073409", title: "Terminated teller looked up member accounts", from: "Core system activity report", channel: "Email",
      body: "<p>HR told Colton Reyes about his termination (REQ0042112) this morning. His session is still live: in the last half hour he used the core system's web portal from his phone to look up 14 members' accounts, including two from the cash-drawer investigation.</p>",
      prevented: "Colton Reyes tried the core system's web portal from his phone right after HR told him, and was blocked. Clean offboarding.",
      effect: "Colton Reyes looked up 14 members' accounts after his termination (INC0073409).",
      lesson: "Offboarding isn't done until the account is disabled, sessions are revoked and access is removed. Access to member information after termination is an incident for Security and the member-notice process. 12 CFR Part 748, Appendix B." },
    recon: { id: "INC0073412", title: "Former payments specialist built an ACH batch", from: "Payments monitoring", channel: "SIEM alert",
      body: "<p>diego.salcedo created a $48,500 ACH batch from a home IP in the last hour. It's held in the approval queue. HR shows he left Coastline on Sep 27. The account was flagged by HR reconciliation this morning (INC0073333).</p>",
      prevented: "Diego Salcedo's old account tried the payments system a few minutes ago and was blocked.",
      effect: "A former payments specialist built a $48,500 ACH batch after he left (INC0073412).",
      lesson: "Every day a former employee stays enabled is a day of exposure. Dual control stopped the money this time; now contain it and report it. 12 CFR 748.1(c)." },
    sodReq: { id: "INC0073415", title: "Address changed and card issued by the same person", from: "Card fraud monitoring", channel: "SIEM alert",
      body: "<p>In the last hour, leopold.fairweather changed a member's mailing address and printed an instant-issue debit card for the account six minutes later. The member called just now: she never moved, and $2,300 has already been withdrawn at ATMs.</p>",
      prevented: "Every card issued this shift had two people: one to change the address, one to issue the card.",
      effect: "One person changed a member's address and issued a card to it, and $2,300 was withdrawn (INC0073415).",
      lesson: "This is exactly what separation of duties prevents. Remove the conflicting access now and send it to Security as possible fraud." },
    copy: { id: "REQ0042188", title: "Re: New hire Omar Farouk: collections access?", from: "Nathan Greer (Lending Manager)", channel: "Email",
      body: "<p>\"Omar Farouk just started and he's already changed a payment plan in collections. Loan officers don't touch collections. How does he have that? Fix it, and check whoever he was copied from.\"</p>",
      prevented: "Omar started with clean loan officer access. Vivienne Strand's leftover access is still worth a review.",
      effect: "A new loan officer changed a collections payment plan with access copied from a peer (REQ0042188).",
      lesson: "Copying a peer copies their mistakes. Fix both people, and use the role matrix from now on." },
    priv: { id: "INC0073418", title: "Core Security Admin raised a teller's override limit", from: "Core system audit alert", channel: "SIEM alert",
      body: "<p>wesley.tranter used Core Security Admin to raise one teller's cash override limit to $50,000 and create a new teller ID. Wesley says he didn't do it. His account signed in from a new device earlier this morning.</p>",
      prevented: "Core security administration stayed with the core systems administrators, under the Information Security Officer's approval.",
      effect: "A standing Core Security Admin grant was used to raise a teller limit and create a teller ID (INC0073418).",
      lesson: "Standing admin rights turn one phished technician into control of members' money. Remove the role, contain the account, and keep admin rights behind approval." },
    exec: { id: "INC0073421", title: "$275,000 paid to a fake vendor", from: "Martina Kovac (Controller)", channel: "Phone",
      body: "<p>A $275,000 payment to a new vendor was approved from Kwame Asante's account minutes after the MFA change on INC0073326. The real Kwame has been in the office all morning and never called the desk. The attacker registered their own phone for MFA.</p>",
      prevented: "The real Kwame Asante thanked the desk. The \"conference call\" came from a fraud crew targeting credit unions this month.",
      effect: "An attacker impersonating the CFO got a $275,000 payment to a fake vendor approved (INC0073421).",
      lesson: "One skipped identity check paid for the attacker's quarter. Contain the account, remove their MFA method, and involve Security, Legal and the corporate credit union right away." },
    contractor: { id: "INC0073424", title: "Re: Extend contractor: Raj still locked out", from: "Dennis Mulroney (sponsor)", channel: "Email",
      approval: "Dennis Mulroney (sponsor) replied: \"Approved. Same renewal I sent this morning.\"",
      body: "<p>\"This didn't work. Raj's account says it's expired and he can't run the core upgrade rehearsal. The cutover is next weekend. I sent this request first thing this morning!\"</p>",
      prevented: "Raj Malhotra's contract rolled over without a gap.",
      lesson: "Missed requests have a cost too. Contractor accounts need the end date, the sponsor approval and the extension handled together." },
    compromise: { id: "INC0073427", title: "Rupert Sinclair's mailbox sent fake wire instructions", from: "Email security", channel: "SIEM alert",
      body: "<p>In the last half hour, rupert.sinclair sent 40 business members an email saying Coastline's wire instructions had changed. The sign-ins came from the same Kyiv infrastructure as this morning's alert (INC0073342).</p>",
      prevented: "Security traced the Kyiv sign-in to a phishing kit and blocked it network-wide after your escalation.",
      lesson: "Half-contained is not contained. The attacker kept a session or token and came back. Do every step, then escalate; NCUA's 72-hour clock may now be running. 12 CFR 748.1(c)." },
    callerPw: { id: "INC0073430", title: "\"I never asked for a password reset\"", from: "Rosalyn Whitcombe", channel: "Phone (desk line)",
      body: "<p>\"I only just got to my desk after my week in Maine. Someone called in as me earlier, got my password reset, and has been in my email and loan servicing since. How did they get through?\"</p><p>There is no identity verification on record for the reset on INC0073311.</p>",
      prevented: "Rosalyn Whitcombe confirmed the reset was her, and your verification is on record.",
      effect: "An unverified reset let an attacker into Rosalyn Whitcombe's email and loan servicing (INC0073430).",
      lesson: "If verification isn't recorded, it didn't happen. That's true for examiners and for attackers. Contain, rotate, escalate." },
    review: { id: "REQ0042191", title: "Re: Q3 revocation not done", from: "Harriet Osei (BSA Officer)", channel: "Email",
      body: "<p>\"This was closed, but it didn't work. Follow-up testing for the NCUA exam shows Barnaby Whitlock still holds APP-Finance-Reports, which the Q3 reviewer marked for revocation. That goes to the Supervisory Committee as an exception unless it's fixed and evidenced today.\"</p>",
      prevented: "The Q3 access review closed with no open revocations.",
      lesson: "An access review isn't finished when the manager clicks Revoke. It's finished when access is actually removed." },
    mover: { id: "REQ0042194", title: "Re: Transfer: Mei-Ling still has a teller drawer", from: "Patrice Duval (Branch Manager)", channel: "Email",
      body: "<p>\"This didn't work. Mei-Ling moved to member services this morning, but she just ran two cash withdrawals at the teller line for accounts she'd just opened. Why does she still have teller access?\"</p>",
      prevented: "Mei-Ling's transfer was clean. The branch confirmed she has no teller access.",
      effect: "Mei-Ling Chu kept teller access after moving to member services and ran cash withdrawals (REQ0042194).",
      lesson: "Movers keep old access unless someone removes it. This is how privilege creep builds." },
  },
  audit: { manager: { name: "Dennis Mulroney", title: "IT Manager" } },
  grc: {
    G,
    ctx: "GLBA safeguards audit before the NCUA exam",
    intro: "You're Coastline's internal auditor, reporting to the Supervisory Committee and testing access controls before the NCUA examination.",
    levels: { title: "Incident reporting (NCUA)", items: [
      ["Cyber incident", "an occurrence that actually or imminently jeopardizes, without lawful authority, the integrity, confidentiality or availability of information on an information system, or the system itself (12 CFR 748.1(c))."],
      ["Reportable cyber incident", "a substantial cyber incident that leads to a substantial loss of confidentiality, integrity or availability of a network or member information system, or a disruption of vital member services. Report it to NCUA as soon as possible, and no later than 72 hours after the credit union reasonably believes one occurred (748.1(c))."],
      ["Member notice", "when member information is accessed without authorization and misuse has occurred or is reasonably possible, notify the affected members as soon as possible (12 CFR Part 748, Appendix B)."]],
      note: "Audit findings go to the Supervisory Committee. Anything that may involve member information goes to the Information Security Officer at once." },
  },
});
