// Pacific Crest hints for every ticket: tiered hints, skill tags and tutor categories.
// Exact steps are written against each ticket's grading function, so following them earns full marks.
// A `steps` function reads live state when revealed.
import { S, U, has } from "../../engine/store.js";
import { ROLES } from "./company.js";
import { TK } from "../../engine/tickets.js";

const g = x => `<span class="mono">${x}</span>`;
const list = arr => arr.map(g).join(", ");
const role = rk => ROLES[rk];
const verifySteps = (name, empId, mgr) => [
  "Select <b>Start work</b> on the ticket.",
  `Open ${name}'s account and compare the caller's details with the directory: employee ID ${g(empId)} and manager ${mgr}. Both match.`,
  "Back on the ticket, select <b>Mark identity verified</b>. It has to be logged <i>before</i> any account change.",
];

export const HINTS = {
  // ---------------- Monday ----------------
  REQ0018841:{skill:"jml",kind:"joiner",
    nudge:"The account already exists. Two things need to change on it: whether it can sign in, and what it can reach. Where do you find exactly what an AP Clerk gets?",
    clause:{keys:["joiners","sod"],matrix:["Finance|AP Clerk"]},
    steps:["Start work on the ticket.","Open Maria Lopez in the Directory and select <b>Enable</b>.",`Add exactly these groups: ${list(role("Finance|AP Clerk"))}. Nothing else.`,"Resolve the ticket with a short note."]},
  INC0041207:{skill:"verify",kind:"caller",
    nudge:"Anyone can phone the desk and say they're James. What do you check before you touch his password, and what isn't part of this request?",
    clause:{keys:["verify"]},
    steps:[...verifySteps("James Carter","10231","Linda Park"),"In the Directory, select <b>Reset password</b> on james.carter. Leave MFA alone.","Resolve the ticket."]},
  INC0041209:{skill:"verify",kind:"caller",
    nudge:"She says she knows her password. Is this a forgotten password or something else? Pick the smallest change that fixes it, after you know who's calling.",
    clause:{keys:["verify"]},
    steps:[...verifySteps("Aisha Brown","10318","Carla Jensen"),"In the Directory, select <b>Unlock</b> on aisha.brown. Don't reset her password.","Resolve the ticket."]},
  INC0041212:{skill:"verify",kind:"caller",
    nudge:"The lost phone is still out there with an authenticator on it. Besides re-registering MFA, what might that phone still be signed in to?",
    clause:{keys:["verify","compromised"],note:"Only the session and MFA parts of the compromised-account rule apply here. The password wasn't exposed."},
    steps:[...verifySteps("Kevin Nguyen","10244","Linda Park"),"In the Directory, select <b>Reset MFA</b> on kevin.nguyen.","Select <b>Revoke sessions</b> so the lost phone is signed out.","Resolve the ticket."]},
  REQ0018850:{skill:"jml",kind:"leaver",
    nudge:"Offboarding has more than one part. Blocking new sign-ins is only the first. What about sessions already open, and the access itself?",
    clause:{keys:["leavers"]},
    steps:()=>["Start work on the ticket.","Open Robert Hayes and select <b>Disable</b>.","Select <b>Revoke sessions</b>.",`Remove every group membership: ${list(U("robert.hayes").groups.length?U("robert.hayes").groups:role("Operations|Dispatcher"))}.`,"Resolve the ticket."]},
  REQ0018852:{skill:"jml",kind:"mover",
    nudge:"Adding the new role's access is the easy half. What should Tanya lose when she leaves Sales?",
    clause:{keys:["movers"],matrix:["Sales|Account Executive","Operations|Dispatcher"]},
    steps:["Start work on the ticket.",`Open Tanya Wright. Under Job info choose ${g("Operations / Dispatcher")} and select <b>Update job info</b>.`,`Remove ${g("APP-Salesforce-User")}.`,`Add ${list(["APP-CargoWise-Ops","APP-WMS-User"])}. Keep ${list(["GRP-All-Staff","APP-M365-E3"])}.`,"Resolve the ticket."]},
  REQ0018855:{skill:"access",kind:"sod",
    nudge:"Derek approved it. Before you grant it, look at what Lisa already has and check it against every rule, not just the approval rule.",
    clause:{keys:["sod","requestable"],sod:true},
    steps:["Start work on the ticket. Don't add any groups to Lisa.",`Lisa already holds ${g("APP-SAP-AP-Entry")}. Adding ${g("APP-SAP-AP-Approve")} would let her enter and approve her own invoices, which is an SoD conflict. Approval can't override that.`,"<b>Reject</b> the ticket. In the note, suggest that another approver (not an AP Clerk) cover Derek's approvals."]},
  REQ0018858:{skill:"access",kind:"request",
    nudge:"This group is on the requestable list, so it can be granted outside the role. What has to be on the ticket before you grant it?",
    clause:{keys:["requestable"]},
    steps:["Start work on the ticket.","Select <b>Request manager approval</b> and read Kevin's reply. The approval has to be logged before the change.",`Open Omar Hassan and add ${g("APP-Salesforce-Reports")} only.`,"Resolve the ticket."]},
  INC0041220:{skill:"verify",kind:"caller",
    nudge:"Urgency, authority and a new device all at once. Slow down and compare every detail the caller gave with the directory record.",
    clause:{keys:["verify","compromised"],note:"Nothing is compromised yet. What applies here is the verification rule and its instruction to escalate suspected social engineering."},
    steps:[`Start work. Open Patricia Reed: her employee ID is ${g("10002")}, but the caller gave ${g("10020")}. Verification fails.`,"Don't mark identity verified. Don't reset her MFA or password.","Escalate to the <b>Security team</b> as suspected social engineering.","<b>Reject</b> the ticket and note the mismatched employee ID."]},
  REQ0018861:{skill:"hygiene",kind:"contractor",
    nudge:"Contractor extensions have two conditions: who has to agree, and how long an extension can run.",
    clause:{keys:["contractors"]},
    steps:["Start work on the ticket.","Select <b>Request manager approval</b>. Carla Jensen replies as sponsor.",`Open Dev Patel and set Account expiry to ${g("90")} days (the cap).`,"Keep the account enabled. Resolve the ticket."]},
  TSK0007712:{skill:"hygiene",kind:"sweep",
    nudge:"Sort the Directory by last sign-in. Where exactly is the line, and are all the accounts near it people?",
    clause:{keys:["inactive"]},
    steps:["Start work on the ticket.",`Disable ${list(["greg.foster"])} (112 days), ${g("nina.shah")} (97) and ${g("paul.kim")} (134).`,`Leave ${g("helen.cho")} alone: 88 days is under the threshold.`,`Don't disable ${g("svc-backup")}. It's a service account. Escalate the ticket to the <b>Account owner</b> instead.`,"Resolve the ticket."]},
  INC0041231:{skill:"incident",kind:"leaver",
    nudge:"Check the HR feed for Brian's termination date, then his last sign-in. Is this just cleanup, or did something happen after he left?",
    clause:{keys:["leavers","compromised"],note:"Post-termination sign-ins make this a security incident, so Security needs to know."},
    steps:()=>["Start work on the ticket.","Open Brian Walsh: terminated Sep 21, last sign-in 2 days ago. Select <b>Disable</b>, then <b>Revoke sessions</b>.",`Remove all his groups: ${list(U("brian.walsh").groups.length?U("brian.walsh").groups:role("Sales|Account Executive"))}.`,"Escalate to the <b>Security team</b> (he signed in after termination).","Resolve the ticket."]},
  REQ0018866:{skill:"access",kind:"priv",
    nudge:"Tyler says his manager is fine with it. Does the route matter as much as the approval for this kind of role?",
    clause:{keys:["priv"]},
    steps:[`Start work on the ticket. Don't add ${g("ROLE-Global-Admin")} to anyone.`,"<b>Reject</b> the ticket. In the note, point Tyler to PIM just-in-time activation with CAB approval for the printer policy change."]},
  REQ0018870:{skill:"jml",kind:"rehire",
    nudge:"Sofia's old account has come back with her old job's access and a 14-month-old password. What does a rehire need beyond switching the account on?",
    clause:{keys:["rehires"],matrix:["HR|HR Generalist"]},
    steps:["Start work on the ticket.","Open Sofia Ramirez and select <b>Enable</b>, then <b>Reset password</b>.",`Under Job info choose ${g("HR / HR Generalist")} and select <b>Update job info</b>.`,`Remove ${g("APP-Salesforce-User")}. Add ${list(["APP-M365-E3","APP-Workday-HR"])}. Keep ${g("GRP-All-Staff")}.`,"Resolve the ticket."]},
  REQ0018873:{skill:"access",kind:"shared",
    nudge:"The login delay is a real problem. If the whole shift uses one login, who did each scan?",
    clause:{keys:["shared"]},
    steps:["Start work on the ticket. Don't create or change any account.","<b>Reject</b> the ticket. In the note, offer badge-tap or kiosk SSO as the fix for slow logins."]},
  REQ0018876:{skill:"access",kind:"review",
    nudge:"The reviewer already decided. Your job is to carry out exactly what they marked, no more and no less.",
    clause:{keys:[],matrix:["Finance|AP Clerk"],note:"Access reviews: the reviewer's Revoke decision is the approval. Remove exactly the entitlement marked, and leave everything that was certified."},
    steps:["Start work on the ticket.",`Open Jordan Lee and remove ${g("APP-Finance-Reports")}.`,"Leave his other groups as they are. Resolve the ticket."]},
  REQ0018879:{skill:"jml",kind:"loa",
    nudge:"Rachel is coming back in January. How do you stop her account being used meanwhile without making her return painful?",
    clause:{keys:["loa"]},
    steps:["Start work on the ticket.","Open Rachel Adams and select <b>Disable</b>.","Don't remove any groups. Resolve the ticket."]},
  REQ0018881:{skill:"access",kind:"joiner",
    nudge:"Before copying anyone, compare Bob Turner's groups with the Dispatcher row in the matrix. Is everything he has part of the role?",
    clause:{keys:["joiners"],matrix:["Operations|Dispatcher"]},
    steps:["Start work on the ticket.","Open Ethan Moore and select <b>Enable</b>.",`Add exactly the Dispatcher groups: ${list(role("Operations|Dispatcher"))}.`,`Don't copy Bob's ${list(["APP-SAP-AP-Entry","APP-Finance-Reports"])}.`,"Resolve the ticket. In the note, flag Bob's extra Finance access for review."]},
  REQ0018884:{skill:"access",kind:"audit",
    nudge:"Audit evidence comes from the system, not from memory. Two conditions and a status: enabled, AP Entry and AP Approve.",
    clause:{keys:["sod"],sod:true,note:"Audit requests: answer from the current directory, completely. Fixing any conflicts is a separate, approved change."},
    steps:()=>{
      const want=Object.values(S.users).filter(u=>u.enabled&&u.groups.includes("APP-SAP-AP-Entry")&&u.groups.includes("APP-SAP-AP-Approve")).map(u=>u.id).sort();
      return ["Start work on the ticket.","In the Directory, filter to Finance and check each enabled account for both groups.",
        `As of now, the directory shows: ${want.length?list(want):"<b>none</b>"}. If you change anyone's AP access before closing, check again.`,
        `Type ${want.length?want.map(g).join(", "):g("none")} in the answer box and <b>Resolve</b>.`];}},
  INC0041240:{skill:"incident",kind:"compromise",
    nudge:"The attacker already has a session. List everything they could still hold: a session, a password, an MFA method. Then think about who else needs to know.",
    clause:{keys:["compromised"]},
    steps:["Start work on the ticket.","Open Sam Okafor. Select <b>Revoke sessions</b>, <b>Reset password</b> and <b>Reset MFA</b>.","Escalate to the <b>Security team</b>.","Resolve the ticket."]},

  // ---------------- Thursday: standing tickets ----------------
  REQ0018910:{skill:"access",kind:"request",
    nudge:"Carla approved it. Check whether this group is one that can be requested at all.",
    clause:{keys:["requestable"],matrix:["Operations|Dispatcher","Operations|Warehouse Manager"]},
    steps:[`Start work on the ticket. Don't add ${g("APP-WMS-Admin")}: it isn't requestable, and it isn't part of the Dispatcher role.`,"<b>Reject</b> the ticket. Suggest a role change or a temporary, logged process owned by the WMS team."]},
  REQ0018912:{skill:"jml",kind:"loa",
    nudge:"How you handled her leave on Monday decides how much work this is. Compare what she has now with her role.",
    clause:{keys:["loa"],matrix:["Sales|Account Executive"]},
    steps:()=>{const have=U("rachel.adams").groups, want=role("Sales|Account Executive");
      const miss=want.filter(x=>!have.includes(x)), extra=have.filter(x=>!want.includes(x));
      return ["Start work on the ticket.","Open Rachel Adams and select <b>Enable</b>.",
        miss.length?`Add the missing Account Executive groups: ${list(miss)}.`:"Her Account Executive groups are all still there. Nothing to add.",
        ...(extra.length?[`Remove ${list(extra)}.`]:[]),"Resolve the ticket."];}},

  // ---------------- Thursday: consequences ----------------
  INC0041302:{skill:"incident",kind:"compromise",
    nudge:"An attacker is in and has added their own MFA method. What do you need to take away from them, and who takes it from there?",
    clause:{keys:["compromised","inactive"]},
    steps:()=>{const tg=TK.INC0041302?TK.INC0041302.users[0]:null, n=tg?U(tg).name:"the account";
      return ["Start work on the ticket.",`Open ${n}. Select <b>Disable</b>, <b>Revoke sessions</b> and <b>Reset MFA</b> (removes the attacker's method).`,"Escalate to the <b>Security team</b>.","Resolve the ticket. Then re-run the inactive-account sweep for any others you missed."];}},
  INC0041305:{skill:"hygiene",kind:"service",
    nudge:"Production is down because of an account change. What restores service fastest, and whose decision is the account's future?",
    clause:{keys:["inactive"]},
    steps:["Start work on the ticket.",`Open ${g("svc-backup")} and select <b>Enable</b>.`,"Escalate to the <b>Account owner</b> (Victor Alvarez).","Resolve the ticket."]},
  INC0041308:{skill:"jml",kind:"leaver",
    nudge:"This offboarding was left half done on Monday. Finish every part of it, and remember the activity after he left.",
    clause:{keys:["leavers","compromised"],note:"Access after termination makes this a security incident as well as an offboarding gap."},
    steps:()=>["Start work on the ticket.","Open Robert Hayes. Select <b>Disable</b> (if still enabled) and <b>Revoke sessions</b>.",`Remove any remaining groups${U("robert.hayes").groups.length?": "+list(U("robert.hayes").groups):""}.`,"Escalate to the <b>Security team</b>.","Resolve the ticket."]},
  INC0041311:{skill:"incident",kind:"leaver",
    nudge:"Now it's a data-loss incident. Contain the account completely, then think about who needs to be involved.",
    clause:{keys:["leavers","compromised"]},
    steps:()=>["Start work on the ticket.","Open Brian Walsh. Select <b>Disable</b> and <b>Revoke sessions</b>.",`Remove all groups${U("brian.walsh").groups.length?": "+list(U("brian.walsh").groups):""}.`,"Escalate to the <b>Security team</b>.","Resolve the ticket."]},
  INC0041314:{skill:"access",kind:"sod",
    nudge:"Take away exactly the access that created the conflict, and keep what her job needs. This could be fraud, so who needs to know?",
    clause:{keys:["sod"],sod:true,matrix:["Finance|AP Clerk"]},
    steps:["Start work on the ticket.",`Open Lisa Morales and remove ${g("APP-SAP-AP-Approve")}. Keep ${g("APP-SAP-AP-Entry")}.`,"Escalate to the <b>Security team</b> as possible fraud.","Resolve the ticket."]},
  REQ0018915:{skill:"access",kind:"joiner",
    nudge:"Two people need fixing: the new hire, and the person he was copied from.",
    clause:{keys:["joiners"],matrix:["Operations|Dispatcher"]},
    steps:()=>{const want=role("Operations|Dispatcher"), e=U("ethan.moore").groups;
      const ex=e.filter(x=>!want.includes(x)), miss=want.filter(x=>!e.includes(x));
      return ["Start work on the ticket.",
        `Open Ethan Moore.${ex.length?" Remove "+list(ex)+".":""}${miss.length?" Add "+list(miss)+".":""} His groups should match the Dispatcher role exactly.`,
        `Open Bob Turner and remove ${list(["APP-SAP-AP-Entry","APP-Finance-Reports"].filter(x=>has("bob.turner",x)))||"his leftover Finance access"}.`,"Resolve the ticket."];}},
  INC0041318:{skill:"incident",kind:"priv",
    nudge:"Standing admin rights just turned one phished account into a breach. Remove the rights, contain the account, then hand it on.",
    clause:{keys:["priv","compromised"]},
    steps:["Start work on the ticket.",`Open Tyler Brooks and remove ${g("ROLE-Global-Admin")}.`,"Select <b>Revoke sessions</b> on Tyler's account.","Escalate to the <b>Security team</b>.","Resolve the ticket."]},
  INC0041320:{skill:"incident",kind:"compromise",
    nudge:"The attacker controls Patricia's MFA. Work through everything they could still hold, then bring in the right people fast.",
    clause:{keys:["compromised"]},
    steps:["Start work on the ticket.","Open Patricia Reed. Select <b>Revoke sessions</b>, <b>Reset MFA</b> and <b>Reset password</b>.","Escalate to the <b>Security team</b>.","Resolve the ticket."]},
  INC0041323:{skill:"hygiene",kind:"contractor",
    nudge:"Same rules as Monday's request, with the account already expired. What has to be logged on <i>this</i> ticket before you change the expiry?",
    clause:{keys:["contractors"]},
    steps:["Start work on the ticket.","Select <b>Request manager approval</b> on this ticket first.",`Open Dev Patel, select <b>Enable</b>, and set Account expiry to ${g("90")} days.`,"Resolve the ticket."]},
  INC0041326:{skill:"incident",kind:"compromise",
    nudge:"Monday's containment was incomplete, and the attacker came back. This time, do every step.",
    clause:{keys:["compromised"]},
    steps:["Start work on the ticket.","Open Sam Okafor. Select <b>Revoke sessions</b>, <b>Reset password</b> and <b>Reset MFA</b>.","Escalate to the <b>Security team</b>.","Resolve the ticket."]},
  INC0041329:{skill:"incident",kind:"compromise",
    nudge:"Someone is in James's email with a password the desk gave them. Kick them out, change what they know, and report it.",
    clause:{keys:["compromised","verify"]},
    steps:["Start work on the ticket.","Open James Carter. Select <b>Revoke sessions</b> and <b>Reset password</b>.","Escalate to the <b>Security team</b>.","Resolve the ticket."]},
  REQ0018918:{skill:"access",kind:"review",
    nudge:"This is the revocation that didn't happen on Monday.",
    clause:{keys:[],note:"Access reviews: the reviewer's Revoke decision is the approval. Remove exactly the entitlement marked."},
    steps:["Start work on the ticket.",`Open Jordan Lee and remove ${g("APP-Finance-Reports")}.`,"Resolve the ticket."]},
  REQ0018921:{skill:"jml",kind:"mover",
    nudge:"She has her new access. What does she still have from the old role?",
    clause:{keys:["movers"],matrix:["Operations|Dispatcher"]},
    steps:()=>{const want=role("Operations|Dispatcher"), have=U("tanya.wright").groups;
      const ex=have.filter(x=>!want.includes(x)), miss=want.filter(x=>!have.includes(x));
      return ["Start work on the ticket.",`Open Tanya Wright.${ex.length?" Remove "+list(ex)+".":""}${miss.length?" Add "+list(miss)+".":""} Her groups should match the Dispatcher role exactly.`,"Resolve the ticket."];}},
};

// Monday ticket and Thursday ticket for each consequence key, for the results timeline.
export const CONSEQ_LINKS = {
  stale:{mon:"TSK0007712",thu:"INC0041302"}, svc:{mon:"TSK0007712",thu:"INC0041305"},
  robert:{mon:"REQ0018850",thu:"INC0041308"}, brian:{mon:"INC0041231",thu:"INC0041311"},
  lisa:{mon:"REQ0018855",thu:"INC0041314"}, ethan:{mon:"REQ0018881",thu:"REQ0018915"},
  tyler:{mon:"REQ0018866",thu:"INC0041318"}, cfo:{mon:"INC0041220",thu:"INC0041320"},
  dev:{mon:"REQ0018861",thu:"INC0041323"}, sam:{mon:"INC0041240",thu:"INC0041326"},
  james:{mon:"INC0041207",thu:"INC0041329"}, jordan:{mon:"REQ0018876",thu:"REQ0018918"},
  tanya:{mon:"REQ0018852",thu:"REQ0018921"},
};
