// Pacific Crest Logistics' PAM shift. The kit (lib/pamKit.js) supplies grading, hints, the playbook
// and the PAM runbook; this file is the story. Lessons cite NIST SP 800-53 Rev. 5 and SOX IT
// general controls (logical access to financially significant systems).
import { buildPam } from "../lib/pamKit.js";
import * as company from "./company.js";
import * as policy from "./policy.js";

const n53 = id => ({ label: `NIST SP 800-53 Rev. 5, ${id}`, href: "https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final" });
const SOX = { label: "SOX ITGC (PCAOB AS 2201)", href: "https://pcaobus.org/oversight/standards/auditing-standards/details/AS2201" };
const ADMIN = "IT|Systems Administrator", STAFF = ["GRP-All-Staff", "APP-M365-E3", "APP-ServiceNow-Agent"];

export const pam = buildPam({
  id: "pacific-crest",
  eligible: { [ADMIN]: ["ROLE-Server-Admin", "ROLE-SAP-Basis-Admin"], "IT|IT Manager": ["ROLE-User-Admin"], "Vendors|WMS Vendor Support": ["ROLE-WMS-Server-Admin"] },
  also: ["ROLE-Global-Admin"],
  roles: { [ADMIN]: [...STAFF, "ROLE-Server-Admin", "ROLE-SAP-Basis-Admin"], "Vendors|WMS Vendor Support": ["GRP-Contractors"] },
  cast: [
    ["marco.silva", "Marco Silva", "10341", ADMIN, "Victor Alvarez"],
    ["june.harper", "June Harper", "10343", ADMIN, "Victor Alvarez", { groups: [...STAFF, "ROLE-Server-Admin"] }],
    ["felix.grant", "Felix Grant", "10345", "IT|Service Desk Tech", "Victor Alvarez", { groups: [...STAFF, "ROLE-Helpdesk-Admin", "ROLE-SAP-Basis-Admin"] }],
    ["iris.boyd", "Iris Boyd", "10347", ADMIN, "Victor Alvarez"],
    ["raymond.oconnor", "Raymond O'Connor", "10349", ADMIN, "Victor Alvarez", { groups: [...STAFF, "ROLE-Server-Admin"], jit: { "ROLE-Server-Admin": 2 } }],
    ["nathan.cole", "Nathan Cole", "10351", ADMIN, "Victor Alvarez"],
    ["owen.price", "Owen Price", "10353", "IT|Service Desk Tech", "Victor Alvarez"],
    ["lena.vogt", "Lena Vogt", "V-0417", "Vendors|WMS Vendor Support", "Marcus Bell (sponsor)", { type: "Contractor", enabled: false, expiry: 200, last: 41 }],
    ["svc-wms-sync", "svc-wms-sync", "SVC-007", null, "Victor Alvarez (owner)", { dept: "IT", title: "Service account: WMS to SAP inventory sync", type: "Service", groups: ["SVC-WMS-Integration"], mfa: false }],
    ["bg-admin-01", "bg-admin-01", "BG-01", null, "Victor Alvarez (owner)", { dept: "IT", title: "Break-glass account: emergency Global Admin", type: "Break-glass", groups: ["ROLE-Global-Admin"], enabled: false, mfa: false, last: 188 }],
  ],
  hr: [{ type: "Termination", who: "Nathan Cole", detail: "Involuntary. Effective today, 10:00 AM. Systems Administrator with server and SAP Basis admin eligibility.", when: 0 }],
  cite: { "pam-jit": [n53("AC-6(5)"), n53("AC-2(6)"), SOX], "pam-eligible": [n53("AC-2(7)"), SOX], "pam-breakglass": [n53("AC-2(2)"), n53("IA-5")],
    "pam-vault": [n53("IA-5"), n53("AC-2k")], "pam-session": [n53("AC-6(9)"), n53("AU-6")], "pam-vendor": [n53("AC-17(4)"), n53("AC-2(2)")], "pam-shared": [n53("IA-2"), n53("AC-2k")] },
  mon: {
    jit: { id: "REQ0019101", uid: "marco.silva", group: "ROLE-SAP-Basis-Admin", hours: 3, change: "CHG0040312", approver: "Dana Whitfield",
      what: "apply the quarter-end SAP kernel patch", from: "Marco Silva", channel: "Portal", opened: "6:50 AM",
      lesson: "Activate an eligible role for the approved window only, with the approval on the ticket first. Admin access to SAP is a SOX key control. NIST AC-6(5), AC-2(6)." },
    breakGlass: { id: "INC0042101", uid: "victor.alvarez", bg: "bg-admin-01", title: "Emergency: admins locked out, need break-glass", from: "Victor Alvarez", channel: "Phone", opened: "7:05 AM",
      body: "<p>\"It's Victor. Conditional access is blocking every admin sign-in after last night's policy change, and the trucks can't be dispatched until we fix the CargoWise connector. I'm declaring an emergency. I need bg-admin-01 turned on.\"</p>",
      lesson: "Break-glass access is real admin power with no MFA in front of it. Verify the caller, enable only the documented account, and tell Security straight away. NIST AC-2(2)." },
    notEligible: { id: "REQ0019104", uid: "owen.price", group: "ROLE-Server-Admin", title: "Server admin for the service desk", from: "Owen Price", channel: "Portal", opened: "7:25 AM",
      body: "<p>The warehouse label printers drop off the print server every morning and the sysadmins don't start until 8. If I had server admin I could restart the spooler myself. Victor's approved it.</p>",
      alt: "explain that Service Desk Techs aren't eligible for ROLE-Server-Admin. The print server fix goes to a Systems Administrator under a change.",
      lesson: "Eligibility for a privileged role comes from the job. A manager's approval can't add a role the job doesn't include. NIST AC-2(7), AC-6." },
    rotate: { id: "REQ0019107", svc: "svc-wms-sync", down: "The WMS to SAP inventory sync", title: "svc-wms-sync password in a support email", from: "Marcus Bell", channel: "Email", opened: "7:40 AM",
      body: "<p>Our WMS vendor emailed us the svc-wms-sync password in plain text while debugging last night, and the email went to the whole warehouse-ops distribution list, about 60 people.</p><p>Please sort out the password. Inventory has to keep syncing to SAP or the cycle count is off.</p>",
      lesson: "An exposed service credential is rotated, not disabled. Production keeps running and the leaked password stops working. NIST IA-5." },
    standing: { id: "TSK0008101", holders: [["june.harper", "ROLE-Server-Admin"], ["felix.grant", "ROLE-SAP-Basis-Admin"]], bg: "bg-admin-01", bgGroup: "ROLE-Global-Admin",
      title: "PAM report: standing privileged memberships", from: "PAM vault (weekly report)", channel: "Automated", opened: "8:00 AM",
      body: "<p>These accounts hold a vaulted role permanently instead of activating it:</p><ul><li><span class=\"mono\">june.harper</span>: ROLE-Server-Admin (since the vault migration)</li><li><span class=\"mono\">felix.grant</span>: ROLE-SAP-Basis-Admin (added for a month-end issue in August)</li><li><span class=\"mono\">bg-admin-01</span>: ROLE-Global-Admin</li></ul><p>Clean up the standing access per the PAM runbook.</p>",
      lesson: "Standing admin access to financial systems is exactly what SOX access testing looks for. Remove it, except where the runbook documents an exception. NIST AC-2(7)." },
    adminLeaver: { id: "REQ0019110", uid: "nathan.cole", svc: "svc-backup", title: "Termination: Nathan Cole, Systems Administrator", from: "HR system (automated)", channel: "HR integration", opened: "8:15 AM",
      body: "<p>Involuntary termination, effective 10:00 AM today. Remove all access before the meeting.</p><p>PAM vault note: Nathan checked out the <span class=\"mono\">svc-backup</span> password on Monday and it hasn't been rotated since.</p>",
      lesson: "An admin leaver's access ends only when what they knew stops working: rotate any credential they checked out. NIST PS-4, IA-5." },
    vendor: { id: "REQ0019113", uid: "lena.vogt", group: "ROLE-WMS-Server-Admin", hours: 2, title: "Vendor support session: WMS upgrade fix", from: "Marcus Bell", channel: "Portal", opened: "8:30 AM",
      body: "<p>Lena from the WMS vendor needs admin on the WMS servers to fix the pick-list bug from Saturday's upgrade. The session is booked from 9:00 to 11:00 AM. Her account is off until we need it.</p>",
      lesson: "Vendor access is opened for one approved session: sponsor approval, the account enabled, the role for the session only. NIST AC-17(4)." },
    noChange: { id: "REQ0019116", uid: "iris.boyd", group: "ROLE-Server-Admin", target: "The Reno warehouse file server", title: "Server admin for the weekend", from: "Iris Boyd", channel: "Portal", opened: "9:00 AM",
      body: "<p>I'd like to tidy up the old scan folders on the Reno warehouse file server this weekend. Can you activate server admin for me from Friday night to Sunday night, about 48 hours? I haven't raised a change, it's just housekeeping.</p>",
      alt: "explain that eligibility isn't enough: the work needs an approved change, and activations are capped at 4 hours.",
      lesson: "Eligible isn't approved. Privileged roles are activated for an approved change, for a short window. NIST AC-6(5), AC-2(6)." },
    session: { id: "REQ0019119", title: "Weekly privileged session review", from: "Security team", channel: "Email", opened: "9:25 AM",
      intro: "<p>Yesterday's recorded admin sessions are below. Check each one against the change or incident it was opened for, and send us the IDs of any session that went outside it.</p>",
      rows: [
        ["PSM-31104", "june.harper", "CHG0040290: patch the dispatch servers", "DSP-APP-01", "Installed patches, rebooted, confirmed the dispatch board loads", false],
        ["PSM-31109", "felix.grant", "CHG0040295: transport a pricing fix to SAP production", "SAP-PRD", "Imported the transport, <b>opened the vendor bank details table and changed one vendor's account number</b>", true],
        ["PSM-31117", "marco.silva", "INC0042050: SAP job failures", "SAP-PRD", "Read the job logs, restarted two failed batch jobs", false],
        ["PSM-31120", "iris.boyd", "CHG0040301: add disk to the scanner share", "FS-RNO-01", "Extended the volume, <b>turned off the antivirus service</b>", true],
        ["PSM-31126", "raymond.oconnor", "CHG0040304: renew the TMS certificate", "TMS-WEB-01", "Imported the certificate, restarted the web service", false],
      ],
      lesson: "A recorded session only protects you if someone compares it with the reason it was opened. NIST AC-6(9) (log privileged functions), AU-6 (review audit records)." },
    compromised: { id: "INC0042104", uid: "raymond.oconnor", group: "ROLE-Server-Admin", title: "SIEM alert: admin sign-in from abroad", from: "SIEM alert", channel: "Automated", opened: "9:45 AM",
      body: "<p>At 5:58 AM <span class=\"mono\">raymond.oconnor</span> approved an MFA prompt after 27 push requests, signed in from an IP address in Brazil, and activated ROLE-Server-Admin for 2 hours. Raymond is at home in Sacramento and says he approved a prompt to make it stop.</p>",
      lesson: "A compromised admin account is contained when the attacker has nothing left: no session, password, MFA method or privileged role. Then Security takes it. NIST IR-4." },
    shared: { id: "REQ0019122", uid: "tyler.brooks", title: "Shared admin login for the night desk", from: "Tyler Brooks", channel: "Portal", opened: "10:00 AM",
      body: "<p>The night dispatch desk keeps calling about stuck print jobs and nobody on nights has server rights. Could we make one shared <span class=\"mono\">nightops-admin</span> login, or just give them the server admin password?</p>",
      alt: "explain that admin passwords are never shared. Night-shift admins check credentials out of the vault under their own accounts, and urgent work goes to the on-call Systems Administrator.",
      lesson: "Shared admin credentials make every change anonymous and can't be taken back from one person. NIST IA-2, AC-2k." },
    auditQ: { id: "REQ0019125", group: "ROLE-Server-Admin", title: "Auditor request: who holds server admin", from: "External auditors (SOX)", channel: "Email", opened: "10:15 AM",
      body: "<p>For our SOX access testing, please list every enabled account that holds <span class=\"mono\">ROLE-Server-Admin</span> right now, including any just-in-time activations still running. Usernames are fine.</p>",
      lesson: "Audit evidence is pulled from the system as it stands. SOX ITGC (logical access) and NIST AC-2(7)." },
  },
  thu: {
    bgClose: { id: "TSK0008104", from: "Victor Alvarez", channel: "Portal", opened: "10:40 AM",
      body: "<p>Conditional access is fixed and admins can sign in again. Emergency over as of 10:30 AM. Please close out bg-admin-01 per the break-glass procedure.</p>",
      lesson: "Break-glass is closed as deliberately as it's opened: disabled, rotated and signed out. NIST AC-2(2), IA-5." },
    vendorEnd: { id: "TSK0008107", from: "Marcus Bell", channel: "Portal", opened: "11:05 AM",
      body: "<p>Lena fixed the pick-list bug and the session is over. Please close her access.</p>",
      lesson: "Third-party access ends with the session. NIST AC-17(4)." },
  },
  conseq: {
    standingJit: { id: "INC0042110", from: "PAM vault", channel: "Automated", opened: "Afternoon" },
    notEligible: { id: "INC0042113", from: "Security team", channel: "Email", opened: "Afternoon" },
    svcDown: { id: "INC0042116", from: "Marcus Bell", channel: "Phone", opened: "Afternoon" },
    svcLeak: { id: "INC0042119", from: "SIEM alert", channel: "Automated", opened: "Afternoon" },
    leaver: { id: "INC0042122", from: "Security team", channel: "Email", opened: "Afternoon" },
    noChange: { id: "INC0042125", from: "Security team", channel: "Email", opened: "Afternoon" },
    compromised: { id: "INC0042128", from: "SIEM alert", channel: "Automated", opened: "Afternoon" },
    bgOpen: { id: "INC0042131", from: "PAM vault", channel: "Automated", opened: "Afternoon" },
    vendorOpen: { id: "INC0042134", from: "Security team", channel: "Email", opened: "Afternoon" },
  },
}, company, policy);
