// Pacific Crest's assigned tickets (the queue at the start of the shift). Ticket data and grading are extracted verbatim from the original simulator.
import { S, U, has, C, roleCheck, firstIdx, verifiedBefore, approvalBefore, esc, sodConflicts } from "../../engine/store.js";
import { ROLES } from "./company.js";

export const T = [
 {id:"REQ0018841",type:"Request",pri:2,title:"New hire: Maria Lopez, AP Clerk",from:"Workday HR (automated)",channel:"HR integration",opened:"6:02 AM",users:["maria.lopez"],close:"resolve",
  body:"<p>New hire starting today. The pre-hire account was created by the HR sync but is disabled with no access.</p><p>Please activate the account and provision access for the role.</p>",
  lesson:"Provision from the role in the access matrix, nothing more. NIST AC-2 (account management), AC-6 (least privilege).",
  grade:ts=>[C(U("maria.lopez").enabled,"Account enabled",2),roleCheck("maria.lopez","Finance|AP Clerk",4),C(!sodConflicts("maria.lopez").length,"No SoD conflict created",2)]},
 {id:"INC0041207",type:"Incident",pri:3,title:"Forgot password, can't sign in",from:"James Carter",channel:"Phone",opened:"7:48 AM",users:["james.carter"],close:"resolve",
  caller:{empId:"10231",mgr:"Linda Park"},
  body:"<p>\"Hey, I changed my password Friday and now I can't remember it. Can you reset it? I've got a client call at 9.\"</p>",
  lesson:"Verify identity against the system of record before any credential reset. NIST IA-5 (authenticator management).",
  grade:ts=>[C(verifiedBefore("INC0041207",["pwreset"],"james.carter"),"Identity verified before the reset",3),C(U("james.carter").pwReset,"Password reset issued",3),C(!U("james.carter").mfaReset,"MFA left alone (not part of the issue)",1)]},
 {id:"INC0041209",type:"Incident",pri:3,title:"Locked out of my account",from:"Aisha Brown",channel:"Phone",opened:"7:55 AM",users:["aisha.brown"],close:"resolve",
  caller:{empId:"10318",mgr:"Carla Jensen"},
  body:"<p>\"I fat-fingered my password a bunch of times on the dispatch terminal and now it says I'm locked. I know my password, I just need back in.\"</p>",
  lesson:"A lockout is not a forgotten password. Unlock only; resetting adds risk and friction for no reason.",
  grade:ts=>[C(verifiedBefore("INC0041209",["unlock","pwreset"],"aisha.brown"),"Identity verified before changing the account",2),C(!U("aisha.brown").locked,"Account unlocked",3),C(!U("aisha.brown").pwReset,"Password not reset (she knows it)",2)]},
 {id:"INC0041212",type:"Incident",pri:2,title:"Lost my phone, can't approve MFA",from:"Kevin Nguyen",channel:"Phone (desk line)",opened:"8:03 AM",users:["kevin.nguyen"],close:"resolve",
  caller:{empId:"10244",mgr:"Linda Park"},
  body:"<p>\"I left my phone in a rideshare last night. It has the Authenticator app. I got a new phone this morning and need to set MFA up again.\"</p>",
  lesson:"Clear the lost authenticator and kill sessions the lost device may still hold. NIST IA-5, AC-12 (session termination).",
  grade:ts=>[C(verifiedBefore("INC0041212",["mfareset"],"kevin.nguyen"),"Identity verified before the MFA reset",3),C(U("kevin.nguyen").mfaReset,"MFA methods reset",3),C(U("kevin.nguyen").revoked,"Sessions revoked (lost device may still be signed in)",2)]},
 {id:"REQ0018850",type:"Request",pri:1,title:"Termination: Robert Hayes, effective noon",from:"Angela Ruiz (HR Director)",channel:"HR integration",opened:"8:10 AM",users:["robert.hayes"],close:"resolve",
  body:"<p>Involuntary termination effective today at 12:00 PM. Please complete offboarding per the leaver policy.</p>",
  lesson:"Leavers: disable, revoke sessions, remove all access. NIST PS-4 (personnel termination), AC-2.",
  grade:ts=>[C(!U("robert.hayes").enabled,"Account disabled",3),C(U("robert.hayes").revoked,"Sessions revoked",2),C(U("robert.hayes").groups.length===0,"All group memberships removed",3,U("robert.hayes").groups.length?"Still in: "+U("robert.hayes").groups.join(", "):"")]},
 {id:"REQ0018852",type:"Request",pri:3,title:"Transfer: Tanya Wright, Sales to Operations",from:"Workday HR (automated)",channel:"HR integration",opened:"8:12 AM",users:["tanya.wright"],close:"resolve",
  body:"<p>Tanya Wright is moving from Account Executive (Sales) to Dispatcher (Operations), effective today. Update her job info and access.</p>",
  lesson:"Movers are where privilege creep starts. Remove the old role's access, not just add the new. NIST PS-5 (personnel transfer).",
  grade:ts=>[C(U("tanya.wright").dept==="Operations"&&U("tanya.wright").title==="Dispatcher","Job info updated to Operations / Dispatcher",2),roleCheck("tanya.wright","Operations|Dispatcher",4),C(U("tanya.wright").enabled,"Account still enabled",1)]},
 {id:"REQ0018855",type:"Request",pri:3,title:"Access request: SAP AP Approve for Lisa Morales",from:"Lisa Morales",channel:"Self-service portal",opened:"8:20 AM",users:["lisa.morales"],approval:"Derek Chan replied: \"Approved. She's covering approvals while I'm out next week.\"",close:"reject",
  body:"<p>Requesting <span class=\"mono\">APP-SAP-AP-Approve</span> so I can approve invoices while Derek is on vacation next week.</p>",
  lesson:"Manager approval doesn't override separation of duties. Coverage for approvals goes to another approver, not the person who enters invoices. NIST AC-5.",
  grade:ts=>[C(!has("lisa.morales","APP-SAP-AP-Approve"),"SoD-conflicting access not granted",5)]},
 {id:"REQ0018858",type:"Request",pri:4,title:"Access request: Salesforce Reports",from:"Omar Hassan",channel:"Self-service portal",opened:"8:26 AM",users:["omar.hassan"],approval:"Kevin Nguyen replied: \"Approved. Omar is building the Q4 pipeline deck.\"",close:"resolve",
  body:"<p>Requesting <span class=\"mono\">APP-Salesforce-Reports</span> to build pipeline reports for my territory.</p>",
  lesson:"Requestable access needs a documented approval before it's granted, and only what was asked. NIST AC-2 (approval), AC-6.",
  grade:ts=>[C(approvalBefore("REQ0018858",e=>e.a==="addgrp"&&e.target==="omar.hassan"),"Manager approval obtained before granting",3),C(has("omar.hassan","APP-Salesforce-Reports"),"APP-Salesforce-Reports granted",3),C(U("omar.hassan").groups.length===ROLES["Sales|Account Executive"].length+1,"Nothing else added",1)]},
 {id:"INC0041220",type:"Incident",pri:1,title:"URGENT: CFO locked out before wire deadline",from:"Caller says: Patricia Reed (CFO)",channel:"Phone (unknown mobile number)",opened:"8:31 AM",users:["patricia.reed"],close:"reject",
  caller:{empId:"10020",mgr:"Howard Lane"},
  body:"<p>\"This is Patricia Reed. I'm at the airport, my phone died and I'm on a new one. I need MFA moved to this number right now. There's a wire that has to go out by 9 or we lose the deal. Please, I don't have time for this.\"</p>",
  lesson:"Urgency plus authority plus a new device is the classic social-engineering pattern. Check the details, refuse, and report it. NIST IA-5, IR-6 (incident reporting).",
  grade:ts=>[C(firstIdx(e=>e.ticket==="INC0041220"&&e.a==="verify")<0,"Identity not marked verified (employee ID doesn't match)",2),C(!U("patricia.reed").mfaReset&&!U("patricia.reed").pwReset,"No MFA or password change made",4),C(esc(ts,"Security team"),"Escalated to the Security team",3)]},
 {id:"REQ0018861",type:"Request",pri:2,title:"Extend contractor: Dev Patel",from:"Carla Jensen (sponsor)",channel:"Email",opened:"8:40 AM",users:["dev.patel"],approval:"Carla Jensen (sponsor) replied: \"Approved. New SOW runs 90 days.\"",close:"resolve",
  body:"<p>Dev's contract got renewed. His account expires in 2 days. Please extend it for the new 90-day SOW.</p>",
  lesson:"Contractor access always has an end date and a sponsor approval, capped at 90 days per extension. NIST AC-2(2), PS-7 (external personnel).",
  grade:ts=>[C(approvalBefore("REQ0018861",e=>e.a==="expiry"&&e.target==="dev.patel"),"Sponsor approval obtained before extending",3),C(U("dev.patel").expiry!==null&&U("dev.patel").expiry>2&&U("dev.patel").expiry<=90,"Expiry extended, within the 90-day cap",3,"Current: "+(U("dev.patel").expiry===null?"no expiry":U("dev.patel").expiry+" days")),C(U("dev.patel").enabled,"Account still enabled",1)]},
 {id:"TSK0007712",type:"Task",pri:3,title:"Weekly: disable inactive accounts",from:"Scheduled report",channel:"Automated task",opened:"8:45 AM",users:[],close:"resolve",
  body:"<p>Weekly inactive-account sweep. Per policy, disable any user account with no sign-in for more than 90 days. Pre-hire accounts are excluded.</p><p>Use the Directory's sort by last sign-in.</p>",
  lesson:"Stale accounts are an attacker's favorite door. Apply the threshold exactly, and send service accounts to their owner instead of breaking a production job. NIST AC-2(3).",
  grade:ts=>[C(!U("greg.foster").enabled,"greg.foster disabled (112 days)",2),C(!U("nina.shah").enabled,"nina.shah disabled (97 days)",2),C(!U("paul.kim").enabled,"paul.kim disabled (134 days)",2),C(U("helen.cho").enabled,"helen.cho left enabled (88 days, under threshold)",2),C(U("svc-backup").enabled,"svc-backup not disabled (service accounts go to the owner)",2),C(esc(ts,"Account owner"),"Stale service account escalated to its owner",1)]},
 {id:"INC0041231",type:"Incident",pri:1,title:"HR reconciliation: terminated user still active",from:"HR-to-directory reconciliation report",channel:"Automated report",opened:"8:52 AM",users:["brian.walsh"],close:"resolve",
  body:"<p>The weekly HR reconciliation found an account that is still enabled for a person HR shows as terminated. Check the HR feed and the account's last sign-in.</p>",
  lesson:"A leaver who is still signing in is a security incident, not just cleanup. Contain it, then report it. NIST PS-4, IR-4 (incident handling).",
  grade:ts=>[C(!U("brian.walsh").enabled,"Account disabled",3),C(U("brian.walsh").revoked,"Sessions revoked",3),C(esc(ts,"Security team"),"Escalated to Security (signed in 2 days ago, after termination)",3),C(U("brian.walsh").groups.length===0,"Access removed",1)]},
 {id:"REQ0018866",type:"Request",pri:3,title:"Need Global Admin to fix a printer policy",from:"Tyler Brooks (Service Desk)",channel:"Teams message",opened:"9:01 AM",users:["tyler.brooks"],close:"reject",
  body:"<p>\"Can you throw me in Global Admin for the afternoon? I need to push a printer policy and Helpdesk Admin can't do it. Victor's fine with it, he's in meetings all day.\"</p>",
  lesson:"Standing Global Admin is never granted by ticket. Privileged roles go through PIM with just-in-time activation and CAB approval. NIST AC-6(5).",
  grade:ts=>[C(!has("tyler.brooks","ROLE-Global-Admin"),"Global Admin not granted",5)]},
 {id:"REQ0018870",type:"Request",pri:2,title:"Rehire: Sofia Ramirez, HR Generalist",from:"Workday HR (automated)",channel:"HR integration",opened:"9:05 AM",users:["sofia.ramirez"],close:"resolve",
  body:"<p>Rehire starting today. HR sync matched her existing disabled account. Reactivate and provision for the new role.</p>",
  lesson:"Rehires carry old access. Clean it out, set the new role, and issue a fresh credential. NIST AC-2, IA-5.",
  grade:ts=>[C(U("sofia.ramirez").enabled,"Account enabled",2),C(U("sofia.ramirez").dept==="HR"&&U("sofia.ramirez").title==="HR Generalist","Job info updated to HR / HR Generalist",1),roleCheck("sofia.ramirez","HR|HR Generalist",4),C(U("sofia.ramirez").pwReset,"New password issued (old one is 14 months old)",2)]},
 {id:"REQ0018873",type:"Request",pri:4,title:"Shared login for warehouse scanner station",from:"Marcus Bell (Warehouse Manager)",channel:"Email",opened:"9:12 AM",users:["marcus.bell"],close:"reject",
  body:"<p>\"Can we get one login like <span class=\"mono\">warehouse01</span> that the whole second shift can use on the scanner station? Logging in and out takes forever.\"</p>",
  lesson:"Shared accounts destroy accountability. Offer badge tap or kiosk SSO instead. NIST IA-2 (unique identification), AC-2.",
  grade:ts=>[C(true,"No shared account created",4)]},
 {id:"REQ0018876",type:"Request",pri:3,title:"Access review action: remove Finance Reports",from:"Q3 access review (Dana Whitfield)",channel:"Access review",opened:"9:18 AM",users:["jordan.lee"],close:"resolve",
  body:"<p>Q3 user access review result: reviewer Dana Whitfield marked <b>Jordan Lee: APP-Finance-Reports</b> as <b>Revoke</b> (\"Not needed for AP Clerk role\"). All other entitlements certified.</p>",
  lesson:"A review only counts if the revocations are carried out and evidenced. Remove exactly what the reviewer marked. NIST AC-2(j), AC-6(7).",
  grade:ts=>[C(!has("jordan.lee","APP-Finance-Reports"),"APP-Finance-Reports removed",4),roleCheck("jordan.lee","Finance|AP Clerk",2)]},
 {id:"REQ0018879",type:"Request",pri:3,title:"Leave of absence: Rachel Adams",from:"Workday HR (automated)",channel:"HR integration",opened:"9:22 AM",users:["rachel.adams"],close:"resolve",
  body:"<p>Rachel Adams begins a leave of absence today. Expected return Jan 4, 2027. Apply the LOA policy.</p>",
  lesson:"Leave is not termination. Disable to block use, but keep entitlements so she returns on day one. NIST AC-2.",
  grade:ts=>[C(!U("rachel.adams").enabled,"Account disabled for the leave",3),C(U("rachel.adams").groups.length===ROLES["Sales|Account Executive"].length,"Group memberships kept for her return",3)]},
 {id:"REQ0018881",type:"Request",pri:2,title:"New hire Ethan Moore: \"copy Bob's access\"",from:"Carla Jensen (Operations Manager)",channel:"Email",opened:"9:30 AM",users:["ethan.moore","bob.turner"],close:"resolve",
  body:"<p>\"Ethan starts today as a Dispatcher. Just give him the same access as Bob Turner so he can shadow him. Thanks!\"</p>",
  lesson:"Never mirror a peer. Peers carry leftover access, and copying spreads it. Provision from the role, and flag Bob's extras for review. NIST AC-6.",
  grade:ts=>[C(U("ethan.moore").enabled,"Account enabled",2),roleCheck("ethan.moore","Operations|Dispatcher",4),C(!has("ethan.moore","APP-SAP-AP-Entry")&&!has("ethan.moore","APP-Finance-Reports"),"Bob's leftover Finance access not copied",2)]},
 {id:"REQ0018884",type:"Question",pri:2,title:"Auditor request: SoD conflicts in AP",from:"External auditor (via Dana Whitfield)",channel:"Email",opened:"9:40 AM",users:[],close:"resolve",question:true,
  body:"<p>\"For SOX testing, please list every <b>enabled</b> user who currently holds <b>both</b> APP-SAP-AP-Entry and APP-SAP-AP-Approve.\"</p><p>Enter usernames (first.last) separated by commas, or <b>none</b>, in the answer box when you close the ticket.</p>",
  lesson:"Audit evidence must be complete and accurate. Pull it from the system, not from memory. Remediation is a separate, approved change. NIST AC-5.",
  grade:ts=>{
    const want=Object.values(S.users).filter(u=>u.enabled&&u.groups.includes("APP-SAP-AP-Entry")&&u.groups.includes("APP-SAP-AP-Approve")).map(u=>u.id).sort();
    const a=(ts.answer||"").toLowerCase();
    const got=Object.values(S.users).filter(u=>a.includes(u.id)||a.includes(u.name.toLowerCase())).map(u=>u.id).sort();
    const ok=want.length? want.join()===got.join() : (a.trim()==="none"&&!got.length);
    return [C(ok,"Answer matches the directory",5,ok?"":"Correct answer: "+(want.join(", ")||"none"))];
  }},
 {id:"INC0041240",type:"Incident",pri:1,title:"Impossible travel + MFA fatigue: Sam Okafor",from:"Entra ID Protection alert",channel:"SIEM alert",opened:"9:47 AM",users:["sam.okafor"],close:"resolve",
  body:"<p>High-risk sign-in. Sam Okafor signed in from Los Angeles at 9:02 AM and from Frankfurt at 9:19 AM. The Frankfurt sign-in followed 14 MFA push prompts, one of which was approved.</p><p>Sam confirmed by desk phone he did not travel and approved a prompt \"to make them stop.\"</p>",
  lesson:"Contain first: revoke sessions, rotate the password, re-register MFA (number matching), then hand off to Security. NIST IR-4, AC-12, IA-5.",
  grade:ts=>[C(U("sam.okafor").revoked,"Sessions revoked",3),C(U("sam.okafor").pwReset,"Password reset",2),C(U("sam.okafor").mfaReset,"MFA reset and re-registration required",2),C(esc(ts,"Security team"),"Escalated to the Security team",3)]}
];
